Repository Wai-Technologies/raaghu-react, pull requests merged in 2022-12, with the labels that each got.

#329 Made RdsCompUserPermission
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-mfe/rds_components/src/rds-comp-user-permission/rds-comp-user-permission.stories.tsx
  raaghu-mfe/rds_components/src/rds-comp-user-permission/rds-comp-user-permission.tsx
Labels: enhancement

#337 created yml file for storybook and mfe
  .github/workflows/development_raaghumfestageui.yml
  .github/workflows/development_storybookreact.yml
  .github/workflows/storybook-portal-live.yml
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: enhancement

#353 Removed the storybook from raaghu-elements and raaghu-mfe
  .github/workflows/development_raaghumfestageui.yml
  .github/workflows/storybook-portal-live.yml
  .storybook/main.js
  package.json
  raaghu-elements/.storybook/assets/playerIcon.svg
  raaghu-elements/.storybook/assets/raaghu-logo.svg
  raaghu-elements/.storybook/customTheme.js
  raaghu-elements/.storybook/main.js
  raaghu-elements/.storybook/manager.js
  raaghu-elements/.storybook/preview.js
  raaghu-elements/package.json
  raaghu-elements/src/rds-address-detail/rds-address-detail.tsx
  raaghu-elements/src/rds-list-group/rds-list-group.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-mfe/rds_components/src/rds-comp-email-settings-new/rds-comp-email-settings-new.tsx
  raaghu-mfe/rds_components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-mfe/rds_components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-mfe/rds_components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-mfe/rds_components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-mfe/rds_components/src/rds-comp-page-not-found/rds-comp-page-not-found.tsx
  raaghu-mfe/rds_components/src/rds-comp-product-image/rds-comp-product-image.tsx
  raaghu-mfe/rds_components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-mfe/rds_components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-mfe/rds_components/src/rds-comp-testimonials/rds-comp-testimonials.tsx
  raaghu-mfe/rds_components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/raaghu-logo.svg
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/rds_components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-mfe/rds_components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-mfe/rds_pages/dashboard/src/Dashboard/Dashboard.tsx
  raaghu-mfe/rds_pages/forgot-password/src/forgot-password/forgot-password.tsx
  raaghu-mfe/rds_pages/forgot-password/webpack.config.js
Labels: enhancement

#367 Added the stories of admin dashboard and webhook subscription . deploy test for anzstageui site
  .github/workflows/development_raaghumfestageui.yml
  .github/workflows/development_storybookreact.yml
  package.json
  raaghu-mfe/rds_components/src/rds-comp-address-input copy/rds-comp-api-scope-resource.scss
  raaghu-mfe/rds_components/src/rds-comp-address-input copy/rds-comp-api-scope-resource.stories.tsx
  raaghu-mfe/rds_components/src/rds-comp-address-input copy/rds-comp-api-scope-resource.tsx
  raaghu-mfe/rds_components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.stories.tsx
  raaghu-mfe/rds_components/src/rds-comp-api-scope-resource/rds-comp-api-scope-resource.tsx
  raaghu-mfe/rds_components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-mfe/rds_components/src/rds-comp-website-log/rds-comp-website-log.stories.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/tenant/src/tenant/tenant.tsx
  stories/Introduction.stories.mdx
  stories/assets/Demo.gif
  stories/assets/how.png
Labels: enhancement

#386 Created mfe-config file
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_components/src/App.tsx
  raaghu-mfe/rds_components/src/rds-comp-website-log/rds-comp-website-log.tsx
  raaghu-mfe/rds_pages/host/.env
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/utils/appconfig.json
  raaghu-mfe/utils/build.js
Labels: enhancement

#402 Build the host page and changes in file
  raaghu-mfe/package.json
  raaghu-mfe/rds_components/src/App.tsx
  raaghu-mfe/rds_components/src/rds-comp-edition-list/rds-comp-edition-list.tsx
  raaghu-mfe/rds_components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-mfe/rds_pages/dashboard/package.json
  raaghu-mfe/rds_pages/dashboard/webpack.config.js
  raaghu-mfe/rds_pages/forgot-password/package.json
  raaghu-mfe/rds_pages/forgot-password/src/forgot-password/forgot-password.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/package.json
  raaghu-mfe/rds_pages/login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/login/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/utils/build.js
Labels: bug, enhancement

#399 Alignment issue in introduction file of storybook
  stories/Introduction.stories.mdx
Labels: documentation, enhancement

#403 removed the public from gitignore
  .gitignore
  raaghu-mfe/rds_components/public/dashboard-data.png
  raaghu-mfe/rds_components/public/edit-pic.png
  raaghu-mfe/rds_components/public/profile-picture-circle.svg
  raaghu-mfe/rds_components/public/raaghu-logo.svg
  raaghu-mfe/rds_components/public/raaghu_icon.png
  raaghu-mfe/rds_pages/dashboard/public/dashboard-data.png
  raaghu-mfe/rds_pages/dashboard/public/profile-picture-circle.svg
  raaghu-mfe/rds_pages/dashboard/public/raaghu-logo.svg
  raaghu-mfe/rds_pages/dashboard/public/raaghu_icon.png
  raaghu-mfe/rds_pages/forgot-password/public/Login-card.svg
  raaghu-mfe/rds_pages/forgot-password/public/Raaghu-logo-mfe-black.png
  raaghu-mfe/rds_pages/forgot-password/public/body-backgroud.svg
  raaghu-mfe/rds_pages/forgot-password/public/index.html
  raaghu-mfe/rds_pages/host/public/bg_1.png
  raaghu-mfe/rds_pages/host/public/body-backgroud.svg
  raaghu-mfe/rds_pages/host/public/building_lights.mp4
  raaghu-mfe/rds_pages/host/public/dashboard-data.png
  raaghu-mfe/rds_pages/host/public/profile-picture-circle.svg
  raaghu-mfe/rds_pages/host/public/raaghu_icon.png
  raaghu-mfe/rds_pages/host/public/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/login/public/bg_1.png
  raaghu-mfe/rds_pages/login/public/body-backgroud.svg
  raaghu-mfe/rds_pages/login/public/raaghu_icon.png
  raaghu-mfe/rds_pages/login/public/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/maintainance/public/index.html
  raaghu-mfe/rds_pages/organization-units/public/index.html
  raaghu-mfe/rds_pages/settings/public/index.html
  raaghu-mfe/rds_pages/tenant/public/edit-pic.png
  raaghu-mfe/rds_pages/tenant/public/index.html
Labels: enhancement

#408 Update build.js
  raaghu-mfe/utils/build.js
Labels: bug

#409 Update webpack.config.js
  raaghu-mfe/rds_pages/login/webpack.config.js
Labels: bug

#418 changes in yml file and added web.config file for deployment
  .github/workflows/development_raaghumfestageui.yml
  raaghu-mfe/web.config
Labels: enhancement

#423 Added config file in host and changes in webpack.config file for deployment
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/index.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/webpack.config.js
Labels: bug

#424 fixed build issue in storybook
  package.json
Labels: bug

#431 Updated web.config file
  raaghu-mfe/web.config
Labels: bug

#433 Removed Mfe from components.
  raaghu-mfe/package.json
  raaghu-mfe/rds_components/src/App.tsx
  raaghu-mfe/rds_components/src/bootstrap.tsx
  raaghu-mfe/rds_components/src/index.ts
  raaghu-mfe/rds_components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-mfe/rds_components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-mfe/rds_components/webpack.config.js
  raaghu-mfe/rds_pages/dashboard/src/Dashboard/Dashboard.tsx
  raaghu-mfe/rds_pages/dashboard/webpack.config.js
  raaghu-mfe/rds_pages/forgot-password/src/forgot-password/forgot-password.tsx
  raaghu-mfe/rds_pages/forgot-password/webpack.config.js
  raaghu-mfe/rds_pages/host/src/index.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/login/webpack.config.js
  raaghu-mfe/rds_pages/rds-components.tsx
Labels: enhancement

#441 Changes in yml file for deployment
  .github/workflows/development_raaghumfestageui.yml
  raaghu-mfe/web.config
Labels: enhancement

#444 updated build.js and yml file for deployment
  .github/workflows/development_raaghumfestageui.yml
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/utils/build.js
Labels: enhancement

#449 changes the name forgot-password and added the assests folder in host.
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/forgotpassword/.env
  raaghu-mfe/rds_pages/forgotpassword/package.json
  raaghu-mfe/rds_pages/forgotpassword/public/Login-card.svg
  raaghu-mfe/rds_pages/forgotpassword/public/Raaghu-logo-mfe-black.png
  raaghu-mfe/rds_pages/forgotpassword/public/body-backgroud.svg
  raaghu-mfe/rds_pages/forgotpassword/public/index.html
  raaghu-mfe/rds_pages/forgotpassword/src/App.tsx
  raaghu-mfe/rds_pages/forgotpassword/src/bootstrap.tsx
  raaghu-mfe/rds_pages/forgotpassword/src/forgot-password/forgot-password.tsx
  raaghu-mfe/rds_pages/forgotpassword/src/index.ts
  raaghu-mfe/rds_pages/forgotpassword/src/remote.d.ts
  raaghu-mfe/rds_pages/forgotpassword/tsconfig.json
  raaghu-mfe/rds_pages/forgotpassword/webpack.config.js
  raaghu-mfe/rds_pages/host/assests/bg_1.png
  raaghu-mfe/rds_pages/host/assests/body-backgroud.svg
  raaghu-mfe/rds_pages/host/assests/building_lights.mp4
  raaghu-mfe/rds_pages/host/assests/dashboard-data.png
  raaghu-mfe/rds_pages/host/assests/profile-picture-circle.svg
  raaghu-mfe/rds_pages/host/assests/raaghu_icon.png
  raaghu-mfe/rds_pages/host/assests/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
Labels: enhancement

#455 Updated Webpack.config files.
  package.json
  raaghu-mfe/rds_pages/dashboard/webpack.config.js
  raaghu-mfe/rds_pages/forgotpassword/webpack.config.js
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/webpack.config.js
  raaghu-mfe/rds_pages/maintainance/webpack.config.js
  raaghu-mfe/rds_pages/organization-units/webpack.config.js
  raaghu-mfe/rds_pages/settings/webpack.config.js
Labels: bug

#454 Deleted all the env files from the pages and trying to add the images on the raaghu-site
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/dashboard/.env
  raaghu-mfe/rds_pages/dashboard/webpack.config.js
  raaghu-mfe/rds_pages/forgotpassword/.env
  raaghu-mfe/rds_pages/forgotpassword/src/App.tsx
  raaghu-mfe/rds_pages/forgotpassword/src/forgotpassword/forgotpassword.tsx
  raaghu-mfe/rds_pages/forgotpassword/webpack.config.js
  raaghu-mfe/rds_pages/host/.env
  raaghu-mfe/rds_pages/host/public/images/bg_1.png
  raaghu-mfe/rds_pages/host/public/images/body-backgroud.svg
  raaghu-mfe/rds_pages/host/public/images/building_lights.mp4
  raaghu-mfe/rds_pages/host/public/images/dashboard-data.png
  raaghu-mfe/rds_pages/host/public/images/profile-picture-circle.svg
  raaghu-mfe/rds_pages/host/public/images/raaghu_icon.png
  raaghu-mfe/rds_pages/host/public/images/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/.env
  raaghu-mfe/rds_pages/maintainance/.env
  raaghu-mfe/rds_pages/organization-units/.env
  raaghu-mfe/rds_pages/settings/.env
  raaghu-mfe/rds_pages/tenant/.env
  raaghu-mfe/rds_pages/under-maintainance/.env
Labels: enhancement

#457 Update webpack.config and top nav file.
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
Labels: bug

#458 Updated Webpack.config file.
  package.json
  raaghu-mfe/rds_pages/host/src/img/bg_1.png
  raaghu-mfe/rds_pages/host/src/img/body-backgroud.svg
  raaghu-mfe/rds_pages/host/src/img/building_lights.mp4
  raaghu-mfe/rds_pages/host/src/img/dashboard-data.png
  raaghu-mfe/rds_pages/host/src/img/profile-picture-circle.svg
  raaghu-mfe/rds_pages/host/src/img/raaghu_icon.png
  raaghu-mfe/rds_pages/host/src/img/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/host/webpack.config.js
Labels: bug

#462 updated webpack.config file
  raaghu-mfe/rds_pages/dashboard/webpack.config.js
  raaghu-mfe/rds_pages/forgotpassword/webpack.config.js
  raaghu-mfe/rds_pages/host/src/assets/bg_1.png
  raaghu-mfe/rds_pages/host/src/assets/body-backgroud.svg
  raaghu-mfe/rds_pages/host/src/assets/building_lights.mp4
  raaghu-mfe/rds_pages/host/src/assets/dashboard-data.png
  raaghu-mfe/rds_pages/host/src/assets/profile-picture-circle.svg
  raaghu-mfe/rds_pages/host/src/assets/raaghu_icon.png
  raaghu-mfe/rds_pages/host/src/assets/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/host/src/img/bg_1.png
  raaghu-mfe/rds_pages/host/src/img/body-backgroud.svg
  raaghu-mfe/rds_pages/host/src/img/building_lights.mp4
  raaghu-mfe/rds_pages/host/src/img/dashboard-data.png
  raaghu-mfe/rds_pages/host/src/img/profile-picture-circle.svg
  raaghu-mfe/rds_pages/host/src/img/raaghu_icon.png
  raaghu-mfe/rds_pages/host/src/img/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/login/webpack.config.js
Labels: bug

#463 Added the images to assets folder for each page
  raaghu-mfe/rds_pages/dashboard/public/assets/dashboard-data.png
  raaghu-mfe/rds_pages/dashboard/public/assets/profile-picture-circle.svg
  raaghu-mfe/rds_pages/dashboard/public/assets/raaghu-logo.svg
  raaghu-mfe/rds_pages/dashboard/public/assets/raaghu_icon.png
  raaghu-mfe/rds_pages/forgotpassword/public/assets/Login-card.svg
  raaghu-mfe/rds_pages/forgotpassword/public/assets/Raaghu-logo-mfe-black.png
  raaghu-mfe/rds_pages/forgotpassword/public/assets/body-backgroud.svg
  raaghu-mfe/rds_pages/forgotpassword/src/forgotpassword/forgotpassword.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/public/assets/bg_1.png
  raaghu-mfe/rds_pages/login/public/assets/body-backgroud.svg
  raaghu-mfe/rds_pages/login/public/assets/building_lights.mp4
  raaghu-mfe/rds_pages/login/public/assets/raaghu_icon.png
  raaghu-mfe/rds_pages/login/public/assets/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/port-config.ts
Labels: enhancement

#468 Changes in webpack to load images
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/assets/Login-card.svg
  raaghu-mfe/rds_pages/host/src/assets/Raaghu-logo-mfe-black.png
  raaghu-mfe/rds_pages/host/webpack.config.js
Labels: enhancement

#469 Update webpack.config.js
  raaghu-mfe/rds_pages/login/webpack.config.js
Labels: bug

#470 changes in path of images and in webpack file
  raaghu-mfe/rds_pages/forgotpassword/public/Login-card.svg
  raaghu-mfe/rds_pages/forgotpassword/public/Raaghu-logo-mfe-black.png
  raaghu-mfe/rds_pages/forgotpassword/public/body-backgroud.svg
  raaghu-mfe/rds_pages/forgotpassword/src/forgotpassword/forgotpassword.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/public/bg_1.png
  raaghu-mfe/rds_pages/login/public/body-backgroud.svg
  raaghu-mfe/rds_pages/login/public/building_lights.mp4
  raaghu-mfe/rds_pages/login/public/raaghu_icon.png
  raaghu-mfe/rds_pages/login/public/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/login/src/Login/Login.tsx
Labels: enhancement

#471 Changed the folder structure of the images
  raaghu-mfe/rds_pages/forgotpassword/public/assets/Login-card.svg
  raaghu-mfe/rds_pages/forgotpassword/public/assets/Raaghu-logo-mfe-black.png
  raaghu-mfe/rds_pages/forgotpassword/public/assets/body-backgroud.svg
  raaghu-mfe/rds_pages/forgotpassword/src/forgotpassword/forgotpassword.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/login/public/assets/bg_1.png
  raaghu-mfe/rds_pages/login/public/assets/body-backgroud.svg
  raaghu-mfe/rds_pages/login/public/assets/building_lights.mp4
  raaghu-mfe/rds_pages/login/public/assets/raaghu_icon.png
  raaghu-mfe/rds_pages/login/public/assets/raaghu_text_logo.svg
  raaghu-mfe/rds_pages/login/src/Login/Login.tsx
Labels: bug

#474 change in web.config file to add mp4 fie
  raaghu-mfe/rds_pages/host/src/assets/raaghu-logo.svg
  raaghu-mfe/web.config
Labels: enhancement

#479 Added the stories of pages and changed the background image of login page.
  .storybook/assets/raaghu_icon.png
  raaghu-elements/src/rds-address-detail/rds-address-detail.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
  raaghu-mfe/rds_components/public/assets/raaghu_icon.png
  raaghu-mfe/rds_components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/rds_pages/dashboard/src/Dashboard/Dashboard.stories.tsx
  raaghu-mfe/rds_pages/forgotpassword/src/forgotpassword/forgotpassword.stories.tsx
  raaghu-mfe/rds_pages/login/src/Login/Login.scss
  raaghu-mfe/rds_pages/login/src/Login/Login.stories.tsx
  raaghu-mfe/rds_pages/login/src/Login/Login.tsx
  stories/assets/raaghu_icon.png
Labels: enhancement

#486 Solved the bug for stories of pages and added the images of top navigation in assets folder
  .storybook/assets/profile-picture-circle.svg
  raaghu-elements/src/rds-side-nav/raaghu-logo.svg
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/rds_components/public/assets/dashboard-data.png
  raaghu-mfe/rds_components/public/assets/profile-picture-circle.svg
  raaghu-mfe/rds_components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/rds_pages/forgotpassword/src/forgotpassword/forgotpassword.stories.tsx
  raaghu-mfe/rds_pages/login/src/App.tsx
  raaghu-mfe/rds_pages/login/src/Login/Login.stories.tsx
Labels: bug

#487 Updated Dropdown list and top navigation
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-mfe/rds_components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: bug

#488 update package.json and yml file of storybook to show the images.
  .github/workflows/development_storybookreact.yml
  package.json
Labels: bug

#490 Enhanced Address detail and label element.
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/src/rds-address-detail/rds-address-detail.scss
  raaghu-elements/src/rds-address-detail/rds-address-detail.tsx
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.stories.tsx
  raaghu-elements/src/rds-label/rds-label.scss
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-range/rds-range.stories.tsx
  raaghu-elements/src/rds-size/rds-size.stories.tsx
  raaghu-elements/src/rds-spinner/rds-spinner.stories.tsx
  raaghu-elements/src/rds-stat/rds-stat.stories.tsx
  raaghu-elements/src/rds-tag/rds-tag.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
Labels: bug

#498 Created Npm package for Rds-elements, works without error for both jsx and tsx projects
  raaghu-components/package.json
  raaghu-elements/.npmignore
  raaghu-elements/package.json
  raaghu-elements/rollup.config.js
  raaghu-elements/tsconfig.json
Labels: enhancement

#503 Changes in build.js fie to run the site.
  .storybook/assets/bg_1.png
  .storybook/assets/building_lights.mp4
  .storybook/assets/raaghu_text_logo.svg
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
  raaghu-components/src/rds-comp-website-log/rds-comp-website-log.tsx
  raaghu-mfe/rds_pages/rds-elements.tsx
  raaghu-mfe/rds_pages/rds-page-login/public/assets/body-backgroud.svg
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.scss
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.tsx
  raaghu-mfe/rds_pages/rds-page-maintainance/src/remote.d.ts
  raaghu-mfe/utils/build.js
Labels: enhancement

#504 Enhancement in build.js file
  raaghu-mfe/utils/build.js
Labels: enhancement

#510 Added international language to raaghu-react. (Internationalization of raaghu-react)
  package.json
  raaghu-components/package.json
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/assets/i18n/af-NA.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/am-ET.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/ar.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/de.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/en-GB.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/en.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/es-MX.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/es.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/fr.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/it.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/nl.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/pt-BR.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/ru.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/th.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/tr.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/vi.json
  raaghu-mfe/rds_pages/host/src/assets/i18n/zh-Hans.json
  raaghu-mfe/rds_pages/host/src/bootstrap.tsx
  raaghu-mfe/rds_pages/host/src/i18n.js
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/af-NA.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/am-ET.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/ar.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/de.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/en-GB.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/en.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/es-MX.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/es.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/fr.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/it.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/nl.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/pt-BR.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/ru.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/th.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/tr.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/vi.json
  raaghu-mfe/rds_pages/rds-page-dashboard/public/assets/i18n/zh-Hans.json
  raaghu-mfe/rds_pages/rds-page-dashboard/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-dashboard/src/Dashboard/Dashboard.tsx
  raaghu-mfe/rds_pages/rds-page-dashboard/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-login/public/assets/i18n/en.json
  raaghu-mfe/rds_pages/rds-page-login/public/assets/i18n/es.json
  raaghu-mfe/rds_pages/rds-page-login/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-settings/tsconfig.json
Labels: enhancement

#515 Centralized the top and side component
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-dashboard/src/Dashboard/Dashboard.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#516 Updated i18n in host page.
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: enhancement

#524 Created Maintainance page and added few images to storybook
  .storybook/assets/Login-card.svg
  .storybook/assets/Raaghu-logo-mfe-black.png
  .storybook/assets/body-backgroud.svg
  .storybook/assets/dashboard-data.png
  raaghu-components/public/assets/edit-pic.png
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.scss
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.stories.tsx
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.tsx
Labels: enhancement

#533 Created folder structure of raaghu-themes and implemented themes in host, login , dashboard , forgotpassword
  .github/workflows/development_raaghumfestageui.yml
  raaghu-mfe/rds_pages/host/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-dashboard/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.tsx
  raaghu-themes/package.json
  raaghu-themes/themes/accessible.scss
  raaghu-themes/themes/accordion.scss
  raaghu-themes/themes/alert.scss
  raaghu-themes/themes/avatar.scss
  raaghu-themes/themes/badge.scss
  raaghu-themes/themes/blue.scss
  raaghu-themes/themes/breadcrumb.scss
  raaghu-themes/themes/button.scss
  raaghu-themes/themes/calender.scss
  raaghu-themes/themes/card.scss
  raaghu-themes/themes/carousel.scss
  raaghu-themes/themes/checkbox.scss
  raaghu-themes/themes/colorvariables-dark.scss
  raaghu-themes/themes/colorvariables-light.scss
  raaghu-themes/themes/colorvariables.scss
  raaghu-themes/themes/cookieconsent.scss
  raaghu-themes/themes/counter.scss
  raaghu-themes/themes/custom.scss
  raaghu-themes/themes/default.scss
  raaghu-themes/themes/dropdown.scss
  raaghu-themes/themes/file-uploader.scss
  raaghu-themes/themes/green.scss
  raaghu-themes/themes/input.scss
  raaghu-themes/themes/list-group.scss
  raaghu-themes/themes/nav-tab.scss
  raaghu-themes/themes/offcanvas.scss
  raaghu-themes/themes/orange.scss
  raaghu-themes/themes/pagination.scss
  raaghu-themes/themes/quillEditor.scss
  raaghu-themes/themes/radio-button.scss
  raaghu-themes/themes/responsive.scss
  raaghu-themes/themes/scrollspy.scss
  raaghu-themes/themes/search-input.scss
  raaghu-themes/themes/side-nav.scss
  raaghu-themes/themes/table.scss
  raaghu-themes/themes/tags.scss
  raaghu-themes/themes/textarea.scss
  raaghu-themes/themes/toast.scss
Labels: enhancement

#535 Added Edit Action in Data Table component
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.tsx
Labels: enhancement

#555 Implemented raaghu-themes in host and as well as storybook
  .github/workflows/development_storybookreact.yml
  .storybook/customTheme.js
  package.json
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-elements/src/rds-popover/index.ts
  raaghu-elements/src/style.scss
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/bootstrap.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-dashboard/src/Dashboard/Dashboard.tsx
  raaghu-mfe/rds_pages/rds-page-dashboard/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.stories.tsx
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/forgotpassword/forgotpassword.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.stories.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-login/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-maintainance/webpack.config.js
Labels: enhancement
