Repository Wai-Technologies/raaghu-react, pull requests merged in 2023-01, with the labels that each got.

#559 Improved Components in settings page and Added Settings page
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-invoice/rds-comp-invoice.tsx
  raaghu-components/src/rds-comp-other-settings/rds-comp-other-settings.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.scss
  raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-management/rds-comp-user-management.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-mfe/rds_pages/rds-page-edition/public/edit-pic.png
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.stories.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/remote.d.ts
  raaghu-mfe/rds_pages/rds-page-settings/tsconfig.json
Labels: enhancement

#560 Improved functionality of the side Navigation and added routing to the pages.
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-nav-new/rds-side-nav-main.tsx
  raaghu-elements/src/rds-side-nav-new/rds-side-nav-new.scss
  raaghu-elements/src/rds-side-nav/index.ts
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: enhancement

#562 Enhanced side nav and fixed top nav, and added Icon list to icons.tsx file.
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-nav/DarkMode.css
  raaghu-elements/src/rds-side-nav/DarkMode.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: enhancement

#565 Added VisualSetting , Settings , Edition , Webhook subscription, tenant , maintainance page to their routes
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-edition-list/rds-comp-edition-list.tsx
  raaghu-components/src/rds-comp-other-settings/rds-comp-other-settings.tsx
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-edition/package.json
  raaghu-mfe/rds_pages/rds-page-edition/public/index.html
  raaghu-mfe/rds_pages/rds-page-edition/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-organizationunits/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-settings/package.json
  raaghu-mfe/rds_pages/rds-page-settings/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-settings/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-settings/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-tenant/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-visual-setting/src/visualSetting/visualSetting.tsx
  raaghu-mfe/rds_pages/rds-page-visualSetting/package.json
  raaghu-mfe/rds_pages/rds-page-visualSetting/public/edit-pic.png
  raaghu-mfe/rds_pages/rds-page-visualSetting/public/index.html
  raaghu-mfe/rds_pages/rds-page-visualSetting/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-visualSetting/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-visualSetting/src/index.ts
  raaghu-mfe/rds_pages/rds-page-visualSetting/src/remote.d.ts
  raaghu-mfe/rds_pages/rds-page-visualSetting/src/visualSetting/visualSetting.stories.tsx
  raaghu-mfe/rds_pages/rds-page-visualSetting/src/visualSetting/visualSetting.tsx
  raaghu-mfe/rds_pages/rds-page-visualSetting/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-visualSetting/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/package.json
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/public/edit-pic.png
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/public/index.html
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/index.ts
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/remote.d.ts
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.stories.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/webpack.config.js
Labels: enhancement

#566 Added build script to the pages
  raaghu-mfe/rds_pages/rds-page-edition/package.json
  raaghu-mfe/rds_pages/rds-page-maintainance/package.json
  raaghu-mfe/rds_pages/rds-page-settings/package.json
  raaghu-mfe/rds_pages/rds-page-tenant/package.json
  raaghu-mfe/rds_pages/rds-page-visualSetting/package.json
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/package.json
Labels: bug

#576 Added toggle element.
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/rds-toggle-switch/rds-toggle-switch.scss
  raaghu-elements/src/rds-toggle-switch/rds-toggle-switch.stories.tsx
  raaghu-elements/src/rds-toggle-switch/rds-toggle-switch.tsx
  raaghu-elements/src/rds-toggle/index.ts
  raaghu-elements/src/rds-toggle/rds-toggle.scss
  raaghu-elements/src/rds-toggle/rds-toggle.stories.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
Labels: enhancement

#577 Added the logout functionality
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.tsx
Labels: enhancement

#583 Added i18n internationalization to the tenant page.
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: enhancement

#585 Changed the UI of profile component and solved the bug for after refreshing the individual pages
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.scss
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#600 Enhancement in counter element
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-elements/src/rds-button/rds-button.scss
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: bug, enhancement

#609 Added the audit log page in anz site and solved the bug for routing when the user is not logged in
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/rds-page-auditLogs/package.json
  raaghu-mfe/rds_pages/rds-page-auditLogs/public/index.html
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/webpack.config.js
Labels: enhancement

#610 Enhanced line chart and Bar Chart in Dashboard.
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.stories.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.stories.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/af-NA.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/am-ET.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/ar.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/de.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/en-GB.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/en.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/es-MX.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/es.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/fr.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/it.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/nl.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/pt-BR.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/ru.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/th.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/tr.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/vi.json
  raaghu-mfe/rds_pages/rds-page-tenant/public/assets/i18n/zh-Hans.json
Labels: enhancement

#612 Refactor elements
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.scss
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
  raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.scss
  raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.scss
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.stories.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.stories.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
  raaghu-elements/src/rds-modal/rds-modal.stories.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: enhancement

#618 Solved the bug for routing when the user enter the login credential and did some ui changes like change in data table and in edition page
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-edition-list/rds-comp-edition-list.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.stories.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.tsx
  raaghu-mfe/libs/shared/AuthGuard.tsx
  raaghu-mfe/libs/state-management/login/login-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: enhancement

#622 Solved the bug for Vertically centered modal
  raaghu-components/src/index.ts
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-modal/rds-modal.stories.tsx
Labels: enhancement

#626 Added icon to the center of the boolean chart.
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-elements/src/rds-chart-boolean/chart-icons.ts
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.tsx
Labels: enhancement

#647 Enhancement in Language Page
  raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.scss
  raaghu-elements/src/rds-label/rds-label.scss
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.scss
  raaghu-mfe/rds_pages/rds-page-language/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.tsx
Labels: enhancement

#668 Enhanced Top-navigation and rectified build error.
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-client-resources/rds-comp-client-resources.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-subscription/rds-comp-subscription.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.scss
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug, enhancement

#669 Enhancement in Rds Avatar and Rds Card
  raaghu-elements/src/rds-avatar/rds-avatar.scss
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.scss
  raaghu-elements/src/rds-card/rds-card.scss
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-notification/rds-notification.scss
  raaghu-mfe/libs/shared/AuthGuard.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/package.json
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/public/index.html
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/bootstrap.tsx
  raaghu-themes/themes/default.scss
Labels: enhancement

#677 Imporved Users Page and data table styling.
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.stories.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#679 Enhancement in Big Number and Widget Element
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-elements/libs/types/colorvariant.ts
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.tsx
  raaghu-elements/src/rds-card/rds-card.scss
  raaghu-elements/src/rds-widget/rds-widget.scss
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: bug, enhancement

#683 Enhancement in app detail and solved the build error
  raaghu-elements/src/rds-app-detail/rds-app-detail.scss
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
Labels: enhancement

#687 did the enhancement in like-dislike element
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.scss
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.stories.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
Labels: enhancement

#693 Enhanced the ui of tenant Page.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#695 Fixed some issues Carousel Element.
  raaghu-elements/src/rds-carousel/rds-carousel.stories.tsx
  raaghu-elements/src/rds-carousel/rds-carousel.tsx
Labels: bug

#699 Fixed error in setting page , Tenant management component, top navigation component.
  raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
Labels: bug

#716 Added Permission Tree, Icon List component and Added Icon List page in the anz site.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.stories.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-ree.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-child/Checkbox.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-child/CheckboxList.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-child/checkbox.module.scss
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-child/checkboxlist.module.scss
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-child/updateItemStates.ts
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new-child.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-trial.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-search/rds-search.stories.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-iconlist/package.json
  raaghu-mfe/rds_pages/rds-page-iconlist/public/index.html
  raaghu-mfe/rds_pages/rds-page-iconlist/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-iconlist/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-iconlist/src/iconlist/iconlist.stories.tsx
  raaghu-mfe/rds_pages/rds-page-iconlist/src/iconlist/iconlist.tsx
  raaghu-mfe/rds_pages/rds-page-iconlist/src/index.ts
  raaghu-mfe/rds_pages/rds-page-iconlist/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-iconlist/webpack.config.js
Labels: enhancement
