Repository Wai-Technologies/raaghu-react, pull requests merged in 2023-04, with the labels that each got.

#1164 Development abp
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-forms-email/index.ts
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.stories.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-forms-response/index.ts
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.stories.tsx
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/rds-page-forms-preview/package.json
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/FormsPreview/FormsPreview.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/package.json
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
Labels: bug

#1172 Update webpack.config.js
  raaghu-mfe/rds_pages/host/webpack.config.js
Labels: bug

#1181 Storybook build issues
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.stories.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.test.tsx
Labels: bug

#1173 Component page creation
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-forms-email/index.ts
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.stories.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-forms-response/index.ts
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.stories.tsx
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/rds-page-forms-preview/package.json
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/FormsPreview/FormsPreview.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/package.json
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
Labels: enhancement

#1174 Update rds-dropdown-list.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: bug

#1175 Added Raaghu-core
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-core/.editorconfig
  raaghu-core/.eslintignore
  raaghu-core/.eslintrc
  raaghu-core/.gitignore
  raaghu-core/.prettierrc
  raaghu-core/.travis.yml
  raaghu-core/README.md
  raaghu-core/package.json
  raaghu-core/src/.eslintrc
  raaghu-core/src/index.test.tsx
  raaghu-core/src/index.tsx
  raaghu-core/src/models/environment.ts
  raaghu-core/src/proxy/api-exploring/api-definition.service.ts
  raaghu-core/src/proxy/application-configurations/raaghu-application-configuration.service.tsx
  raaghu-core/src/proxy/application-configurations/raaghu-application-localization.service.tsx
  raaghu-core/src/proxy/models.tsx
  raaghu-core/src/proxy/multi-tenancy/abp-tenant.service.tsx
  raaghu-core/src/proxy/multi-tenancy/raaghu-multi-tenancy-tenant.service.tsx
  raaghu-core/src/proxy/token/connect-token.ts
  raaghu-core/src/redux/actions/action.creator.tsx
  raaghu-core/src/redux/actions/action.types.tsx
  raaghu-core/src/redux/actions/index.tsx
  raaghu-core/src/redux/reducers/configReducer.tsx
  raaghu-core/src/redux/reducers/index.tsx
  raaghu-core/src/redux/reducers/localizationReducer.tsx
  raaghu-core/src/redux/reducers/multiTenancyReducer.tsx
  raaghu-core/src/services/config-state-service.tsx
  raaghu-core/src/services/localization.service.tsx
  raaghu-core/src/services/multi-tenancy.service.tsx
  raaghu-core/src/services/permission-service.tsx
  raaghu-core/src/services/rest.service.tsx
  raaghu-core/src/services/session-state-service.tsx
  raaghu-core/src/styles.module.css
  raaghu-core/src/tokens/tenant-key.token.ts
  raaghu-core/src/typings.d.ts
  raaghu-core/src/utils/interceptor.ts
  raaghu-core/src/utils/internal-store-utils.ts
  raaghu-core/tsconfig.json
  raaghu-core/tsconfig.test.json
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-icon/flag-icons.tsx
  raaghu-mfe/index.js
  raaghu-mfe/libs/raaghu-core.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/libs/state-management/config/config-slice.ts
  raaghu-mfe/libs/state-management/config/config.model.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/localization/localization-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/.env
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-login/.env
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#1176 changes in search filter functionality
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.scss
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.scss
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#1179 committed for two fact tab state management and data-binding
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-mfe/libs/state-management/my-account/my-account-slice.ts
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
Labels: enhancement

#1182 state management for chat module
  raaghu-mfe/libs/state-management/chats/chats-slice.ts
Labels: bug

#1184 Build issues resolved
  raaghu-core/.npmrc
  raaghu-core/src/services/permission-service.tsx
Labels: bug

#1185 Build issues resolved
  raaghu-components/src/rds-comp-elements/rds-comp-elements.stories.tsx
  raaghu-components/src/rds-comp-elements/rds-comp-elements.test.tsx
Labels: bug

#1188 Update mfe-config.ts
  raaghu-mfe/rds_pages/mfe-config.ts
Labels: bug

#1193 Updated node script for writing standard layout for the pages and updated addidng side nav items to the bottom of the side nav list.
  page-template/template/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  utils/create.js
Labels: bug, enhancement

#1194 committed-blogger-bug
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
Labels: bug

#1198 Build issues are resolved.
  package.json
  raaghu-elements/package.json
  raaghu-elements/src/rds-text-editor/rds-text-editor.tsx
  raaghu-mfe/package.json
Labels: bug

#1206 Development abp
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-forms-email/index.ts
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.stories.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-forms-response/index.ts
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.stories.tsx
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-core/src/utils/interceptor.ts
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.scss
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-forms-preview/package.json
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/FormsPreview/FormsPreview.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/package.json
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
Labels: bug

#1209 Development abp
  raaghu-components/package.json
  raaghu-elements/package.json
  raaghu-mfe/package.json
Labels: enhancement

#1218 committed for build issue
  .vs/slnx.sqlite
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
Labels: bug

#1210 offcanvas blacking out, top-nav in login, datatable action box size
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/libs/state-management/settings/settings-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
Labels: bug

#1227 core updated and alert implemented
  raaghu-core/src/index.tsx
  raaghu-core/src/models/environment.ts
  raaghu-core/src/proxy/api-exploring/api-definition.service.ts
  raaghu-core/src/proxy/application-configurations/raaghu-application-configuration.service.tsx
  raaghu-core/src/proxy/application-configurations/raaghu-application-localization.service.tsx
  raaghu-core/src/proxy/models.tsx
  raaghu-core/src/proxy/token/connect-token.ts
  raaghu-core/src/redux/actions/action.creator.tsx
  raaghu-core/src/redux/actions/action.types.tsx
  raaghu-core/src/redux/actions/index.tsx
  raaghu-core/src/redux/reducers/configReducer.tsx
  raaghu-core/src/redux/reducers/index.tsx
  raaghu-core/src/redux/reducers/localizationReducer.tsx
  raaghu-core/src/redux/reducers/multiTenancyReducer.tsx
  raaghu-core/src/services/config-state-service.tsx
  raaghu-core/src/services/localization.service.tsx
  raaghu-core/src/services/rest.service.tsx
  raaghu-core/src/utils/interceptor.ts
  raaghu-core/src/utils/internal-store-utils.ts
  raaghu-core/tsconfig.json
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
  utils/create.js
Labels: bug

#1228 interceptor added into lib/service
  raaghu-mfe/libs/shared/interceptor.ts
Labels: bug

#1234 committed for build issue
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
Labels: bug

#1235 Update create.js file to add import and export statement automatically in reducer and creating slice file.
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-elements/package.json
  raaghu-mfe/rds_pages/rds-page-myaccount/package.json
  raaghu-mfe/rds_pages/rds-page-personaldata/package.json
  raaghu-mfe/rds_pages/rds-page-rdscomponents/package.json
  raaghu-mfe/rds_pages/rds-page-urlforwarding/package.json
  utils/create.js
Labels: enhancement

#1244 committed for url issue in build webpack.config.js for forms
  .vs/slnx.sqlite
  raaghu-mfe/rds_pages/host/webpack.config.js
Labels: bug

#1252 Created Menus page, New menus component ,Resolved bugs in pages and added alert in user, urlforwarding and tag pages
  page-template/template/src/App.tsx
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/state-management/forgot-password/forgotpassword-slice.ts
  raaghu-mfe/libs/state-management/hooks.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/localization/localization-slice.ts
  raaghu-mfe/libs/state-management/menus/menus-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/FormsPreview/FormsPreview.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-language/package.json
  raaghu-mfe/rds_pages/rds-page-menus/.gitignore
  raaghu-mfe/rds_pages/rds-page-menus/package.json
  raaghu-mfe/rds_pages/rds-page-menus/public/index.html
  raaghu-mfe/rds_pages/rds-page-menus/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-menus/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-menus/src/index.ts
  raaghu-mfe/rds_pages/rds-page-menus/src/menus/menus.tsx
  raaghu-mfe/rds_pages/rds-page-menus/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-menus/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-paymentPlans/package.json
  raaghu-mfe/rds_pages/rds-page-paymentPlans/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-paymentRequests/package.json
  raaghu-mfe/rds_pages/rds-page-polls/package.json
  raaghu-mfe/rds_pages/rds-page-roles/package.json
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/security-logs/SecurityLogs.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
  raaghu-mfe/rds_pages/rds-page-tags/src/tags/tags.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/package.json
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-users/package.json
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
  raaghu-mfe/rds_pages/rds-page-visualSetting/package.json
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/package.json
Labels: bug

#1250 create a file mover component
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-components/src/rds-comp-file-mover/index.ts
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.scss
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.stories.tsx
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-icon-label/rds-icon-label.tsx
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#1254 Development abp
  raaghu-components/package.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.stories.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-elements/elements/accordion.tsx
  raaghu-components/src/rds-comp-elements/elements/alert.tsx
  raaghu-components/src/rds-comp-elements/elements/appDetail.tsx
  raaghu-components/src/rds-comp-elements/index.ts
  raaghu-components/src/rds-comp-elements/rds-comp-elements.scss
  raaghu-components/src/rds-comp-elements/rds-comp-elements.styled.ts
  raaghu-components/src/rds-comp-elements/rds-comp-elements.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.scss
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
  raaghu-mfe/libs/main-menu/elements.ts
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/main-menu/personal-data.ts
  raaghu-mfe/libs/main-menu/rds-components.ts
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-elements/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-elements/src/elements/elements.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: enhancement

#1245 Implement eye icon to password input
  .vs/slnx.sqlite
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-components/index.ts
  raaghu-components/src/rds-comp-components/rds-comp-components.stories.tsx
  raaghu-components/src/rds-comp-components/rds-comp-components.styled.ts
  raaghu-components/src/rds-comp-components/rds-comp-components.test.tsx
  raaghu-components/src/rds-comp-components/rds-comp-components.tsx
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-input/rds-input.scss
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-mfe/libs/main-menu/components.ts
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/pages.ts
  raaghu-mfe/libs/main-menu/rds-components.ts
  raaghu-mfe/libs/state-management/components/components-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/pages/pages-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-components/.gitignore
  raaghu-mfe/rds_pages/rds-page-components/package.json
  raaghu-mfe/rds_pages/rds-page-components/public/index.html
  raaghu-mfe/rds_pages/rds-page-components/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-components/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-components/src/components/components.tsx
  raaghu-mfe/rds_pages/rds-page-components/src/index.ts
  raaghu-mfe/rds_pages/rds-page-components/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-components/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-pages/.gitignore
  raaghu-mfe/rds_pages/rds-page-pages/package.json
  raaghu-mfe/rds_pages/rds-page-pages/public/index.html
  raaghu-mfe/rds_pages/rds-page-pages/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-pages/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-pages/src/index.ts
  raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx
  raaghu-mfe/rds_pages/rds-page-pages/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-pages/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-rdscomponents/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-rdscomponents/src/rds-components/rds-components.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  utils/create.js
Labels: enhancement

#1256 Changes done in Generate proxy CLI script
  package.json
  raaghu-core/package.json
  swaggerJSON.json
  utils/generateProxy.js
Labels: bug

#1262 CLI related changes
  package.json
  raaghu-components/src/index.ts
  utils/create.js
  utils/generateProxy.js
Labels: enhancement

#1277 Development abp
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-blog-post/index.ts
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.stories.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.styled.ts
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.test.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/libs/main-menu/blog-post.ts
  raaghu-mfe/libs/main-menu/components.ts
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/state-management/blog-post/blog-post-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-blogpost/.gitignore
  raaghu-mfe/rds_pages/rds-page-blogpost/package.json
  raaghu-mfe/rds_pages/rds-page-blogpost/public/index.html
  raaghu-mfe/rds_pages/rds-page-blogpost/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/index.ts
  raaghu-mfe/rds_pages/rds-page-blogpost/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-blogpost/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: enhancement

#1279 solved bugs in pages
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.scss
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-mfe/libs/state-management/settings/settings-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-elements/src/elements/elements.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
Labels: bug

#1280 Updated slice file of Application, Blogs, Chats, Claim-types, comment, edition, forgot-password, forms, language-text, my-account, organization-tree, payment-request, personal-data, Security-logs, tags, text-template, url-forwarding, page and removed debugger from few pages.
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-components/src/rds-comp-elements/rds-comp-elements.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-mfe/libs/proxy/core/OpenAPI.ts
  raaghu-mfe/libs/state-management/Blogs/blogs-slice.ts
  raaghu-mfe/libs/state-management/applications/applications-slice.ts
  raaghu-mfe/libs/state-management/chats/chats-slice.ts
  raaghu-mfe/libs/state-management/claim-types/claim-types-slice.ts
  raaghu-mfe/libs/state-management/comments/comments-slice.ts
  raaghu-mfe/libs/state-management/edition/edition-slice.ts
  raaghu-mfe/libs/state-management/forgot-password/forgotpassword-slice.ts
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/libs/state-management/host/host-slice.ts
  raaghu-mfe/libs/state-management/language-text/language-text-slice.ts
  raaghu-mfe/libs/state-management/my-account/my-account-slice.ts
  raaghu-mfe/libs/state-management/organization-tree/organization-tree-slice.ts
  raaghu-mfe/libs/state-management/payment-requests/paymentRequests-slice.ts
  raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
  raaghu-mfe/libs/state-management/polls/polls-slice.ts
  raaghu-mfe/libs/state-management/security-logs/security-logs-slice.ts
  raaghu-mfe/libs/state-management/settings/settings-slice.ts
  raaghu-mfe/libs/state-management/tags/tags-slice.ts
  raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
  raaghu-mfe/libs/state-management/url-forwarding/url-forwarding-slice.ts
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/FormsPreview/FormsPreview.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
Labels: enhancement

#1282 Development abp >UI for forms page
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/FormsPreview/FormsPreview.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
Labels: bug

#1288 breadcrum applied for all pages
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#1284 commited for newsletter page
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/newsletters/newsletters-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-newsletters/.gitignore
  raaghu-mfe/rds_pages/rds-page-newsletters/package.json
  raaghu-mfe/rds_pages/rds-page-newsletters/public/index.html
  raaghu-mfe/rds_pages/rds-page-newsletters/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-newsletters/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-newsletters/src/index.ts
  raaghu-mfe/rds_pages/rds-page-newsletters/src/newsletters/Newsletters.tsx
  raaghu-mfe/rds_pages/rds-page-newsletters/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-newsletters/webpack.config.js
Labels: bug

#1290 changes in service proxy files of different pages
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-mfe/libs/state-management/apiScope/apiScope-slice.ts
  raaghu-mfe/libs/state-management/blogger/blogger-slice.ts
  raaghu-mfe/libs/state-management/language/language-slice.ts
  raaghu-mfe/libs/state-management/menus/menus-slice.ts
  raaghu-mfe/libs/state-management/payment-plans/paymentPlans-slice.ts
  raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
  raaghu-mfe/libs/state-management/polls/polls-slice.ts
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
Labels: enhancement

#1291 Development abp
  package.json
  raaghu-mfe/utils/build.js
  utils/install-all.js
Labels: enhancement

#1292 committed changes for my-account slice file
  .vs/slnx.sqlite
  raaghu-mfe/libs/state-management/my-account/my-account-slice.ts
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
Labels: bug

#1293 Added menus directory component and added menus page
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/menus/menus-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/rds-page-menus/src/menus/menus.tsx
Labels: bug

#1294 Update tenant.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug

#1305 Resolved build issues
  raaghu-mfe/libs/state-management/newsletters/newsletters-slice.ts
  raaghu-mfe/rds_pages/rds-page-newsletters/src/newsletters/Newsletters.tsx
Labels: bug

#1304 Blog-post page create slice file.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-blog-post-new/index.ts
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.stories.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.styled.ts
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.test.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-mfe/libs/state-management/blog-post/blog-post-slice.ts
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
Labels: enhancement

#1307 Added parent items to the list items while running the create module command. and added select list.
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  utils/create.js
Labels: enhancement

#1309 removed menu item heading from menus page
  raaghu-mfe/rds_pages/rds-page-menus/src/menus/menus.tsx
Labels: bug

#1321 Resolved Bug
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.stories.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.stories.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.stories.tsx
  raaghu-components/src/rds-comp-components/rds-comp-components.stories.tsx
  raaghu-components/src/rds-comp-elements/rds-comp-elements.stories.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.stories.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.stories.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.stories.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.stories.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.stories.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/main-menu/pages.ts
  raaghu-mfe/rds_pages/host/public/favicon.ico
Labels: bug

#1323 committed changes for removing rdscomponents page
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
Labels: bug

#1325 Development abp
  package.json
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/utils/build.js
  utils/generateProxy.js
  utils/start-scripts.js
Labels: enhancement

#1324 Adding storybook favicon
  .storybook/assets/favicon.ico
  .storybook/images/favicon.ico
  .storybook/manager-head.html
  package.json
Labels: bug

#1326 committed changes for warnings for pages while build
  .vs/slnx.sqlite
  page-template/template/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-apiResources/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-apiScope/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-applications/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-auditLogs/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-blogpost/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-blogs/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-client/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-components/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-edition/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-elements/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-identityResources/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-maintainance/webpack.config.js
Labels: bug

#1332 Version changed for raaghu-react-core
  package.json
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#1333 Development abp
  package.json
  raaghu-mfe/libs/state-management/config/config-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  utils/create.js
  utils/generateProxy.js
Labels: bug

#1334 raaghu-themes version is incremented.
  package.json
  raaghu-mfe/package.json
Labels: bug

#1336 Build issues are resolved.
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#1344 Update tenant.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug

#1346 committed for issues #1207 #1229 #1300 #1330
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.scss
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1356 committed for build time optimize
  raaghu-mfe/rds_pages/rds-page-menus/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-myaccount/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-pages/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-personaldata/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-scope/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-settings/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-undermaintainance/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-urlforwarding/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-visualSetting/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/webpack.config.js
Labels: bug

#1349 Changes are commited for users
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/public/index.html
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1364 changes in file management page
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-mfe/libs/proxy/core/OpenAPI.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
  raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
  raaghu-mfe/libs/state-management/polls/polls-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-newsletters/src/newsletters/Newsletters.tsx
Labels: enhancement

#1367 Updated slice file for news-letters, global-resources, blog-post, and audit-log slice file. Deleted the older service-proxy file and remove errors after deleting the previous service-proxy file. Also applied localization key-value to the side-navigation main-menu.
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/shared/public.api.ts
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/libs/state-management/apiScope/apiScope-slice.ts
  raaghu-mfe/libs/state-management/applications/applications-slice.ts
  raaghu-mfe/libs/state-management/audit-logs/audit-log-slice.ts
  raaghu-mfe/libs/state-management/blog-post/blog-post-slice.ts
  raaghu-mfe/libs/state-management/blogger/blogger-slice.ts
  raaghu-mfe/libs/state-management/chats/chats-slice.ts
  raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/libs/state-management/global-resources/globalResources-slice.ts
  raaghu-mfe/libs/state-management/language/language-slice.ts
  raaghu-mfe/libs/state-management/newsletters/newsletters-slice.ts
  raaghu-mfe/libs/state-management/payment-plans/paymentPlans-slice.ts
  raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
  raaghu-mfe/libs/state-management/polls/polls-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug, enhancement

#1368 Development abp
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1375 create edit for blogpost slice file.
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/libs/state-management/blog-post/blog-post-slice.ts
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
Labels: bug

#1376 Resolved the build error in Tenant page , language, and language text page
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1377 PR for task #1242, #1274 and #1275
  .vs/slnx.sqlite
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-newPage/index.ts
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.stories.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.styled.ts
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.test.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  raaghu-components/src/rds-comp-pages/index.ts
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
  raaghu-components/src/rds-comp-pages/rds-comp-pages.styled.ts
  raaghu-components/src/rds-comp-pages/rds-comp-pages.test.tsx
  raaghu-components/src/rds-comp-pages/rds-comp-pages.tsx
  raaghu-mfe/libs/state-management/pages/pages-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx
Labels: enhancement

#1379 Development abp
  raaghu-mfe/libs/proxy/core/OpenAPI.ts
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/rds_pages/host/.env
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#1386 Build issues are resolved
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/webpack.config.js
Labels: bug

#1389 Development abp
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.stories.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  utils/create.js
Labels: bug

#1390 Removed unwanted files
  raaghu-mfe/libs/shared/array-to-tree-converter.tsx
  raaghu-mfe/libs/shared/axios-interceptor.tsx
  raaghu-mfe/libs/shared/i18n.ts
Labels: bug

#1387 necessary changes according to core
  raaghu-mfe/libs/shared/AuthGuard.tsx
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/shared/public.api.ts
  raaghu-mfe/libs/state-management/host/host-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/login/login-slice.ts
  raaghu-mfe/libs/state-management/login/loginModels.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#1398 Versions are incremented
  package.json
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
  raaghu-mfe/libs/public.api.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/state-management/config/config-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  utils/create.js
  utils/generateProxy.js
Labels: enhancement

#1400 Build issues are resolved.
  raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
  raaghu-mfe/libs/state-management/host/host-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/bootstrap.tsx
  raaghu-mfe/rds_pages/host/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-dashboard/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-globalResources/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-identityResources/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/bootstrap.tsx
Labels: bug

#1391 Added missing functionality in language text page and Scope page
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-mfe/libs/state-management/language-text/language-text-slice.ts
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
Labels: enhancement

#1395 Development abp
  raaghu-mfe/libs/state-management/pages/pages-slice.ts
  raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx
Labels: enhancement

#1396 refactored toast element and applied bootstrap js in storybook
  .storybook/preview.js
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-elements/src/style.scss
Labels: enhancement

#1397 drag and drop functionality
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#1399 Development abp
  raaghu-mfe/libs/state-management/chats/chats-slice.ts
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
Labels: bug

#1402 Created toast element and it types
  .storybook/preview.js
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: enhancement

#1403 Update languageText.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
Labels: bug

#1404 Added ActionPosition in data table and resolve bugs in tenant page and global resource page
  raaghu-components/src/rds-comp-billing/rds-comp-billing.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-dynamic-properties/rds-comp-dynamic-properties.tsx
  raaghu-components/src/rds-comp-edition-list/rds-comp-edition-list.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
  raaghu-components/src/rds-comp-pages/rds-comp-pages.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-security-logs/rds-comp-security-logs.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
  raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.tsx
  raaghu-components/src/rds-comp-user-table/rds-comp-user-table.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/shared/array-to-tree-converter.tsx
  raaghu-mfe/libs/state-management/host/host-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-apiResources/src/apiResources/apiResources.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-client/src/client/client.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-globalResources/src/globalResources/globalResources.tsx
  raaghu-mfe/rds_pages/rds-page-identityResources/src/IdentityResources/IdentityResources.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-newsletters/src/newsletters/Newsletters.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
  raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-scope/src/Scope/Scope.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/security-logs/SecurityLogs.tsx
  raaghu-mfe/rds_pages/rds-page-tags/src/tags/tags.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.tsx
Labels: enhancement

#1407 Restructuring sidenav
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-icon/flag-icons.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/rds_pages/host/.env
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: enhancement

#1408 Resolved 1361 and added icon width, height, and fill in element
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
Labels: bug

#1410 Resolve Add, Edit & Delete tag functionality
  raaghu-mfe/libs/state-management/tags/tags-slice.ts
Labels: bug

#1414 Fixed vertical alignment issue for ellipsis in data table.
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
Labels: bug

#1416 committed for issue #1340 and #1363
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-mfe/libs/state-management/security-logs/security-logs-slice.ts
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
Labels: bug

#1417 top navigation chat icon changes and sidebar child dropdown position changes
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: bug

#1418 Rectified the issue of data table in roles page.
  .github/workflows/development_raaghumfestageui.yml
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/rds_pages/host/.env
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: bug

#1421 sidebar logo issue.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#1429 Environment variable is not accessible, so replaced it with sessionSt…
  package.json
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#1428 PR for remove inline styles from login page
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/assets/fg_raaghu.png
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.scss
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#1438 Development abp
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
  raaghu-mfe/libs/public.api.ts
  raaghu-mfe/libs/shared/i18n.ts
  raaghu-mfe/libs/shared/public.api.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1439 updated roles-slice file
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
Labels: bug

#1440 PR for remove inline style and eye icon issue of password input
  raaghu-elements/src/rds-input/rds-input.scss
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-modal/rds-modal.tsx
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/forgotpassword/forgotpassword.scss
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/forgotpassword/forgotpassword.tsx
Labels: bug, enhancement

#1441 sidenav changer
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
Labels: bug

#1442 maintain same between inner body and outer area for all the pages
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-security-logs/rds-comp-security-logs.tsx
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-menus/src/menus/menus.tsx
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
  raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/security-logs/SecurityLogs.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
  raaghu-mfe/rds_pages/rds-page-tags/src/tags/tags.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#1452 Resolved the issue in profile of top navigation.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: bug

#1456 Add class to navtab and dropdown for handcursor
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: bug, enhancement

#1467 Development abp
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.scss
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-modal/rds-modal.scss
  raaghu-elements/src/rds-modal/rds-modal.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: bug

#1468 Implemented jest for raaghu application.
  package.json
  raaghu-elements/package.json
  raaghu-elements/src/rds-button/rds-button.test.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-icon/rds-icon.test.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-input/rds-input.test.tsx
  raaghu-elements/src/rds-tooltip/rds-tooltip.tsx
Labels: enhancement

#1469 Implemented Element Page functionality.
  raaghu-components/src/rds-comp-elements/code_snippet.ts
  raaghu-components/src/rds-comp-elements/elements/accordion.tsx
  raaghu-components/src/rds-comp-elements/elements/addressDetail.tsx
  raaghu-components/src/rds-comp-elements/elements/alert.tsx
  raaghu-components/src/rds-comp-elements/elements/appDetail.tsx
  raaghu-components/src/rds-comp-elements/elements/avatar.tsx
  raaghu-components/src/rds-comp-elements/elements/badge.tsx
  raaghu-components/src/rds-comp-elements/rds-comp-elements.tsx
  raaghu-components/src/rds-comp-top-navigation/element-list.ts
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-mfe/rds_pages/rds-page-elements/src/elements/elements.tsx
Labels: enhancement

#1470 Removed jiggle from sidebar.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#1472 plus icon issue
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: bug

#1478 PR for remove inline styling for roles page
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug, enhancement

#1485 Remember me login Page
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-mfe/libs/proxy/core/OpenAPI.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/openid.config.ts
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#1487 solved bugs #1233 #1453 #1444 #1445 #1446
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1492 Application issue, canvas title issue, audit log spacing issue
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug

#1494 Implemented component page and resolve all the issues related to it.
  raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
  raaghu-components/src/rds-comp-components/code_snippet.ts
  raaghu-components/src/rds-comp-components/components/cache.tsx
  raaghu-components/src/rds-comp-components/components/cardDetailList.tsx
  raaghu-components/src/rds-comp-components/rds-comp-components.tsx
  raaghu-components/src/rds-comp-elements/rds-comp-elements.tsx
  raaghu-components/src/rds-comp-top-navigation/components-list.ts
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/libs/main-menu/elements.ts
  raaghu-mfe/rds_pages/host/.env
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-components/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-components/src/components/components.tsx
  raaghu-mfe/rds_pages/rds-page-elements/src/App.tsx
Labels: enhancement

#1496 committed for tenant breadcrumb issue
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1504 active class
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
Labels: bug

#1509 raaghu-react-core version is incremented
  package.json
  raaghu-mfe/package.json
Labels: bug

#1506 Development abp
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-security-logs/rds-comp-security-logs.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
Labels: bug, enhancement

#1510 Removed inline CSS form Datatable comp, avatar and illustration elements.
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-mfe/libs/proxy/core/OpenAPI.ts
Labels: enhancement

#1512 Development abp
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug

#1514 login and polls and breadcrum issue solved
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-mfe/libs/state-management/security-logs/security-logs-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
Labels: bug

#1515 changes in the UI
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
Labels: bug

#1516 committed for issue #1448
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
Labels: bug

#1532 dark theme related changes and icon animation chnaged for icons
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/rds-table/rds-table.tsx
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug

#1534 Created test files outside the src directory and added required configuration for the same. Also added test files for alert, address-detail and Checkbox element. Rectified the error of chatbox in chat module.
  package.json
  raaghu-elements/__mocks__/styleMock.ts
  raaghu-elements/__tests__/rds-address-detail.test.tsx
  raaghu-elements/__tests__/rds-alert.test.tsx
  raaghu-elements/__tests__/rds-button.test.tsx
  raaghu-elements/__tests__/rds-checkbox.test.tsx
  raaghu-elements/__tests__/rds-icon.test.tsx
  raaghu-elements/__tests__/rds-input.test.tsx
  raaghu-elements/babel.config.js
  raaghu-elements/jest.config.js
  raaghu-elements/jest.config.ts
  raaghu-elements/package.json
  raaghu-elements/src/rds-address-detail/rds-address-detail.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-button/rds-button.test.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
Labels: bug, enhancement

#1543 PR for remove decimal and add hand cursor on sidenav toggle
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
Labels: bug

#1549 Development abp
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-change-user-password/index.ts
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.stories.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-changepassword/package.json
  raaghu-mfe/rds_pages/rds-page-changepassword/public/assets/Login-card.svg
  raaghu-mfe/rds_pages/rds-page-changepassword/public/assets/body-backgroud.svg
  raaghu-mfe/rds_pages/rds-page-changepassword/public/index.html
  raaghu-mfe/rds_pages/rds-page-changepassword/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-changepassword/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-changepassword/src/changepassword/changepassword.scss
  raaghu-mfe/rds_pages/rds-page-changepassword/src/changepassword/changepassword.stories.tsx
  raaghu-mfe/rds_pages/rds-page-changepassword/src/changepassword/changepassword.tsx
  raaghu-mfe/rds_pages/rds-page-changepassword/src/index.ts
  raaghu-mfe/rds_pages/rds-page-changepassword/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-changepassword/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: bug

#1552 Icon list page UI updated and update some classes in pages
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-security-logs/rds-comp-security-logs.tsx
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.scss
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
Labels: enhancement

#1557 Added multi-level dropdown in top navigation
  raaghu-components/src/rds-comp-charts/charts/boolean.tsx
  raaghu-components/src/rds-comp-charts/code_snippet.ts
  raaghu-components/src/rds-comp-top-navigation/charts-list.ts
  raaghu-components/src/rds-comp-top-navigation/multi-level-dropdown.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
Labels: enhancement
