Repository Wai-Technologies/raaghu-react, pull requests merged in 2023-03, with the labels that each got.

#866 language page and language text page
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/language-text/language-text-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
Labels: enhancement

#870 Changed Data table Event emitter data. made required changes in all …
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.tsx
Labels: bug

#871 Pagination element enhancement and security logs page issue
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.scss
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/webpack.config.js
Labels: enhancement

#872 UI of language and language text
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#874 settings page ui
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/libs/state-management/settings/settings-slice.ts
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
Labels: enhancement

#880 new claims component and code refactoring in Tenant Page
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-account/index.ts
  raaghu-components/src/rds-comp-application-basic/index.ts
  raaghu-components/src/rds-comp-claims/index.ts
  raaghu-components/src/rds-comp-claims/rds-comp-claims.scss
  raaghu-components/src/rds-comp-claims/rds-comp-claims.stories.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-feature-management/index.ts
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-security-logs/index.ts
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-informations.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug

#894 Storybook build issue
  .github/workflows/development_storybookreact.yml
Labels: bug

#896 Ci-Cd pipeline storybook
  .github/workflows/development_storybookreact.yml
Labels: bug

#897 Update development_storybookreact.yml
  .github/workflows/development_storybookreact.yml
Labels: bug

#898 Build issue storybook
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: bug

#901 Build issue storybook
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
Labels: bug

#895 Added Edition page, Features component and suggested UI changes.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/state-management/edition/edition-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: enhancement

#908 useLocation() issue is resolved
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-mfe/rds_pages/rds-page-login/tsconfig.json
Labels: bug

#909 Development abp
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-mfe/libs/state-management/applications/applications-slice.ts
  raaghu-mfe/libs/state-management/claim-types/claim-types-slice.ts
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/webpack.config.js
Labels: enhancement

#911 create file management page
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/package.json
  raaghu-mfe/rds_pages/rds-page-fileManagement/public/index.html
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/index.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-fileManagement/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
Labels: enhancement

#917 localization from api fetched data
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/localization/localization-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/MyComponent.tsx
  raaghu-mfe/rds_pages/host/src/i18n.js
Labels: enhancement

#918 committed for user roles component
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.stories.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#919 Create a home page of Chat module
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-chats/package.json
  raaghu-mfe/rds_pages/rds-page-chats/public/index.html
  raaghu-mfe/rds_pages/rds-page-chats/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/index.ts
  raaghu-mfe/rds_pages/rds-page-chats/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-chats/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: enhancement

#921 Debugger removed.
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-informations.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
  raaghu-mfe/libs/state-management/claim-types/claim-types-slice.ts
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/host/src/MyComponent.tsx
  raaghu-mfe/rds_pages/host/tsconfig.json
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#922 created a directory list component
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.scss
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.stories.tsx
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#923 created localization service
  raaghu-mfe/libs/shared/UserAuth.ts
  raaghu-mfe/libs/shared/i18n.ts
  raaghu-mfe/libs/shared/public.api.ts
  raaghu-mfe/libs/shared/service-proxies.ts
  raaghu-mfe/libs/state-management/forgot-password/forgotpassword-slice.ts
  raaghu-mfe/libs/state-management/language-text/language-text-slice.ts
  raaghu-mfe/libs/state-management/login/login-slice.ts
  raaghu-mfe/rds_pages/host/src/MyComponent.tsx
  raaghu-mfe/rds_pages/host/src/bootstrap.tsx
  raaghu-mfe/rds_pages/host/src/i18n.js
  raaghu-mfe/rds_pages/host/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-dashboard/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/bootstrap.tsx
Labels: enhancement

#926 committed-permission-tree
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: enhancement

#927 committed for user role component functionality
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-roles/index.ts
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.module.scss
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#928 Added users list commponent in chats module page.
  raaghu-components/src/index.ts
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
Labels: enhancement

#929 Development abp
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug, enhancement

#933 build issue storybook
  .storybook/preview.js
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.stories.tsx
  raaghu-mfe/rds_pages/rds-page-roles/package.json
  raaghu-mfe/rds_pages/rds-page-texttemplate/package.json
Labels: bug

#934 storybook build
  raaghu-components/src/rds-comp-account/rds-comp-account.stories.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.stories.tsx
  raaghu-mfe/package.json
Labels: bug

#935 added data table and search filter in file management page
  raaghu-components/src/rds-comp-directory-list/index.ts
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#936 Development abp
  raaghu-mfe/libs/shared/UserAuth.ts
  raaghu-mfe/libs/shared/i18n.ts
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
  raaghu-mfe/rds_pages/rds-page-dashboard/src/Dashboard/Dashboard.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/forgotpassword/forgotpassword.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#938 localizatio via dropdown
  raaghu-mfe/libs/state-management/localization/localization-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/MyComponent.tsx
  raaghu-mfe/rds_pages/rds-page-dashboard/src/Dashboard/Dashboard.tsx
Labels: enhancement

#960 Development abp
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-forms-basic/index.ts
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.stories.tsx
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
  raaghu-components/src/rds-comp-forms-question/index.ts
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-question.stories.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-question.tsx
  raaghu-components/src/rds-comp-forms-setting/index.ts
  raaghu-components/src/rds-comp-forms-setting/rds-comp-forms-setting.stories.tsx
  raaghu-components/src/rds-comp-forms-setting/rds-comp-forms-setting.tsx
  raaghu-components/src/rds-comp-questions/index.ts
  raaghu-components/src/rds-comp-questions/rds-comp-questions.stories.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-forms/package.json
  raaghu-mfe/rds_pages/rds-page-forms/public/index.html
  raaghu-mfe/rds_pages/rds-page-forms/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/index.ts
  raaghu-mfe/rds_pages/rds-page-forms/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-forms/webpack.config.js
Labels: enhancement

#962 committed for user page organization unit functionality
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#966 Update the APIs in service-proxy.ts file
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-question.tsx
  raaghu-components/src/rds-comp-forms-setting/rds-comp-forms-setting.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-mfe/libs/shared/UserAuth.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/shared/service-proxies.ts
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/libs/state-management/blogger/blogger-slice.ts
  raaghu-mfe/libs/state-management/settings/settings-slice.ts
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/nswag/service.config.nswag
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/package.json
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#967 committed-feature-component
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-informations.tsx
  raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/webpack.config.js
Labels: enhancement

#970 Added chat screen to the chats module.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-mfe/libs/state-management/chats/chats-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-chats/src/chats/chats.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/App.tsx
Labels: enhancement

#977 committed-blog-module-functionality
  raaghu-mfe/libs/state-management/blogger/blogger-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
Labels: enhancement

#979 databinding for api scopes page
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/scope/scope-slice.ts
  raaghu-mfe/libs/state-management/scope/scope.models.ts
  raaghu-mfe/rds_pages/rds-page-scope/src/Scope/Scope.tsx
Labels: enhancement

#980 Client page creation , element and component addition
  raaghu-components/src/index.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-client/package.json
  raaghu-mfe/rds_pages/rds-page-client/public/index.html
  raaghu-mfe/rds_pages/rds-page-client/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-client/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-client/src/client/client.tsx
  raaghu-mfe/rds_pages/rds-page-client/src/index.ts
  raaghu-mfe/rds_pages/rds-page-client/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-client/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: bug

#983 Build issue is resolved
  raaghu-elements/src/rds-navtabs/rds-navtabs.scss
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
Labels: bug

#982 committed for properties component
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-properties-new/index.ts
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.module.scss
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.stories.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.test.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
  raaghu-mfe/rds_pages/rds-page-identity-resources/src/IdentityResources/IdentityResources.tsx
  raaghu-mfe/rds_pages/rds-page-identity-resources/src/bootstrap.tsx
Labels: enhancement

#984 Development abp
  package.json
  page-template/package.json
  page-template/template.json
  page-template/template/gitignore
  page-template/template/package.json
  page-template/template/public/index.html
  page-template/template/src/App.tsx
  page-template/template/src/bootstrap.tsx
  page-template/template/src/index.ts
  page-template/template/tsconfig.json
  page-template/template/webpack.config.js
  utils/create.js
Labels: enhancement

#987 created state management for file management module
  raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#998 Date Range issue resolved.
  raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.stories.tsx
  raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.test.tsx
  raaghu-mfe/libs/shared/UserAuth.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#999 Development abp
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-question.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-mfe/rds_pages/mfe-config.ts
Labels: enhancement

#1027 binded folder structure with apis in file management
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#1029 Storybook build issues are resolved
  .npmrc
  package.json
  raaghu-components/package.json
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.stories.tsx
  tsconfig.json
Labels: bug

#1032 create new comp of identity server basic.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-identity-client-basic/index.ts
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client.stories.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-client/src/client/client.tsx
  raaghu-mfe/rds_pages/rds-page-client/webpack.config.js
Labels: enhancement

#1036 dropdown working on all pages
  raaghu-mfe/rds_pages/host/public/index.html
Labels: bug

#1037 committed for bugs #1002 #1004 #1006 #1023 #1024
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.tsx
  raaghu-mfe/libs/state-management/identity-resources/identity-resoucesModels.ts
  raaghu-mfe/libs/state-management/identity-resources/identity-resources-slice.ts
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1039 create a file uploader component
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-fileUploader/index.ts
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.scss
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.stories.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.test.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-mfe/rds_pages/host/src/assets/File-upload.png
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#1040 Client page component
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-mfe/rds_pages/rds-page-client/src/client/client.tsx
Labels: enhancement

#1043 committed changes for tenant save button, security-log filter alignment
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
Labels: bug

#1044 Restructure left navigation menu
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#1045 Development abp
  .vs/slnx.sqlite
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-api-resource-basic/index.ts
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.stories.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-apiResources/package.json
  raaghu-mfe/rds_pages/rds-page-apiResources/public/index.html
  raaghu-mfe/rds_pages/rds-page-apiResources/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-apiResources/src/apiResources/apiResources.tsx
  raaghu-mfe/rds_pages/rds-page-apiResources/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-apiResources/src/index.ts
  raaghu-mfe/rds_pages/rds-page-apiResources/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-apiResources/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#1046 roles page functionality completed
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: enhancement

#1047 Created separate directory for storing side nav items data, and wrote node script to automatically create routes and items data after running the cli command to create page.
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  utils/create.js
Labels: enhancement

#1048 committed for resolved bugs
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1059 Update the service-proxy.ts with all the ABP Commercial modules
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/libs/state-management/chats/chats-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/scope/scope-slice.ts
  raaghu-mfe/libs/state-management/settings/settings-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/nswag/service.config.nswag
  raaghu-mfe/rds_pages/rds-page-scope/src/Scope/Scope.tsx
Labels: bug

#1060 creation page Url forwarding
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/main-menu/url-forwarding.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-polls/package.json
  raaghu-mfe/rds_pages/rds-page-polls/public/index.html
  raaghu-mfe/rds_pages/rds-page-polls/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.stories.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/index.ts
  raaghu-mfe/rds_pages/rds-page-polls/src/remote.d.ts
  raaghu-mfe/rds_pages/rds-page-polls/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-polls/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-urlforwarding/.gitignore
  raaghu-mfe/rds_pages/rds-page-urlforwarding/package.json
  raaghu-mfe/rds_pages/rds-page-urlforwarding/public/index.html
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/index.ts
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-urlforwarding/webpack.config.js
Labels: enhancement

#1070 Development abp
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-blogs/package.json
  raaghu-mfe/rds_pages/rds-page-blogs/public/index.html
  raaghu-mfe/rds_pages/rds-page-blogs/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/index.ts
  raaghu-mfe/rds_pages/rds-page-blogs/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-blogs/webpack.config.js
Labels: enhancement

#1071 committed-payments-page
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/payment-plans/paymentPlans-slice.ts
  raaghu-mfe/libs/state-management/payment-plans/paymentPlans.models.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-paymentPlans/package.json
  raaghu-mfe/rds_pages/rds-page-paymentPlans/public/index.html
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/index.ts
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-paymentPlans/webpack.config.js
Labels: enhancement

#1074 Development abp
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
  raaghu-components/src/rds-comp-forms-question/index.ts
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-question.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/libs/state-management/forms/forms.models.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
Labels: enhancement

#1077 url forwarding page state management and databinding
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-url-forwardings/index.ts
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/scope/scope-slice.ts
  raaghu-mfe/libs/state-management/scope/scope.models.ts
  raaghu-mfe/libs/state-management/url-forwarding/url-forwarding-slice.ts
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
Labels: enhancement

#1079 committed for polls page question component
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-polls-option/index.ts
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.module.scss
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.stories.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.test.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-polls-question/index.ts
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.module.scss
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.stories.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.test.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-mfe/libs/shared/UserAuth.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/state-management/identity-resources/identity-resources-slice.ts
  raaghu-mfe/rds_pages/host/public/index.html
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
Labels: enhancement

#1082 Update service-proxy.ts
  raaghu-mfe/libs/shared/UserAuth.ts
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-scope/src/App.tsx
Labels: enhancement

#1096 Resolved build issues
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
Labels: bug

#1098 Version incremented for raaghu-themes
  package.json
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.stories.tsx
  raaghu-mfe/package.json
Labels: bug

#1102 Update rds-comp-polls-option.stories.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.stories.tsx
Labels: bug

#1089 Development abp
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-mfe/libs/state-management/Blogs/blogs-slice.ts
  raaghu-mfe/libs/state-management/Blogs/blogs.models.ts
  raaghu-mfe/rds_pages/rds-page-apiResources/src/apiResources/apiResources.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-client/src/client/client.tsx
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-identityResources/src/IdentityResources/IdentityResources.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-scope/src/Scope/Scope.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.tsx
Labels: bug

#1099 dropdown issue and datatable entry last value first
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/libs/state-management/apiScope/apiScope-slice.ts
  raaghu-mfe/libs/state-management/applications/applications-slice.ts
  raaghu-mfe/libs/state-management/claim-types/claim-types-slice.ts
  raaghu-mfe/libs/state-management/edition/edition-slice.ts
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/libs/state-management/language-text/language-text-slice.ts
  raaghu-mfe/libs/state-management/language/language-slice.ts
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
  raaghu-mfe/libs/state-management/url-forwarding/url-forwarding-slice.ts
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/host/public/index.html
Labels: bug

#1100 committed changes for admin offcanvas UI
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: enhancement

#1101 adding functionality in directory list component
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-mfe/libs/state-management/file-management/file-management-slice.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#1107 raaghu-react-elments version is change
  raaghu-components/package.json
  raaghu-elements/package.json
  raaghu-mfe/package.json
Labels: enhancement

#1111 Forgot page Ui and functionality
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/assets/Raaghu-logo-mfe-white.svg
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/forgotpassword/forgotpassword.scss
  raaghu-mfe/rds_pages/rds-page-forgotpassword/src/forgotpassword/forgotpassword.tsx
Labels: enhancement

#1112 Development abp
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-question.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-forms-setting/rds-comp-forms-setting.tsx
  raaghu-components/src/rds-comp-questions/rds-comp-questions.tsx
  raaghu-mfe/libs/shared/UserAuth.ts
  raaghu-mfe/libs/state-management/forms/forms-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-forms-preview/package.json
  raaghu-mfe/rds_pages/rds-page-forms-preview/public/index.html
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/FormsPreview/FormsPreview.tsx
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-forms-preview/src/index.ts
  raaghu-mfe/rds_pages/rds-page-forms-preview/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-forms-preview/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-forms-view/package.json
  raaghu-mfe/rds_pages/rds-page-forms-view/public/index.html
  raaghu-mfe/rds_pages/rds-page-forms-view/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/index.ts
  raaghu-mfe/rds_pages/rds-page-forms-view/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-forms-view/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
Labels: bug

#1113 committed for state management of polls page
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-mfe/libs/state-management/polls/polls-slice.ts
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
Labels: enhancement

#1115 solved roles users edition page bugs
  raaghu-mfe/libs/state-management/user/user-slice.ts
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1116 Development abp
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: enhancement

#1134 data binding for Rename and Delete funstionality
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
Labels: bug

#1135 bugs in user and login navigation issue solved
  raaghu-mfe/libs/state-management/host/host-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1136 Themes and Elements versions are changed.
  package.json
  raaghu-elements/package.json
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-roles/package.json
  raaghu-mfe/rds_pages/rds-page-texttemplate/package.json
Labels: bug

#1139 Create elements page in react.
  raaghu-components/generate-react-cli.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-elements/index.ts
  raaghu-components/src/rds-comp-elements/rds-comp-elements.stories.tsx
  raaghu-components/src/rds-comp-elements/rds-comp-elements.styled.ts
  raaghu-components/src/rds-comp-elements/rds-comp-elements.test.tsx
  raaghu-components/src/rds-comp-elements/rds-comp-elements.tsx
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.tsx
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/libs/main-menu/elements.ts
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/assets/chevron-right-double.svg
  raaghu-mfe/rds_pages/host/src/assets/raaghu_logs.png
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-elements/.gitignore
  raaghu-mfe/rds_pages/rds-page-elements/package.json
  raaghu-mfe/rds_pages/rds-page-elements/public/index.html
  raaghu-mfe/rds_pages/rds-page-elements/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-elements/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-elements/src/elements/elements.tsx
  raaghu-mfe/rds_pages/rds-page-elements/src/index.ts
  raaghu-mfe/rds_pages/rds-page-elements/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-elements/webpack.config.js
Labels: bug, enhancement

#1140 Personal data page UI
  .vs/slnx.sqlite
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/personal-data.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-personaldata/.gitignore
  raaghu-mfe/rds_pages/rds-page-personaldata/package.json
  raaghu-mfe/rds_pages/rds-page-personaldata/public/index.html
  raaghu-mfe/rds_pages/rds-page-personaldata/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-personaldata/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-personaldata/src/index.ts
  raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx
  raaghu-mfe/rds_pages/rds-page-personaldata/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-personaldata/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
Labels: enhancement

#1141 committed changes for my-account UI component
  .vs/slnx.sqlite
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-change-password/index.ts
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.stories.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.styled.ts
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.test.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-personal-info/index.ts
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.stories.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.styled.ts
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.test.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-picture/index.ts
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.stories.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.styled.ts
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.test.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/libs/main-menu/my-account.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-myaccount/.gitignore
  raaghu-mfe/rds_pages/rds-page-myaccount/package.json
  raaghu-mfe/rds_pages/rds-page-myaccount/public/index.html
  raaghu-mfe/rds_pages/rds-page-myaccount/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-myaccount/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-myaccount/src/index.ts
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
  raaghu-mfe/rds_pages/rds-page-myaccount/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-myaccount/webpack.config.js
Labels: enhancement

#1148 action in the data table issue solved
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1152 committed-payment-request-page-for-functionality
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/payment-requests/paymentRequests-slice.ts
  raaghu-mfe/libs/state-management/payment-requests/paymentRequests.models.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/package.json
  raaghu-mfe/rds_pages/rds-page-paymentRequests/public/index.html
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/index.ts
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-paymentRequests/webpack.config.js
Labels: enhancement

#1155 committed for my account > personal-info and change password state management and binding
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/my-account/my-account-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
Labels: enhancement

#1160 Updated the script for the service proxy file creation and routing issue.
  package.json
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  utils/create.js
Labels: enhancement

#1157 committed for data-table changes and polls option component
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/polls/polls-slice.ts
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
Labels: enhancement

#1158 Functionality for Personal data page.
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/main-menu/rds-components.ts
  raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx
  raaghu-mfe/rds_pages/rds-page-rdscomponents/.gitignore
  raaghu-mfe/rds_pages/rds-page-rdscomponents/package.json
  raaghu-mfe/rds_pages/rds-page-rdscomponents/public/index.html
  raaghu-mfe/rds_pages/rds-page-rdscomponents/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-rdscomponents/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-rdscomponents/src/index.ts
  raaghu-mfe/rds_pages/rds-page-rdscomponents/src/rds-components/rds-components.tsx
  raaghu-mfe/rds_pages/rds-page-rdscomponents/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-rdscomponents/webpack.config.js
Labels: bug

#1161 issues solved offcanas backdrop and page opening issues
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-role-list/index.ts
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.scss
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.stories.tsx
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1162 Change import statement with export statement
  raaghu-elements/generate-react-cli.json
  raaghu-mfe/package.json
  utils/create.js
Labels: bug
