Repository Wai-Technologies/raaghu-react, pull requests merged in 2023-05, with the labels that each got.

#1560 PR for #1529
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
Labels: bug, enhancement

#1578 Create rds-card.test.tsx
  raaghu-elements/__tests__/rds-card.test.tsx
Labels: enhancement

#1582 Added configuration for jest testing in raaghu-components and raaghu-mfe, Also written tests for rds-comp-background-image, rds-comp-edition, rds-address-detail, rds-app-detail,rds-avatar, rds-badge and made some required changes in the respective components.
  raaghu-components/__mocks__/styleMock.ts
  raaghu-components/__tests__/rds-comp-background-image.test.tsx
  raaghu-components/__tests__/rds-comp-edition.test.tsx
  raaghu-components/babel.config.js
  raaghu-components/jest.config.js
  raaghu-components/jest.config.ts
  raaghu-components/package.json
  raaghu-components/src/rds-comp-background-image/rds-comp-background-image.tsx
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-elements/__tests__/rds-address-detail.test.tsx
  raaghu-elements/__tests__/rds-app-detail.test.tsx
  raaghu-elements/__tests__/rds-avatar.test.tsx
  raaghu-elements/__tests__/rds-badge.test.tsx
  raaghu-elements/package.json
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
  raaghu-elements/tsconfig.json
  raaghu-mfe/__mocks__/styleMock.ts
  raaghu-mfe/babel.config.js
  raaghu-mfe/package.json
Labels: enhancement

#1585 Development abp
  package.json
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/openid.config.ts
Labels: bug

#1589 raaghu-themes version is incremented.
  package.json
  raaghu-mfe/package.json
Labels: enhancement

#1586 Development abp
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-mfe/rds_pages/host/public/index.html
Labels: enhancement

#1604 Created test file for rds-banner
  raaghu-elements/__tests__/rds-banner.test.tsx
Labels: enhancement

#1606 Created test file for rds-benefit element.
  raaghu-elements/__tests__/rds-benefit.test.tsx
Labels: enhancement

#1609 Created test file for rds-bignumber element.
  raaghu-elements/__tests__/rds-big-number.test.tsx
Labels: enhancement

#1611 created test file for rds-button-group element.
  raaghu-elements/__tests__/rds-button-group.test.tsx
Labels: enhancement

#1616 created test file for rds-carousel element.
  raaghu-elements/__tests__/rds-carousel.test.tsx
Labels: enhancement

#1621 Create rds-icon-label.test.tsx
  raaghu-elements/__tests__/rds-icon-label.test.tsx
Labels: enhancement

#1624 Created test file for Accordion
  raaghu-elements/__tests__/rds-accordion.test.tsx
Labels: enhancement

#1634 Written tests for checkbox group and checkbox parent child.
  raaghu-elements/__tests__/rds-checkbox-group.test.tsx
  raaghu-elements/__tests__/rds-checkbox-parent-child.test.tsx
  raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.tsx
Labels: enhancement

#1638 Written tests for collapse and color-picker element.
  raaghu-elements/__tests__/rds-collapse.test.tsx
  raaghu-elements/__tests__/rds-color-picker.test.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.tsx
Labels: enhancement

#1645 Created test file for color-picker and color-switcher
  raaghu-elements/__tests__/rds-color-switcher.test.tsx
  raaghu-elements/src/rds-color-switcher/rds-color-switcher.tsx
Labels: enhancement

#1646 Written test file for counter.
  raaghu-elements/__tests__/rds-counter.test.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: enhancement

#1658 Created test file for modal.
  raaghu-elements/__tests__/rds-modal.test.tsx
Labels: enhancement

#1659 Development abp
  package.json
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/App.scss
Labels: bug

#1665 Created test for dropdown, fab Menu, feature list.
  raaghu-elements/__tests__/rds-dropdown.test.tsx
  raaghu-elements/__tests__/rds-fab-menu.test.tsx
  raaghu-elements/__tests__/rds-feature-list.test.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
  raaghu-elements/src/rds-feature-list/rds-feature-list.tsx
Labels: enhancement

#1667 Added test file for popular page.
  raaghu-elements/__tests__/rds-popular-page.test.tsx
  raaghu-elements/__tests__/rds-price.test.tsx
  raaghu-elements/__tests__/rds-product-image.test.tsx
  raaghu-elements/src/rds-popular-page/rds-popular-page.tsx
  raaghu-elements/src/rds-price/rds-price.tsx
  raaghu-elements/src/rds-product-image/rds-product-image.tsx
Labels: enhancement

#1668 Created test script for navtabs elements
  raaghu-elements/__tests__/rds-navtabs.test.tsx
  raaghu-elements/__tests__/rds-notification.test.tsx
Labels: enhancement

#1673 Added test for progress bar element.
  raaghu-elements/__tests__/rds-progress-bar.test.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
Labels: enhancement

#1681 Added test file for Search and select list.
  raaghu-elements/__tests__/rds-search.test.tsx
  raaghu-elements/__tests__/rds-select-list.test.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: enhancement

#1680 committed for offcanvas title canvas issue and change password input
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
Labels: bug

#1679 Created test script for rds-radio button
  raaghu-elements/__tests__/rds-radio-button.test.tsx
Labels: enhancement

#1683 Created test script for rds-range
  raaghu-elements/__tests__/rds-range.test.tsx
Labels: enhancement

#1684 Added test files for spinner and tooltip
  raaghu-elements/__tests__/rds-size.test.tsx
  raaghu-elements/__tests__/rds-spinner.test.tsx
  raaghu-elements/__tests__/rds-stat.test.tsx
  raaghu-elements/__tests__/rds-tooltip.test.tsx
  raaghu-elements/src/rds-size/rds-size.tsx
  raaghu-elements/src/rds-stat/rds-stat.tsx
Labels: enhancement

#1685 Created test script for rds-rating
  raaghu-elements/__tests__/rds-rating.test.tsx
Labels: enhancement

#1688 PR for bug #1655, #1628
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
Labels: bug

#1686 Created test script for rds-stepper element
  raaghu-elements/__tests__/rds-stepper.test.tsx
  raaghu-elements/__tests__/rds-text-area.test.tsx
  raaghu-elements/__tests__/rds-text-editor.test.tsx
  raaghu-elements/__tests__/rds-toast.test.tsx
Labels: enhancement

#1699 committed for logo issue in dark and semidark theme
  .vs/slnx.sqlite
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/assets/Raaghu-logo-mfe-white (3).svg
  raaghu-mfe/rds_pages/host/src/assets/raaghu-logo-white-text.png
Labels: bug

#1700 Created test script for rds-toggle element
  raaghu-elements/__tests__/rds-toggle.test.tsx
Labels: enhancement

#1701 Created test script of rds-chart-area element
  raaghu-elements/__tests__/rds-chart-area.test.tsx
  raaghu-elements/__tests__/rds-dropdown-list.test.tsx
Labels: enhancement

#1705 PR for #1503, #1644, #1691, #1689 & #1690
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: bug, enhancement

#1721 Created Test script for rds-double-range and side-nave element
  raaghu-elements/__tests__/rds-double-range.test.tsx
  raaghu-elements/__tests__/rds-side-nav.test.tsx
Labels: enhancement

#1727 PR for bug #1693 & #1714
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
Labels: bug

#1749 fixed bugs #1373 #1736 #1730 #1733 #1731
  raaghu-mfe/libs/state-management/organization-tree/organization-tree-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#1750 request personal data issue
  raaghu-mfe/libs/state-management/personal-data/personal-data-slice.ts
  raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx
Labels: bug

#1754 PR for #1517
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-register/index.ts
  raaghu-components/src/rds-comp-register/rds-comp-register.stories.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.styled.ts
  raaghu-components/src/rds-comp-register/rds-comp-register.test.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-mfe/libs/main-menu/index.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/register/register-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/PageComponent.ts
  raaghu-mfe/rds_pages/host/src/openid.config.ts
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-register/.gitignore
  raaghu-mfe/rds_pages/rds-page-register/package.json
  raaghu-mfe/rds_pages/rds-page-register/public/index.html
  raaghu-mfe/rds_pages/rds-page-register/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-register/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-register/src/index.ts
  raaghu-mfe/rds_pages/rds-page-register/src/register/register.tsx
  raaghu-mfe/rds_pages/rds-page-register/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-register/webpack.config.js
Labels: bug, enhancement

#1760 Rectified the error of raaghu-component testing and added tests for background-image, email, edition and alert popup.
  raaghu-components/__tests__/rds-comp-alert-popup.test.tsx
  raaghu-components/__tests__/rds-comp-edition.test.tsx
  raaghu-components/__tests__/rds-comp-email.test.tsx
  raaghu-components/jest.config.ts
  raaghu-components/package.json
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.test.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.test.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.test.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.test.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.test.tsx
Labels: bug, enhancement

#1761 Created test script for App Details component
  raaghu-components/__tests__/rds-comp-app-detail.test.tsx
Labels: enhancement

#1767 Added test file for feeds component.
  raaghu-components/__tests__/rds-comp-feeds.test.tsx
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
Labels: enhancement

#1771 Created test script for apply for position component
  raaghu-components/__tests__/rds-comp-apply-for-position.test.tsx
Labels: enhancement

#1773 Pr for #1732
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.module.scss
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-elements/src/rds-input/rds-input.scss
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.scss
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.scss
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.scss
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-paymentRequests/src/paymentRequests/paymentRequests.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
Labels: enhancement

#1770 PR for #1656 & #1765
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/libs/state-management/register/register-slice.ts
Labels: bug, enhancement

#1783 Created test script for Billing Address component
  raaghu-components/__tests__/rds-comp-billing-address.test.tsx
Labels: enhancement

#1792 Package names are changed, remove the babel warnings
  raaghu-mfe/rds_pages/rds-page-blogpost/package.json
  raaghu-mfe/rds_pages/rds-page-chart/package.json
  raaghu-mfe/rds_pages/rds-page-chart/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-components/package.json
  raaghu-mfe/rds_pages/rds-page-components/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-newsletters/package.json
  raaghu-mfe/rds_pages/rds-page-newsletters/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-pages/package.json
  raaghu-mfe/rds_pages/rds-page-pages/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-polls/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-polls/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-register/package.json
  raaghu-mfe/rds_pages/rds-page-register/webpack.config.js
Labels: bug

#1791 Created test script for Card detail list component
  raaghu-components/__tests__/rds-comp-card-detail-list.test.tsx
Labels: enhancement

#1790 Written test for benefit, contact us, delivery method and download collation
  raaghu-components/__tests__/rds-comp-benefit.test.tsx
  raaghu-components/__tests__/rds-comp-contact-us.test.tsx
  raaghu-components/__tests__/rds-comp-delivery-method.test.tsx
  raaghu-components/__tests__/rds-comp-download-collation.test.tsx
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.tsx
  raaghu-components/src/rds-comp-download-collation/rds-comp-download-collation.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: enhancement

#1802 Created test script for Change user password component
  raaghu-components/__tests__/rds-comp-change-user-password.test.tsx
Labels: enhancement

#1807 PR for #1779
  .vs/slnx.sqlite
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
  raaghu-mfe/rds_pages/rds-page-globalResources/src/globalResources/globalResources.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-newsletters/src/newsletters/Newsletters.tsx
  raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
Labels: enhancement

#1809 Added test file for faq and subscription component.
  raaghu-components/__tests__/rds-comp-faq.test.tsx
  raaghu-components/__tests__/rds-comp-subscription.test.tsx
Labels: enhancement

#1813 Created test script for Calendar component
  raaghu-components/__tests__/rds-comp-calendar.test.tsx
Labels: enhancement

#1815 Created test script for cache and file-mover component
  raaghu-components/__tests__/rds-comp-cache.test.tsx
  raaghu-components/__tests__/rds-comp-file-mover.test.tsx
  raaghu-components/__tests__/rds-comp-fileUploader.test.tsx
Labels: enhancement

#1824 PR for #1782 & #1753
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-register/src/register/register.tsx
Labels: bug, enhancement

#1842 Created test script for new language, new role, password setting, payment detail and my setting component
  raaghu-components/__tests__/rds-comp-my-settings.test.tsx
  raaghu-components/__tests__/rds-comp-new-language.test.tsx
  raaghu-components/__tests__/rds-comp-new-role.test.tsx
  raaghu-components/__tests__/rds-comp-password-setting.test.tsx
  raaghu-components/__tests__/rds-comp-payment-detail.test.tsx
Labels: enhancement

#1841 PR for #1810, #1811
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.scss
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
Labels: enhancement

#1844 committed changes for dropdown to icons
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug, enhancement

#1845 Development abp
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
Labels: bug

#1868 Created test for new roles component
  raaghu-components/__tests__/rds-comp-new-role.test.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
Labels: enhancement

#1871 added test for password-setting component
  raaghu-components/__tests__/rds-comp-password-setting.test.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
Labels: enhancement

#1872 Added test for forms basic component.
  raaghu-components/__tests__/rds-comp-forms-basic.test.tsx
  raaghu-components/__tests__/rds-comp-my-settings.test.tsx
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
Labels: enhancement

#1877 Added tests for form email component.
  raaghu-components/__tests__/rds-comp-forms-email.test.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
Labels: enhancement

#1884 Added test file for forms response.
  raaghu-components/__tests__/rds-comp-forms-response.test.tsx
Labels: enhancement

#1886 Added test for forms setting.
  raaghu-components/__tests__/rds-comp-forms-setting.test.tsx
  raaghu-components/src/rds-comp-forms-setting/rds-comp-forms-setting.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
Labels: enhancement

#1888 added test file for new claim component
  raaghu-components/__tests__/rds-comp-new-claim-type.test.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
Labels: enhancement

#1902 Added test file for Personal Info component.
  raaghu-components/__tests__/rds-comp-personal-info.test.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: enhancement

#1905 Added test for polls option.
  raaghu-components/__tests__/rds-comp-polls-option.test.tsx
  raaghu-components/__tests__/rds-comp-polls-question.test.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
Labels: enhancement

#1908 Added test file for profile edit component
  raaghu-components/__tests__/rds-comp-profile-edit.test.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
Labels: enhancement

#1909 Added test files for profile picture and properties component.
  raaghu-components/__tests__/rds-comp-other-settings.test.tsx
  raaghu-components/__tests__/rds-comp-profile-picture.test.tsx
  raaghu-components/__tests__/rds-comp-properties.test.tsx
  raaghu-components/__tests__/rds-comp-tenant-settings.test.tsx
  raaghu-components/src/rds-comp-other-settings/rds-comp-other-settings.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: enhancement

#1912 PR for #1843
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#1913 fixed the backdrop issue and save button issue.
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-mfe/libs/state-management/blog-post/blog-post-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-urlforwarding/src/url-forwarding/url-forwarding.tsx
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/src/webhook/webhook.tsx
Labels: bug

#1932 Added test file for forgot-password, Icon list and register component.
  raaghu-components/__tests__/rds-comp-forgot-password.test.tsx
  raaghu-components/__tests__/rds-comp-icon-list.test.tsx
  raaghu-components/__tests__/rds-comp-register.test.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.test.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
Labels: enhancement

#1938 Code enhanced in RdsDatePicker and comp-poll-question.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: bug

#1940 PR for #1900, #1898, #1890 & #1527
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-list-group/rds-list-group.tsx
  raaghu-elements/src/rds-modal/rds-modal.css
  raaghu-elements/src/rds-navbar/rds-navbar.css
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.css
  raaghu-elements/src/rds-popular-page/rds-popular-page.css
  raaghu-elements/src/rds-popular-page/rds-popular-page.tsx
  raaghu-elements/src/rds-product-image/rds-product-image.tsx
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
  raaghu-elements/src/rds-table/rds-table.tsx
  raaghu-elements/src/rds-tag/rds-tag.css
  raaghu-elements/src/rds-tag/rds-tag.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.css
  raaghu-elements/src/rds-team-member/rds-team-member.stories.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.tsx
  raaghu-elements/src/rds-testimonial/rds-testimonial.css
  raaghu-elements/src/rds-text-editor/rds-text-editor.css
  raaghu-elements/src/rds-tooltip/rds-tooltip.stories.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: bug

#1941 Development abp- #1874, #1875, #1880, #1879, #1885 #1919, #1927, #1885, #1915
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
  raaghu-mfe/rds_pages/rds-page-comments/src/comments/comments.tsx
Labels: bug

#1942 Fixed UI bugs for #1916, #1920, #1921, #1923
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-syntax-highlighter/rds-comp-syntax-highlighter.tsx
  raaghu-elements/src/assets/Icons.js
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
  raaghu-mfe/rds_pages/rds-page-globalResources/src/globalResources/globalResources.tsx
  raaghu-mfe/rds_pages/rds-page-myaccount/src/my-account/my-account.tsx
Labels: bug

#1943 Added test file for identity management and edit-language component.
  raaghu-components/__tests__/rds-comp-edit-language-text.test.tsx
  raaghu-components/__tests__/rds-comp-identity-management-new.test.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
Labels: bug

#1944 Added test file for identity-resource-basic, Creatd mock file for bootstrap backdrop issue, and corrected the name of resource from resourcse.
  raaghu-components/__mocks__/bootstrap.ts
  raaghu-components/__tests__/rds-comp-identity-resource-basic.test.tsx
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-components/code_snippet.ts
  raaghu-components/src/rds-comp-components/components/identityResourcesBasic.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/index.ts
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.stories.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-identiy-resourcse-basic/index.ts
  raaghu-components/src/rds-comp-identiy-resourcse-basic/rds-comp-identiy-resourcse-basic.test.tsx
  raaghu-mfe/rds_pages/rds-page-identityResources/src/IdentityResources/IdentityResources.tsx
Labels: bug

#1945 Added tests file for information and linked account component.
  raaghu-components/__tests__/rds-comp-information.test.tsx
  raaghu-components/__tests__/rds-comp-linked-account.test.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
Labels: enhancement

#1946 PR for button spinner
  .vs/VSWorkspaceState.json
  .vs/saniya-react/FileContentIndex/163d00f0-4ecf-49a4-8e51-4faac700b698.vsidx
  .vs/saniya-react/FileContentIndex/539e62d6-0c42-4596-9bda-097fa10eb8e7.vsidx
  .vs/saniya-react/FileContentIndex/5b0e6713-947e-4b65-b8dd-7f0f0dce85fb.vsidx
  .vs/saniya-react/FileContentIndex/7d6b2209-e793-4b9b-86e7-7f424e9fc9eb.vsidx
  .vs/saniya-react/FileContentIndex/read.lock
  .vs/saniya-react/v17/.suo
  .vs/slnx.sqlite
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: bug

#1947 Added test file for newPage and notificatin settings component.
  raaghu-components/__tests__/rds-comp-newPage.test.tsx
  raaghu-components/__tests__/rds-comp-notification-settings.test.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
Labels: enhancement

#1952 Added test files for profile and user roles component.
  raaghu-components/__tests__/rds-comp-profile.test.tsx
  raaghu-components/__tests__/rds-comp-user-roles.test.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
Labels: enhancement

#1953 PR for #1527
  raaghu-components/src/rds-comp-calendar/rds-comp-calendar.tsx
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-cookies-section/rds-comp-cookies-section.css
  raaghu-components/src/rds-comp-cookies-section/rds-comp-cookies-section.tsx
  raaghu-components/src/rds-comp-email-settings-new/rds-comp-email-settings-new.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-child/checkbox.module.css
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.css
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-informations.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
Labels: bug

#1954 PR for #1924, #1928, #1933
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/assets/Icons.js
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-mfe/rds_pages/rds-page-menus/src/menus/menus.tsx
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
Labels: bug

#1956 Development abp- #1876, #1925, #1914, #1870, #1856,#1883, #1922, #1935, #1852
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-mfe/rds_pages/rds-page-blogpost/src/blog-post/blog-post.tsx
Labels: bug

#1957 Added tests for url-forwarding and user-management component.
  raaghu-components/__tests__/rds-comp-organization-tree.test.tsx
  raaghu-components/__tests__/rds-comp-url-forwardings.test.tsx
  raaghu-components/__tests__/rds-comp-user-management.test.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
  raaghu-components/src/rds-comp-user-management/rds-comp-user-management.tsx
Labels: enhancement

#1955 Added Alert functionality in Polls page.
  raaghu-mfe/rds_pages/rds-page-polls/src/Polls/Polls.tsx
Labels: bug

#1961 Added test for testimonials and theme new component.
  raaghu-components/__tests__/rds-comp-testimonials.test.tsx
  raaghu-components/__tests__/rds-comp-theme-new.test.tsx
  raaghu-components/src/rds-comp-testimonials/rds-comp-testimonials.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-elements/__tests__/rds-select-list.test.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: enhancement

#1964 committed for sidebar menu_ issue
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#1989 UI Fixes and CHanges in tenant file for core
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-mfe/libs/main-menu/main-menu.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug

#1992 Fixed the language refresh bug
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#1995 Development abp- #1968, #1967
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-charts/charts/doughnut.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.tsx
  raaghu-mfe/rds_pages/rds-page-apiResources/src/apiResources/apiResources.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-blogger/src/blogger/blogger.tsx
  raaghu-mfe/rds_pages/rds-page-blogs/src/blogs/blogs.tsx
  raaghu-mfe/rds_pages/rds-page-client/src/client/client.tsx
  raaghu-mfe/rds_pages/rds-page-fileManagement/src/fileManagement/fileManagement.tsx
  raaghu-mfe/rds_pages/rds-page-forms-view/src/FormsView/FormsView.tsx
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
  raaghu-mfe/rds_pages/rds-page-maintainance/src/Maintainance/Maintainance.tsx
  raaghu-mfe/rds_pages/rds-page-newsletters/src/newsletters/Newsletters.tsx
  raaghu-mfe/rds_pages/rds-page-paymentPlans/src/paymentPlans/paymentPlans.tsx
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
  raaghu-mfe/rds_pages/rds-page-tags/src/tags/tags.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#1996 Added test file for application basic.
  raaghu-components/__tests__/rds-comp-application-basic.test.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
Labels: enhancement

#2002 Added test file for user permission new component.
  raaghu-components/__tests__/rds-comp-user-permission-new.test.tsx
  raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.tsx
Labels: enhancement

#2003 Resolved the Roles page bug while editing claims.
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: bug

#2008 Added test file for login component.
  raaghu-components/__tests__/rds-comp-login.test.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
Labels: enhancement

#2009 Fixed the bugs of data table grid in Pages
  raaghu-mfe/rds_pages/rds-page-pages/src/pages/pages.tsx
Labels: enhancement

#2011 PR for #1692, #1903 & #2006
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
Labels: bug

#2022 Build issue is resolved
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-mfe/rds_pages/rds-page-globalResources/src/globalResources/globalResources.tsx
Labels: bug

#2020 Added coverage report for raaghu-components. and added few more tests to application basic and properties component.
  raaghu-components/__tests__/rds-comp-application-basic.test.tsx
  raaghu-components/__tests__/rds-comp-properties.test.tsx
  raaghu-components/jest.config.ts
  raaghu-components/package.json
Labels: enhancement

#2021 Added functionality of Disappearing of the error message after re-e…
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#2023 committed for set theme on refresh page
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#2024 Organization unit, User and Tenant fixes
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: bug

#2025 Fixed the Page alignment issue in forms page.
  raaghu-mfe/rds_pages/rds-page-forms/src/forms/forms.tsx
Labels: bug

#2027 Login and logout issue#1373
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/logout/logout-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
Labels: bug

#2028 PR for #1986 #2014 #2005
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-application-scopes/index.ts
  raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.stories.tsx
  raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.styled.ts
  raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.test.tsx
  raaghu-components/src/rds-comp-application-scopes/rds-comp-application-scopes.tsx
  raaghu-components/src/rds-comp-application-workflows/index.ts
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.stories.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.styled.ts
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.test.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-personaldata/src/personal-data/personal-data.tsx
Labels: bug
