Repository Wai-Technologies/raaghu-react, pull requests merged in 2023-02, with the labels that each got.

#718 Development: data binding on language page
  raaghu-mfe/libs/state-management/hooks.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/language/language-slice.ts
  raaghu-mfe/libs/state-management/login/login-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-language/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.stories.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
Labels: enhancement

#720 Development
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-alert/rds-alert.scss
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.scss
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: enhancement

#722 Fetch the Data from api through edition slice
  raaghu-mfe/libs/state-management/edition/edition-slice.ts
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: enhancement

#724 Enhanced Ui of login page
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/src/rds-modal/rds-modal.stories.tsx
  raaghu-elements/src/rds-modal/rds-modal.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#727 Fixed the organization tree component and button, offcanvas element.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.scss
  raaghu-components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.stories.tsx
  raaghu-components/src/rds-comp-organization-tree-new/rds-comp-organization-tree-new.tsx
  raaghu-components/src/rds-comp-organization-tree/Edit/edit-modal-organization-tree.tsx
  raaghu-components/src/rds-comp-organization-tree/Edit/update-organization-tree.tsx
  raaghu-components/src/rds-comp-organization-tree/Edit/user.tsx
  raaghu-components/src/rds-comp-organization-tree/Edit/usercontext.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.scss
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.stories.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-organization-children.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-organization-parent.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.scss
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
Labels: bug, enhancement

#729 Added noDataTitle props and illustration in datatable
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.stories.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/src/dynamicProperties/dynamicProperties.tsx
Labels: enhancement

#730 implemented raaghu-themes from npm package
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/App.scss
  raaghu-mfe/rds_pages/host/src/App.tsx
  raaghu-themes/package.json
  raaghu-themes/themes/accessible.scss
  raaghu-themes/themes/accordion.scss
  raaghu-themes/themes/alert.scss
  raaghu-themes/themes/avatar.scss
  raaghu-themes/themes/badge.scss
  raaghu-themes/themes/blue.scss
  raaghu-themes/themes/breadcrumb.scss
  raaghu-themes/themes/button.scss
  raaghu-themes/themes/calender.scss
  raaghu-themes/themes/card.scss
  raaghu-themes/themes/carousel.scss
  raaghu-themes/themes/checkbox.scss
  raaghu-themes/themes/colorvariables-dark.scss
  raaghu-themes/themes/colorvariables-light.scss
  raaghu-themes/themes/colorvariables.scss
  raaghu-themes/themes/cookieconsent.scss
  raaghu-themes/themes/counter.scss
  raaghu-themes/themes/custom.scss
  raaghu-themes/themes/default.scss
  raaghu-themes/themes/dropdown.scss
  raaghu-themes/themes/file-uploader.scss
  raaghu-themes/themes/green.scss
  raaghu-themes/themes/input.scss
  raaghu-themes/themes/list-group.scss
  raaghu-themes/themes/nav-tab.scss
  raaghu-themes/themes/offcanvas.scss
  raaghu-themes/themes/orange.scss
  raaghu-themes/themes/pagination.scss
  raaghu-themes/themes/quillEditor.scss
  raaghu-themes/themes/radio-button.scss
  raaghu-themes/themes/responsive.scss
  raaghu-themes/themes/scrollspy.scss
  raaghu-themes/themes/search-input.scss
  raaghu-themes/themes/side-nav.scss
  raaghu-themes/themes/table.scss
  raaghu-themes/themes/tags.scss
  raaghu-themes/themes/textarea.scss
  raaghu-themes/themes/toast.scss
Labels: enhancement

#744 Added Side nav according to abp commercial site.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.stories.tsx
Labels: enhancement

#745 Update service-proxies.ts
  raaghu-mfe/libs/shared/service-proxies.ts
Labels: bug

#748 Language page and data binding
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.stories.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-mfe/libs/shared/service-proxies.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/language/language-slice.ts
  raaghu-mfe/libs/state-management/language/languageEdit-slice.ts
  raaghu-mfe/libs/state-management/login/login-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/nswag/service.config.nswag
  raaghu-mfe/rds_pages/host/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-edition/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-edition/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-language/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.stories.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
Labels: enhancement

#750 Improved Edition page
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: enhancement

#755 Development abp
  package.json
  raaghu-components/package.json
  raaghu-mfe/libs/state-management/edition/edition-slice.ts
  raaghu-mfe/libs/state-management/language/language-slice.ts
  raaghu-mfe/libs/state-management/language/languageEdit-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-auditLogs/package.json
  raaghu-mfe/rds_pages/rds-page-auditLogs/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-dashboard/package.json
  raaghu-mfe/rds_pages/rds-page-dashboard/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/package.json
  raaghu-mfe/rds_pages/rds-page-dynamicProperties/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-edition/package.json
  raaghu-mfe/rds_pages/rds-page-edition/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-forgotpassword/package.json
  raaghu-mfe/rds_pages/rds-page-forgotpassword/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-iconlist/package.json
  raaghu-mfe/rds_pages/rds-page-iconlist/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-language/package.json
  raaghu-mfe/rds_pages/rds-page-language/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-language/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-languageText/package.json
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-languageText/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-login/package.json
  raaghu-mfe/rds_pages/rds-page-login/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-maintainance/package.json
  raaghu-mfe/rds_pages/rds-page-maintainance/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-organizationunits/package.json
  raaghu-mfe/rds_pages/rds-page-organizationunits/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-roles/package.json
  raaghu-mfe/rds_pages/rds-page-roles/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-settings/package.json
  raaghu-mfe/rds_pages/rds-page-settings/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-tenant/package.json
  raaghu-mfe/rds_pages/rds-page-tenant/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-undermaintainance/package.json
  raaghu-mfe/rds_pages/rds-page-undermaintainance/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-users/package.json
  raaghu-mfe/rds_pages/rds-page-users/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-visualSetting/package.json
  raaghu-mfe/rds_pages/rds-page-visualSetting/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/package.json
  raaghu-mfe/rds_pages/rds-page-webhookSubscription/webpack.config.js
Labels: bug

#767 Create a command to generate a new element in raaghu-elements folder.
  package.json
  raaghu-elements/generate-react-cli.json
  raaghu-mfe/package.json
  utils/create-element.js
Labels: enhancement

#769 Added new features component to the raaghu react. and Improved edition page.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
  raaghu-mfe/rds_pages/host/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: enhancement

#774 Added edition page and component
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: enhancement

#778 Added publish feature for raaghu-elements
  raaghu-elements/package.json
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-tag/rds-tag.tsx
Labels: enhancement

#777 Input field error validation and redAsteriskPresent property name cha…
  raaghu-components/package.json
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-edition-new-basic/rds-comp-edition-new-basic.tsx
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-role-list/rds-comp-role-list.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/package.json
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-users/src/users/users.tsx
Labels: enhancement

#798 created axios interceptor and added corrected new service proxy
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/nswag/service.config.nswag
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#801 Added a code to create a index.ts file
  raaghu-components/generate-react-cli.json
  raaghu-elements/generate-react-cli.json
  utils/create.js
Labels: bug

#818 Create language page and date binding for the same
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.stories.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/shared/service-proxies.ts
  raaghu-mfe/libs/shared/service-proxy.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/language/language-slice.ts
  raaghu-mfe/libs/state-management/language/languageEdit-slice.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/rds_pages/rds-page-language/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-language/src/language/language.tsx
  raaghu-mfe/rds_pages/rds-page-languageText/src/languageText/languageText.tsx
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#820 Development abp
  .vs/slnx.sqlite
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.stories.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-client-basic/rds-comp-client-basic.stories.tsx
  raaghu-components/src/rds-comp-client-basic/rds-comp-client-basic.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-child.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav-new.scss
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/style.scss
  raaghu-mfe/libs/state-management/applications/applications-slice.ts
  raaghu-mfe/libs/state-management/applications/applications.models.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-applications/package.json
  raaghu-mfe/rds_pages/rds-page-applications/public/edit-pic.png
  raaghu-mfe/rds_pages/rds-page-applications/public/index.html
  raaghu-mfe/rds_pages/rds-page-applications/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.stories.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/applications/applications.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-applications/src/index.ts
  raaghu-mfe/rds_pages/rds-page-applications/src/remote.d.ts
  raaghu-mfe/rds_pages/rds-page-applications/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-applications/webpack.config.js
Labels: enhancement

#824 Added Organization Unit Page and Made some required changes in Data T…
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.scss
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.scss
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-mfe/libs/state-management/edition/edition-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/organization-tree/organization-tree-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-organizationunits/src/Organization-Tree/Organization-Tree.tsx
Labels: bug

#825 Audit log page data binding
  raaghu-mfe/libs/state-management/audit-logs/audit-log-slice.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.scss
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.stories.tsx
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/Auditlogs/Auditlogs.tsx
Labels: enhancement

#826 committed-text-template
  raaghu-elements/package.json
  raaghu-elements/src/rds-text-editor/rds-text-editor.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/text-template/text-template-slice.ts
  raaghu-mfe/libs/state-management/text-template/text-template.models.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
Labels: enhancement

#828 committed changes for security-logs page
  .vs/slnx.sqlite
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-security-logs/rds-comp-security-logs.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/security-logs/security-logs-slice.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-auditLogs/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/package.json
  raaghu-mfe/rds_pages/rds-page-securitylogs/public/index.html
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/index.ts
  raaghu-mfe/rds_pages/rds-page-securitylogs/src/security-logs/SecurityLogs.tsx
  raaghu-mfe/rds_pages/rds-page-securitylogs/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-securitylogs/webpack.config.js
Labels: enhancement

#832 tenant-page functionality
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.stories.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-elements/package.json
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/tenant/tenant-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/assets/edit-pic.png
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/index.ts
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/tsconfig.json
Labels: enhancement

#827 Scopes page creation and functionality
  .vs/VSWorkspaceState.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-api-scope-resource/rds-comp-api-scope-resource.tsx
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/libs/state-management/apiScope/apiScope-slice.ts
  raaghu-mfe/libs/state-management/apiScope/apiScope.models.ts
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/package.json
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/host/src/remote.d.ts
  raaghu-mfe/rds_pages/host/webpack.config.js
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-apiScope/package.json
  raaghu-mfe/rds_pages/rds-page-apiScope/public/index.html
  raaghu-mfe/rds_pages/rds-page-apiScope/src/App.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/bootstrap.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/index.ts
  raaghu-mfe/rds_pages/rds-page-apiScope/tsconfig.json
  raaghu-mfe/rds_pages/rds-page-apiScope/webpack.config.js
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: enhancement

#842 Changes done in yaml files
  .github/workflows/development_raaghumfestageui.yml
  .github/workflows/development_storybookreact.yml
  raaghu-components/package.json
  raaghu-elements/package.json
  raaghu-mfe/nswag/service.config.nswag
  tsconfig.json
Labels: bug

#835 Rectified Input null value handling error and enhancement in claimTypes and edition page
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-claimtypes/src/Claim-Types/Claim-Type.tsx
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
Labels: bug, enhancement

#837 committed-enhancement-in-permission-tree
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.scss
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
Labels: enhancement

#839 change history selection in Scopes page
  raaghu-mfe/libs/state-management/apiScope/apiScope-slice.ts
  raaghu-mfe/rds_pages/host/src/Main.tsx
  raaghu-mfe/rds_pages/rds-page-apiScope/src/apiScope/apiScope.tsx
Labels: enhancement

#845 Resolved build issues.
  .github/workflows/development_raaghumfestageui.yml
  raaghu-mfe/rds_pages/mfe-config.ts
  raaghu-mfe/rds_pages/port-config.ts
  raaghu-mfe/rds_pages/rds-page-edition/src/edition/edition.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/package.json
  raaghu-mfe/rds_pages/rds-page-texttemplate/tsconfig.json
  raaghu-mfe/utils/appconfig.json
  raaghu-mfe/utils/build.js
Labels: bug

#848 Resolved build level issues.
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: bug

#849 Update rds-select-list.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: bug

#838 setting page functionality
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-account/rds-comp-account.stories.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.module.scss
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.stories.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/public.api.ts
  raaghu-mfe/libs/state-management/settings/settings-slice.ts
  raaghu-mfe/libs/state-management/settings/settings.models.ts
  raaghu-mfe/rds_pages/rds-page-settings/src/Settings/Settings.tsx
Labels: enhancement

#852 Created Roles page, added data binding and state management for the same.
  raaghu-mfe/libs/state-management/index.ts
  raaghu-mfe/libs/state-management/roles/roles-slice.ts
  raaghu-mfe/rds_pages/rds-page-roles/src/Roles/Roles.tsx
Labels: enhancement

#853 committed-text-template-UI-bug-fixed-for-functionality
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-mfe/rds_pages/rds-page-texttemplate/src/texttemplate/text-template.tsx
Labels: bug

#863 settings page build errors solved
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
Labels: bug

#864 URL changes from localhost to demoapi server
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-mfe/libs/shared/interceptor.ts
  raaghu-mfe/rds_pages/rds-page-login/src/Login/Login.tsx
Labels: bug

#865 tenant page updated
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-mfe/rds_pages/rds-page-tenant/src/tenant/tenant.tsx
Labels: bug
