Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-08, with the labels that each got.

#614 Completed Task 606 : Integration Of Chromatic In Storybook For Visual Testing For Raaghu Design System
  package.json
Labels: Task

#616 Completed Task 615 : Visual Testing For Storybook
  .storybook/main.ts
  chromatic.config.json
  package.json
Labels: Task

#617 Updated Staging Action : "Raaghu Design System Storybook Deployment"
  .github/workflows/storybookreact.yml
Labels: Deployment

#580 Resolved Bug 539 : Resolved Storybook Components Issues
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-page-not-found/rds-comp-page-not-found.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
Labels: Bug

#581 Resolved Bug 511 and 568 : Storybook > Elements > Feed > Select dark theme star color is not change And Storybook > Elements > Widget Portal > Incorrect text
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.css
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.stories.tsx
Labels: Bug

#583 Resolved Bug 569 and 582 : Small and Large Mobile View Language Pop Up Is Not Display Proper , Color Code Is Invalid.
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#587 Resolved Bug 448, 570, 472 and 589 : Issue on Visual Setting Component, Hand Cursor Issue on Icons, Issues on Collapsible Container and Assistance Component
  .storybook/custom-theme.css
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.scss
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.style.css
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.tsx
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-components/src/rds-comp-subscription/rds-comp-subscription.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-typeahead/rds-comp-typeahead.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.css
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.stories.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-card-detail/rds-card-detail.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-feed/rds-feed.tsx
  raaghu-elements/src/rds-icon-label/rds-icon-label.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-popular-page/rds-popular-page.tsx
  raaghu-elements/src/rds-price/rds-price.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-elements/src/rds-stat/rds-stat.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#597 Resolved Bug 586 and 594 : Dark Theme Text Is Not Display Proper And Dark Theme Selected Value Is Not Visible Proper
  raaghu-react-themes/src/styles/button.scss
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#599 Resolved Bug 567 and 574 : Storybook > Components > Product List > Images alignment is not proper And Component > Edition New Basic : Validation missing for Edition Name. No error message if its kept emptyoved
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-product-list/rds-comp-product-list.css
  raaghu-components/src/rds-comp-product-list/rds-comp-product-list.tsx
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.tsx
Labels: Bug

#600 Resolved Bug 563 : After Submitting Field Is Not Clear
  raaghu-components/src/rds-comp-theme/rds-comp-theme.tsx
Labels: Bug

#607 Completed Task 601 : Implement Different Divider
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-divider/index.ts
  raaghu-elements/src/rds-divider/rds-divider.css
  raaghu-elements/src/rds-divider/rds-divider.stories.tsx
  raaghu-elements/src/rds-divider/rds-divider.tsx
Labels: Task

#608 Completed Task 591 : Implement Different Types Buttons
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: Task

#613 Resolved Bug 526 : Changes Made for the Stacked Chart Views
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#620 Action Changes : Added Staging Environment into "Raaghu React Storybook Deployment" Actions
  .github/workflows/storybookreact.yml
Labels: Deployment

#623 Completed Task 612 : Add the New Type of Breadcrumb
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.css
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
Labels: Enhancement

#631 Resolved Bug 628 : Label Is CICD Instead Of Ci/CD
  stories/Introduction.stories.mdx
Labels: Bug

#632 Resolved Bug 629 : App Details > Incorrect Word
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
Labels: Bug

#633 Resolved Bug 630 : Banner > Space is missing between word News and !
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
Labels: Bug

#636 Resolved Bug : Build Issue
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/__tests__/rds-breadcrumb.test.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
Labels: Deployment

#635 Adding Action into Development branch
  .github/workflows/storybookreact.yml
Labels: Deployment
