Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-04, with the labels that each got.

#146 Bug #143 : Restructure the Integration component.
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-integration/rds-comp-integration.stories.tsx
  raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx
Labels: Bug

#147 Bug 144: Resolved Issue on Components Profile Edit.
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
Labels: Bug

#149 Bug 148 : Resolved Components Rendering and Alignment Issues
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-profile/rds-comp-profile.stories.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.stories.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.styled.ts
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-shopping-cart/rds-comp-shopping-cart.stories.tsx
  raaghu-components/src/rds-comp-shopping-cart/rds-comp-shopping-cart.tsx
Labels: Bug

#151 Resolved Bug 152 : User Role Rendering Issue
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.stories.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
  raaghu-components/src/rds-comp-user-table/rds-comp-user-table.tsx
Labels: Bug

#153 Bug 143 : Enhance Product Image component.
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.css
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.stories.tsx
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.tsx
Labels: Bug

#155 Bug 144: Resolve Issue on Component Features new.
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.stories.ts
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
Labels: Bug

#159 Bug #154 : Enhance the Product List component.
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.css
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.tsx
  raaghu-components/src/rds-comp-product-list/rds-comp-product-list.stories.tsx
Labels: Bug

#162 Bug 161 : Issues on Component User Table
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-user-table/rds-comp-user-table.stories.tsx
Labels: Bug

#165 Bug 150 : Resolved Issue on Tenant and Admin Dashboard Components
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
Labels: Bug

#167 Bug 163 : Resolved Bug of Change Default Color and Radio Button Issue
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#169 Bug 168 : Resolved Introduction Page UI Issues
  package.json
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.stories.tsx
  stories/Introduction.stories.mdx
  stories/assets/app-shell-learn-more.svg
  stories/assets/app-shell.png
  stories/assets/bootstrap.png
  stories/assets/bootstrap.svg
  stories/assets/charts-learn-more.png
  stories/assets/charts-learn-more.svg
  stories/assets/components-learn-more.png
  stories/assets/components-learn-more.svg
  stories/assets/elements-learn-more.png
  stories/assets/elements-learn-more.svg
  stories/assets/layouts-learn-more.png
  stories/assets/layouts-learn-more.svg
  stories/assets/maps-learn-more.png
  stories/assets/maps-learn-more.svg
  stories/assets/million.svg
  stories/assets/react.png
  stories/assets/react.svg
  stories/assets/storybook.png
  stories/assets/storybook.svg
  stories/assets/ts.png
  stories/assets/ts.svg
  stories/assets/typescript.png
  stories/assets/vite.png
  stories/assets/vite.svg
Labels: Bug

#171 Bug 170 : Component > Permission Tree Rendering Issue
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
Labels: Bug

#175 Bug 166 : Resolved Issue on Component Top Navigation Add "Linked Accounts" and "Authority Delegation" in Host off Canvas
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-react-themes/src/styles/card.scss
Labels: Bug

#178 Bug 172 : Resolved Issues on Account Component
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#179 Task : Moving Portal Components to Storybook
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-payment-tenure/index.ts
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.scss
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.stories.tsx
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
  raaghu-components/src/rds-comp-summary-details/index.ts
  raaghu-components/src/rds-comp-summary-details/rds-comp-summary-details.scss
  raaghu-components/src/rds-comp-summary-details/rds-comp-summary-details.stories.tsx
  raaghu-components/src/rds-comp-summary-details/rds-comp-summary-details.tsx
  raaghu-components/src/rds-comp-tenant-register/index.ts
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.stories.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Task, Enhancement

#181 Bug 176: Resolved Issue on Application Basic and Change Password
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
Labels: Bug

#182 Bug#180 : Enhance Billing Address and Change User Password Components
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.stories.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
Labels: Bug

#185 Bug 184 : Resolved Issue on Components for display Submitted Data
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.stories.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.stories.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  stories/assets/storybook-hero-Banner.png
Labels: Bug

#188 Enhancement 187 : Add Account External Provider Component to Storybook
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-account-external-provider/index.ts
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.stories.tsx
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
Labels: Enhancement

#197 Bug #186 : Enhanced Identity Resource Basic Component.
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.stories.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
Labels: Bug

#198 Bug #191 : Enhanced New Role Component.
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.stories.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
Labels: Bug

#199 Bug 191 : Enhance Edit Language Text Component
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
Labels: Bug

#200 Bug 195 : Resolved Issue on Components for display Submitted Data
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.stories.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.stories.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
Labels: Enhancement

#203 Bug 190 : Enhancement On Tenant Information Component
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.stories.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
Labels: Bug

#204 Bug #192 : Enhancement On Secrets and Notification Setting Components.
  raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.stories.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
Labels: Bug

#202 Bug 189 : Enhancement on Contact Information Component
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.stories.tsx
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
Labels: Bug

#207 Bug 193: Resolved Issue Enhancement On Component Api Resource Basic, Contact Us.
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.stories.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.stories.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
Labels: Bug

#208 Bug 194: Resolved Issue On Component New Claim Type, Set Password.
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.stories.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.stories.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
Labels: Bug

#209 Bug 201 : Resolved Rendering and UI Issue on Components
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.stories.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-elements/src/rds-testimonial/rds-testimonial.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#210 Bug 194: Resolved Issue On Enhancement on Component- Register.
  raaghu-components/src/rds-comp-register/rds-comp-register.stories.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
Labels: Bug

#211 Enhancement 196 : Completed Enhancement on Components for display Submitted Data on User Claim and Tenant Setting Component
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-react-themes/src/styles/card.scss
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/colorvariables-semidark.scss
Labels: Enhancement

#214 Enhancement 206 : Component > Forms Email and Profile Picture
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
Labels: Enhancement

#215 Enhancement 191 : Blog Post New Component
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.stories.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
Labels: Enhancement

#216 Bug 212 : Resolved Rendering and UI Issue on Polls Option Components
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
Labels: Bug

#217 Enhancement 205 : Component > Edition Information
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Enhancement

#218 Enhancement 192 : Scope Basic Resource Component
  package.json
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.stories.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
Labels: Enhancement

#219 Bug 193 : Resolved Issue Enhancement On Component Forgot Password
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
Labels: Bug

#220 Resolved Bug : Build Issue On Scope Basic Recourse Component
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.stories.tsx
  raaghu-elements/src/rds-address-detail/rds-address-detail.stories.tsx
Labels: Bug

#225 Bug 224 : Issues on Component Menus Directories
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.stories.tsx
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
Labels: Bug

#227 Bug 183 : Issues on Component Dynamic Entity Property
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.stories.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
Labels: Bug

#228 Bug 226 : Resolved Issues on Personal Info Component
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.stories.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
Labels: Bug

#229 Bug 156 : Components Organization Tree Issue
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.css
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
Labels: Bug

#231 Bug #230 : Resolved the Validation Message Issues on Components
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
Labels: Bug

#235 Bug 234 : Issues on Component File Management Tree
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.stories.tsx
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#236 Bug #230 : Resolved Components Validation Issues
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
Labels: Bug

#237 Enhancement 233 : Completed Enhancement on Components for display Submitted Data on Webhook Subscription and User Claim Component
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.stories.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
Labels: Enhancement

#238 Bug 230: Resolved Validation Message Issues on Components.
  raaghu-components/src/rds-comp-edition-new-basic/rds-comp-edition-new-basic.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
Labels: Bug

#240 Bug 230: Resolved Validation Message Issues on Components.
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.stories.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-edition-new-basic/rds-comp-edition-new-basic.tsx
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: Bug

#243 Bug 230 : Resolved Validation and Control Issues on Application Workflow
  package.json
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.stories.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
Labels: Bug

#251 Merged Development : Changes Merged from Development to Production for Latest Version from 1.0.7 to 1.0.8
  .github/workflows/required-reviewers.yml
  .storybook/manager-head.html
  package.json
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.stories.tsx
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.stories.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.stories.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.stories.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-edition-new-basic/rds-comp-edition-new-basic.tsx
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.stories.tsx
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.stories.tsx
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.css
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.stories.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.stories.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-react-themes/src/styles/custom.scss
  stories/assets/dashboard.png
Labels: Latest Version, Storybook, NPM Package

#252 Bug 247 : Resolve Issues on Component Background Image
  raaghu-components/src/rds-comp-background-image/rds-comp-background-image.stories.tsx
  raaghu-components/src/rds-comp-background-image/rds-comp-background-image.tsx
Labels: Bug

#253 Bug 248 : Resolved Issues on Register Component
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
Labels: Bug

#254 Bug 239 : Resolved Issue on Component Address Input
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#255 Bug 249 : Resolved Issues on Security Component
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
Labels: Bug

#267 Bug 261 : Resolved Issues on Delivery Method Component
  raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.tsx
Labels: Bug

#268 Bug 246 : Resolved Issues on Application Workflows Component
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.stories.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
Labels: Bug

#270 Bug 256: Resolved Issue on Components Spacing is Expected Between Title and Field.
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Bug

#271 Bug 257: Resolved Issue on Components Save and Cancel Button Spacing.
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-client-resources/rds-comp-client-resources.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
  raaghu-components/src/rds-comp-order-summary/rds-comp-order-summary.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
Labels: Bug

#272 Bug 266 : Resolved Issues on Email Component
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
Labels: Bug

#276 Bug 264 : Resolved Issue on Edition Component
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
Labels: Bug

#279 Bug 265 : Resolved Issues on Email Settings Component
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
Labels: Bug

#281 Bug 260 : Resolved Issue on Datatable Pagination is Missing
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
Labels: Bug

#283 Bug 284 : Responsiveness of Introduction Page UI for Different Devices
  stories/Introduction.stories.mdx
Labels: Bug

#289 Enhancement : Updated Design System Version to 1.0.9
  package.json
  raaghu-react-themes/README.md
  raaghu-react-themes/package.json
  stories/Introduction.stories.mdx
Labels: Enhancement

#291 Bug 280 : Resolved Issues on Detail List Component
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.tsx
Labels: Bug

#292 Bug 278 : Resolved Issues on Permission Tree New Component
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#293 Bug 288 : Resolved Issue on Component Pagination on Mouse Hovering Value Gets Fade and Number and Chevron Should be in the Middle
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#295 Bug 285 : Resolved Issue on List Group Element
  raaghu-elements/src/rds-list-group/rds-list-group.tsx
Labels: Bug

#296 Bug 102: Resolved Issue on Component Visual Setting Update Themes and Default Value is Expected on Dropdown.
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.stories.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
Labels: Bug
