Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-12, with the labels that each got.

#1191 Resolved Bug 852 : Design-System-Version-8-3-Side-navigation-bar-font-size-font-style-not-consistent
  .storybook/custom-theme.css
Labels: Bug

#1182 Completed Task 1158 : Design system enhancement file uploader component
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Enhancement

#1166 Completed Task 749 : Design System > Element > Alert : Alert issues #749
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: Task

#1193 Resolved bug 991 : Design System > Components > Calendar > Small mobile view text and alignment issue.
  raaghu-components/src/rds-comp-calendar/rds-comp-calendar.css
Labels: Bug

#1171 Resolved bug 1092 : Design System > Components > Add Member > Off canvas close icon is not working.
  raaghu-elements/src/rds-button/rds-button.css
Labels: Bug

#1196 Resolved bug 1111 : Design System > Components > File Management Tree> Default > Vertical node does not display proper.
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1197 Resolved bug 1102 : Design System > Elements > Input Group> Size control is not working proper.
  raaghu-react-themes/src/styles/button.scss
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1206 Resolved Bug 1198 : Design System > Tree structure build issues
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.stories.tsx
Labels: Bug

#1202 Completed Task 592 : Design System > Implement different types of Avtaars
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Task

#1210 Resolved Bug 894 : Design System > Components > Visual Setting> Default > Small large mobile Sub header Footer overlap
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
Labels: Bug

#1204 Resolved bug 969 : Design System >Elements > Payment Card > Default > Label and button alignment issue.
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.tsx
Labels: Bug

#1212 Resolved bug 845 : Design System > Components > My Settings > Default > Error message alignment issue.
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
Labels: Bug

#1214 Completed Task 989 : Design System > Element > AI Prompt for new project
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#726 Resolved Bug 593 : Design Systems > Implement different types of input
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Enhancement

#1217 Resolved Bug 1093 : Design System > Components > Features > Alignment issue.
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-navtabs/rds-navtabs.css
Labels: Bug

#1218 Resolved bug 1106 : Design System > Components > Address Input > Default > Input box alignment issue.
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#1201 Resolved Bug 1195 : Design System > In Calendar Only Selected Month's Date Should Be Visible, Rest Can Be Greyed Out
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#1203 Resolved Bug 1049 : Design System > Components > Side Navigation > Default > Image & text is not display correct.
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.stories.tsx
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Bug

#1223 Resolved bug 1090 : Design System >Elements > File Uploader > All stories multiple -true upload file display twice file. #1090
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#1227 Resolved Bug 1215 : Design System > Elements > Datepicker > Default/With time/Advanced > Layout > Minor UI issues
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Bug

#1219 Completed Task 795 : Design System > Elements > Enhancements in Input.
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Task

#1229 Completed Task 784 : Design System > Elements > Enhancements in Action Button/Dropdown
  raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
Labels: Task

#1168 Completed Design System > Element or Component > Comment component issue while exporting it as a reference in another project and has formatting issue
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
Labels: Able Systems

#1237 Resolved Bug 1225 : Design System > Element > Input > Enhancement in alignment and validations
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-react-themes/src/styles/default.scss
  raaghu-react-themes/src/styles/label.scss
Labels: Bug

#1235 Resolved Bug 1209 : Design System > Side nav bar > Component > Components are not arrange in alphabetically
  raaghu-components/src/rds-comp-bank-card-detail-list/index.ts
  raaghu-components/src/rds-comp-bank-card-detail-list/rds-comp-bank-card-detail-list.css
  raaghu-components/src/rds-comp-bank-card-detail-list/rds-comp-bank-card-detail-list.stories.tsx
  raaghu-components/src/rds-comp-bank-card-detail-list/rds-comp-bank-card-detail-list.tsx
  raaghu-components/src/rds-comp-card-detail-list/index.ts
Labels: Bug

#1231 Resolved Bug 1208 : Design System > Component > Top Navigation > Ecommerce 4 > Text overlapping issue
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: Bug

#1238 Resolved Bug 1233 : Design system > Side nav bar > Charts and maps are not display in the element section
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.stories.tsx
  raaghu-elements/src/rds-chart-area/rds-chart-area.stories.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.stories.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.stories.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.stories.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.stories.tsx
  raaghu-elements/src/rds-map/rds-map.stories.tsx
Labels: Bug

#1240 Resolved Bug 1236 : Design system > Elements/Components > Bank card details > C is show in capital letters
  raaghu-components/src/rds-comp-bank-card-detail-list/rds-comp-bank-card-detail-list.stories.tsx
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.stories.tsx
  raaghu-elements/src/rds-card-detail/rds-card-detail.stories.tsx
Labels: Bug

#1244 Completed Task 795 : Design System > Elements > Enhancements in Input.
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Task

#1239 Resolved bug 1102 : Design System > Elements > Input Group> Size control is not working proper.
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#1228 Resolved Bug 1226 : Design System > Elements > Counter > Counter button alignment issue
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
Labels: Bug

#1220 Completed Task 1146 : Design System > Component >enhancement of the alert popup and in otp input
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-components/src/rds-comp-otpinput/styles.css
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Enhancement

#1246 Resolved Bug 1216 : Design System > Elements > Accordion > Docs > Background color is showing to the chevron of first accordion
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
Labels: Bug

#1248 Completed Task 593 : Design System > Implement different types of Inputs
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Task

#1250 Resolved Bug 753 : Design System > Elements > Card : Minor Issues
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Bug

#1254 Resolved bug 1247 : Design System > Elements > Date picker > Default/Advanced/With time> Not able to see greyed out date after hovering
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
Labels: Bug

#1257 Resolved bug 1252 : Design System > Elements > All components error message alignment issue.
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Bug

#1249 Resolved Bug 971 : Datepicker > Advanced > Custom Icon Is Not Displaying Properly, Open Modal Alignment & Border Issue.
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Bug

#1253 Resolved bug 845 : Design System > Components > My Settings > Default > Error message alignment issue.
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1255 Resolved Bug 1131 : Design System > Components >Login Attempts > Default >Select Date Range overlap dropdown & dark theme pagination number is not display.
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
Labels: Bug

#1259 Resolved Bug 1258 : Design System > Element > Toaster > Position issue
  raaghu-elements/libs/types/placement.ts
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/toast.scss
Labels: Bug

#1256 Resolved Bug 1136 : Design System > Components > Profile Edit > Default >Small, Large mobile view input box alignment issue.
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
Labels: Bug

#1266 Completed Task 777 : Design System > Elements > Enhancements in file uploader
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Task

#1265 Resolved Bug 989 : Design System > Element > AI Prompt for new project flow
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
Labels: Bug

#1267 Completed Task 820 : Design System > Elements > Side navigation enhancements
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Task

#1268 Resolved bug 1111 : Design System > Components > File Management Tree> Default > Vertical node does not display proper.
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1269 Resolved Bug 1143 -: Components Tenant Settings Default Small Large Mobile Save Cancel Button alignment issue
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Bug

#1270 Completed Task 849 : Design System > Element > Progress Bar > Default : Enhancements in style.
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
Labels: Task

#1271 Resolved Bug 1140 : Components Login Attempts Dark and light theme pagination number
  raaghu-elements/src/rds-pagination/rds-pagination.css
Labels: Bug

#1273 Merge Development : Moving Changes from Development to Staging Branch
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-components/src/rds-comp-otpinput/styles.css
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-elements/libs/types/placement.ts
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/button.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/side-nav.scss
  raaghu-react-themes/src/styles/toast.scss
Labels: Deployment

#1230 Reviewed Latest Contributions
  Contributors.txt
Labels: Enhancement

#1297 Completed Task 820 : Design System > Elements > Side navigation enhancements
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Task

#1302 Resolved Bug 1263 : Fixed Button Alignment And Link Alignment As Per Figma Design
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
Labels: Bug

#1305 Resolved Bug 956 : Fixed Design System Side Navigation Multiple issues in side navigation
  .storybook/custom-theme.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Bug

#1277 Resolved bug 1102 : Design System > Elements > Input Group> Size control is not working proper.
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
Labels: Bug

#1316 Completed task 795 : Design System > Elements > Enhancements in Input.
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Task

#1315 Resolved bug 1106 : Design System > Components > Address Input > Default > Input box alignment issue.
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#1319 Resolved bug 1107 : Design System > Components > Chat > Default > Placeholder text & icon is not centralized.
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
Labels: Bug

#1272 Resolved bug 1134 : Design System > Components >Polls-Question > Default > Widget first value is by default selected, select list & date picker alignment issue.
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
Labels: Bug

#1338 Resolved Bug 1311: Design System > Elements > Pagination > Advanced > Dark theme pagination is not display proper
  raaghu-elements/src/rds-pagination/rds-pagination.css
Labels: Bug

#1328 Resolved Bug 1303: Design System > Component > Cache > Pagination number is not display proper
  raaghu-elements/src/rds-pagination/rds-pagination.css
Labels: Bug

#1313 Resolved Bug 1145: Components Tenant List Default When the mouse hovers over a small view the popup is hidden
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.css
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
Labels: Bug

#1345 Resolved Bug 1339: Design System > Side Navigation > Side Navigation with List > When we click on sub menu these are not highlighted
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: Bug
