Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-06, with the labels that each got.

#392 Bug 388 : Issue on Components Edition Information Alignment Issue
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Bug

#394 Task 393 : Create Loader Element in Storybook and Add Loaders
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-loader/index.ts
  raaghu-elements/src/rds-loader/rds-loader.stories.tsx
  raaghu-elements/src/rds-loader/rds-loader.test.tsx
  raaghu-elements/src/rds-loader/rds-loader.tsx
  raaghu-react-themes/src/styles/default.scss
  raaghu-react-themes/src/styles/loaders.scss
Labels: Task

#395 Task 377 : Added Premium Support & Purchase Developer Seats Component on Storybook
  raaghu-components/package.json
  raaghu-components/public/assets/downloadable-section.png
  raaghu-components/public/assets/headset-purple.svg
  raaghu-components/public/assets/headset.svg
  raaghu-components/public/assets/screen-sharing.svg
  raaghu-components/public/assets/seatPurple.svg
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.test.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.test.tsx
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.test.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.test.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.test.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.test.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.test.tsx
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.test.tsx
  raaghu-components/src/rds-comp-premium-support/index.ts
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.css
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.stories.tsx
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
  raaghu-components/src/rds-comp-purchase-developer-seats/index.ts
  raaghu-components/src/rds-comp-purchase-developer-seats/rds-comp-purchase-developer-seats.stories.tsx
  raaghu-components/src/rds-comp-purchase-developer-seats/rds-comp-purchase-developer-seats.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.test.tsx
  raaghu-elements/src/rds-loader/rds-loader.test.tsx
Labels: Task

#426 Bug 396, 397, 398 : Resolved Issues on Checkbox Group, Datepicker, Avatar Elements
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Bug

#427 Bug 399, 403 : Resolved Issues on Toggle Element and Api Resource Basic Component
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-react-themes/src/styles/toggle.scss
Labels: Bug

#432 Bug 408, 410 : Resolved Issues on Feeds And Email Settings Component
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.stories.tsx
Labels: Bug

#433 Bug 414, 415, 416 : Resolved issues on Get Assistance, Identity Management & Invoice Detail Receipt Component
  .storybook/assets/WAi-logo.png
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
Labels: Bug

#439 Bug 418, 419, 420, 421, 422, 423, 424, 425, 430, 434, 435 : Resolved Issues on Payment Card, Order Confirmation, Login, New Language, Identity Oauth Management, Benefit, Change User Password, CMS, Identity Client Basic, Identity Ldap Management Components
  .storybook/assets/payment-inprogress.mp4
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.stories.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.stories.tsx
  raaghu-components/src/rds-comp-download-collation/rds-comp-download-collation.stories.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.tsx
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.stories.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-react-themes/src/styles/colorvariables.scss
Labels: Bug

#447 Bug 431, 436, 437, 440, 441 : Added Advanced story in Email Setting & Issues on Integration, Feature New, Payment Details, Product List Components
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.stories.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#451 Bug 442, 443, 444, 445, 446 : Resolved Issues on Personal Info, Properties, User Basics, Teams, Secrets & Register Components
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-download-collation/rds-comp-download-collation.stories.tsx
  raaghu-components/src/rds-comp-download-collation/rds-comp-download-collation.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.css
Labels: Bug

#453 Completed Task : Build Issue for Version 1.1.3 and Update Version to 1.1.4
  package.json
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
Labels: Storybook, NPM Package
