Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-07, with the labels that each got.

#459 Bug 403, 449, 452 : Resolved Issues on Api Resource Basic, Alert Popup, Account, Dynamic Entity Properties & Password Setting Components
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
Labels: Bug

#461 Bug 307, 400, 436, 437 : Resolved Issues on Profile Edit, Storybook Scrollbar, Integration, Features New & Directory List Components
  .storybook/assets/edit-pic.png
  .storybook/custom-theme.css
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.stories.tsx
  raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
Labels: Bug

#471 Bug 463, 464, 465 : Resolved Issues on Color Picker, Navbar & Button Group Elements
  raaghu-elements/src/rds-color-picker/rds-color-picker.css
  raaghu-elements/src/rds-color-picker/rds-color-picker.tsx
  raaghu-elements/src/rds-navbar/rds-navbar.css
  raaghu-elements/src/rds-navbar/rds-navbar.stories.tsx
  raaghu-elements/src/rds-navbar/rds-navbar.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#473 Enhancement 469: DS > Implement Changes to Urls through application for Updated Urls
  .storybook/customTheme.js
  package.json
  raaghu-components/package.json
  raaghu-components/src/rds-comp-product-list/rds-comp-product-list.stories.tsx
  raaghu-elements/package.json
  stories/Introduction.stories.mdx
Labels: Enhancement

#474 Bug 466 : Resolved Issues on File Uploader Component
  .storybook/raaghuTheme.js
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
Labels: Bug

#477 Merged Latest : Changes Merged for Latest Version from 1.1.4 to 1.1.5
  package.json
  raaghu-pages/tsconfig.json
Labels: Latest Version, NPM Package

#480 Resolved Bug 275 : Component > Hide Unused components
  .storybook/manager-head.html
Labels: Bug

#484 Completed Task 475 : Add newly designed and existing updated Layout from Abel Systems
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
Labels: Enhancement

#486 Enhancement 472, Bug 429 and 448 : Added Abel System Component Collapsible Container on Storybook
  raaghu-components/src/rds-comp-collapsible-container/index.ts
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.stories.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.style.css
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.tsx
  raaghu-components/src/rds-comp-download-collation/rds-comp-download-collation.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
Labels: Bug, Enhancement

#487 Completed Task 478 : Implement Top Navigation With Search
  raaghu-components/src/rds-comp-top-navigation-with-search/index.ts
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.stories.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.styled.ts
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.test.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
Labels: Enhancement

#490 Resolved Bug 470 and 481 : Elements > Notification > Selecting dark theme button text is not display and Storybook > Elements > Card Detail > Selecting small mobile view radio button is stick on card text.
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-card-detail/rds-card-detail.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-size/rds-size.css
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.css
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.tsx
Labels: Bug

#493 Resolved Bug 467, 482 and 485 : Resolved Issues on Counter, Collapse, Button and Card Element Issues
  raaghu-elements/__tests__/rds-card.test.tsx
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-collapse/rds-collapse.tsx
  raaghu-elements/src/rds-counter/rds-counter.css
Labels: Bug

#501 Completed Task 498 : Change Path from Angular Reference to Current Repo of Storybook
  .storybook/assets/Door_hanger.png
  .storybook/assets/Ink_pen.png
  .storybook/assets/Layer_glass_bottle.png
  .storybook/assets/Leather_long_wallet.png
  .storybook/assets/Leather_wallet.png
  .storybook/assets/Lounge_Chair.png
  .storybook/assets/Pen_with_diary.png
  .storybook/assets/brass_metal.png
  .storybook/assets/earthen_bottle.png
  .storybook/assets/elegant_creative_art.png
  .storybook/assets/finish_table.png
  .storybook/assets/inline_price.png
  .storybook/assets/leather_bag.png
  .storybook/assets/leather_girls_bag.png
  .storybook/assets/leather_office_bag.png
  .storybook/assets/pure_glass_bottle.png
  .storybook/assets/school_bag_black_red.png
  .storybook/assets/school_bag_green.png
  .storybook/assets/school_bag_red.png
  .storybook/assets/tea_coaster_Set_antique.png
  .storybook/assets/tumbler_bottle.png
  .storybook/assets/wood_chair.png
  .storybook/assets/wood_primer_toy.png
  raaghu-components/src/rds-comp-product-list/rds-comp-product-list.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
Labels: Enhancement

#506 Resolved Bug 499 : Storybook > Charts > Pie Chart > Small and Large Mobile View Alignment Issue Color and Chart
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.tsx
Labels: Bug

#514 Bug 488, 495 : Resolved Issues on Input Element and Email Component
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#515 Bug 496 : Storybook > Elements > Stat > Default > Dark Theme Icon Color is not change
  raaghu-components/src/rds-comp-integration/rds-comp-integration.css
  raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#520 Bug 511: Resolved Storybook >Elements>Feed> Select dark theme star color is not change
  raaghu-elements/src/rds-feed/rds-feed.styled.css
  raaghu-elements/src/rds-feed/rds-feed.tsx
Labels: Bug

#532 Completed Task : Build Issue for Version 1.1.5 and Update Version to 1.1.6
  package.json
Labels: Enhancement, NPM Package

#524 Bug 491, 507 and 510 : Resolved Issues on Loader Element, Developer Mode and Delivery Method Component
  raaghu-components/src/rds-comp-calendar/rds-comp-calendar.css
  raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.css
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.stories.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-react-themes/src/styles/loaders.scss
Labels: Bug

#528 Resolved Bug 417 : Start Date and End Date Issue which not display in Action
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Enhancement

#535 Bug 494, 497 and 531 : Storybook > Elements > Scrollspy > Default > Small and Large Mobile View Card Content and Button Overlap, Storybook > Elements >Toast>Toast without header > Cross Icon Alignment Issue and Storybook > Elements > Review Category > Default > Selecting Dark Theme Star Color is not change
  raaghu-elements/src/rds-review-category/rds-review-category.css
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.css
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.tsx
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#536 Bug 516, 521, 525 : Cache, New Menu, Email Setting Component and Website Matrix Element
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-cache/rds-comp-cache.stories.tsx
  raaghu-components/src/rds-comp-email-settings-new/index.ts
  raaghu-components/src/rds-comp-email-settings-new/rds-comp-email-settings-new.css
  raaghu-components/src/rds-comp-email-settings-new/rds-comp-email-settings-new.stories.tsx
  raaghu-components/src/rds-comp-email-settings-new/rds-comp-email-settings-new.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-elements/src/rds-table/rds-table.stories.tsx
  raaghu-elements/src/rds-table/rds-table.tsx
  raaghu-elements/src/rds-website-matrix/rds-website-matrix.stories.tsx
  raaghu-elements/src/rds-website-matrix/rds-website-matrix.tsx
Labels: Bug

#538 Bug 522 : Storybook > Charts > Scatter Chart > Docs > Stories Scatter Chart through Error
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.stories.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.tsx
Labels: Bug

#540 Bug 500 and 508 : Storybook > Components > Billing > Default > Small and large mobile view first card is not display And Storybook > Elements > Dropdown List > Default > Select dark theme chevron is not visible
  raaghu-components/src/rds-comp-billing/rds-comp-billing.css
  raaghu-components/src/rds-comp-billing/rds-comp-billing.tsx
  raaghu-components/src/rds-comp-subscription/rds-comp-subscription.css
  raaghu-elements/src/rds-counter/rds-counter.css
Labels: Bug

#545 Bug 543 : Resolved UI Issue In Bank Card Detail Elements
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.tsx
Labels: Bug

#548 Bug 504 : Element File Uploader Unable to upload multiple files
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#549 Bug 547 : Placeholder Is Not Proper And Add Phone No Validation
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
Labels: Bug

#556 Bug 550 : Components > Tenant Settings > Placeholder and Warning Issue
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
Labels: Bug

#558 Bug 554 : Add Url Validation And Change Warning Message.
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
Labels: Bug

#560 Bug #509 #526 Modal Issue Inside Datatable and Different Views Issue Inside Stacked Chart
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.css
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#564 Bug 429, 492, 551 : Resolved Issues on Download Collection, Premium Support Component & Popover Element
  raaghu-components/src/rds-comp-download-collation/rds-comp-download-collation.tsx
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
  raaghu-elements/src/rds-popover/rds-popover.css
  raaghu-elements/src/rds-popover/rds-popover.tsx
Labels: Bug

#571 Completed Task 555 : Create Script Enhancement With Reference of Support Application
  utils/create.js
Labels: Enhancement

#575 Bug 563 : Components>Theme New >Invalid placeholder Theme New and Typeahead.
  raaghu-components/src/rds-comp-theme/rds-comp-theme.tsx
  raaghu-components/src/rds-comp-typeahead/rds-comp-typeahead.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#588 Merged Latest : Changes Merged for Latest Version from 1.1.6 to 1.1.7 in development branch
  package.json
Labels: Enhancement
