Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-02, with the labels that each got.

#8 Raaghu Elements and Components can now be created by using CLI and Remove Unwanted Code from Create js and Package js Files
  package.json
  utils/create.js
Labels: Enhancement

#11 Completed Task 9 : Implemented Layouts and Shells for different combinations in Storybook
  .storybook/main.ts
  raaghu-layouts/.gitignore
  raaghu-layouts/.npmignore
  raaghu-layouts/.npmrc
  raaghu-layouts/babel.config.js
  raaghu-layouts/generate-react-cli.json
  raaghu-layouts/package.json
  raaghu-layouts/public/accessibleTheme.png
  raaghu-layouts/public/assets/dashboard-data.png
  raaghu-layouts/public/assets/edit-pic.png
  raaghu-layouts/public/assets/profile-picture-circle.svg
  raaghu-layouts/public/assets/raaghu_icon.png
  raaghu-layouts/public/edit-pic.png
  raaghu-layouts/public/index.html
  raaghu-layouts/public/raaghu-logo.svg
  raaghu-layouts/rollup.config.js
  raaghu-layouts/src/index.ts
  raaghu-layouts/src/rds-comp-app-shell/index.ts
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell-item.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
  raaghu-layouts/src/rds-comp-layout/index.ts
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout-item.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.css
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.tsx
  raaghu-layouts/tsconfig.json
  utils/install-all.js
Labels: Enhancement

#13 Completed Task 12 : Apply raaghu-react-theme into Storybook
  package.json
Labels: Enhancement

#19 Bug 17 : Enhancement on Benefit, Breadcrumb and Button Group Elements
  raaghu-elements/src/rds-benefit/rds-benefit.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
Labels: UI Design, Bug, Enhancement

#23 Bug 16 : Enhancement in Widget , Website Matrix, Tooltip and Toast Elements
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-tooltip/rds-tooltip.stories.tsx
  raaghu-elements/src/rds-website-matrix/rds-website-matrix.stories.tsx
  raaghu-elements/src/rds-website-matrix/rds-website-matrix.tsx
  raaghu-elements/src/rds-widget/rds-widget.stories.tsx
Labels: Bug, Enhancement

#27 Bug 20, 21 and 25 : Alert Pop up, Adress input, and API Resource Basic component and Enhancement in Button, Checkbox, Counter, Button group, Date picker, Icon label, Icon and Input Group Elements
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-icon-label/rds-icon-label.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: UI Design, Bug, Enhancement

#28 Bug 26 : Elements names are not displaying after deployment on Docs
  .storybook/main.ts
  .storybook/manager-head.html
  package.json
  raaghu-components/package.json
  raaghu-elements/package.json
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-layouts/package.json
Labels: Bug, Documentation, Enhancement, Deployment, Latest Version

#29 Bug 24 : Issues on Elements Text Editor, Text area, Spinner and Video player
  .storybook/manager-head.html
  raaghu-elements/src/rds-spinner/rds-spinner.stories.tsx
  raaghu-elements/src/rds-spinner/rds-spinner.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.stories.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.stories.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
Labels: UI Design, Bug, Enhancement, Storybook

#32 Bug 31 : Enhancement in Illustration, Label and Modal Elements and Apply for Position Component
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.stories.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.stories.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/src/rds-address-detail/rds-address-detail.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-icon-label/rds-icon-label.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.stories.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.stories.tsx
  raaghu-elements/src/rds-label/rds-label.stories.tsx
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-elements/src/rds-modal/rds-modal.stories.tsx
Labels: Bug, Enhancement

#34 Bug 33 : Badge, Input and Navtab elements and Billing Address and Blog Post New component
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.stories.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.stories.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
Labels: Bug, Enhancement, Storybook

#35 Bug 30 : Testimonial , Team-member, Tag and Table Elements
  .storybook/manager-head.html
  raaghu-elements/src/rds-table/rds-table.stories.tsx
  raaghu-elements/src/rds-table/rds-table.tsx
  raaghu-elements/src/rds-tag/rds-tag.stories.tsx
  raaghu-elements/src/rds-testimonial/rds-testimonial.tsx
  raaghu-elements/src/rds-widget/rds-widget.stories.tsx
Labels: UI Design, Bug, Storybook

#37 Bug 36 : Stepper, Stat, Size and Side Nav Elements
  .storybook/manager-head.html
  raaghu-elements/src/rds-size/rds-size.css
  raaghu-elements/src/rds-size/rds-size.stories.tsx
  raaghu-elements/src/rds-stat/rds-stat.css
  raaghu-elements/src/rds-stat/rds-stat.stories.tsx
  raaghu-elements/src/rds-stat/rds-stat.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
Labels: UI Design, Bug, Enhancement, Storybook

#42 Bug 38 : Enhancement and Rendering Issue on Side navigation Element and Component
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: Bug, Enhancement, Storybook

#44 Bug 41 : Rating, Review Category, Scroll Spy, Search and Select List
  .storybook/manager-head.html
  raaghu-elements/src/rds-rating/rds-rating.css
  raaghu-elements/src/rds-rating/rds-rating.stories.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.stories.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.css
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.stories.tsx
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.tsx
  raaghu-elements/src/rds-search/rds-search.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: UI Design, Enhancement

#43 Bug 39 : Resolved Top Navigation Component Rendering and Enhancement Issues and Implement Components In Shell
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout-item.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.tsx
Labels: UI Design, Bug
