Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-10, with the labels that each got.

#751 Resolved Bug 746 : Storybook >Design System > Scroll bar alignment issue.
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
Labels: Bug

#734 Resolved Bug 731 : Storybook > Component > Feeds & Reviews > Month text is not as per wireframe
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
Labels: Bug

#730 Resolved Bug 715 : Design System > Components > Get Assistance > Default > Fill the required field. NEXT button is not enabled.
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
Labels: Bug

#720 Resolved bug 420: Storybook > Component >Login > Default > Tablet view chevron is not visible proper.
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
Labels: Bug

#722 Resolved Bug 661 : Local environment > Design system > side nav bar > setting icon> misplaced the position of setting icon
  .storybook/custom-theme.css
Labels: Bug

#721 Resolved Bug 667 : Storybook > Component > Small and Large Mabile view save and cancel button is alignment issue all component
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#687 Resolved Bug 172, 434, 654 and 658 : Missing required validation message and save button disable based on required field
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.stories.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#763 Completed Task 708 : Design System > Compare all storybook's elements, components ,charts, app shell and layout with design link and fix the differences
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-react-themes/src/styles/accordion.scss
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/colorvariables.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/default.scss
Labels: Enhancement

#729 Resolved Bug 688: Design System > Disable Save button till all mandatory fields have the value
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-page/rds-comp-page.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
Labels: Bug

#741 Resolved Bug 735: Storybook > Component > Admin Dashboard> In small mobile view Card Revenue, Sales and To do List table is not display proper.
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#761 Resolved Bug 753: Design System > Elements > Card : Minor Issues
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Enhancement

#728 Resolved Bug 522 : Storybook > Charts > Scatter Chart > Docs > Scatter Chart icon does not display issue is resolved
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.tsx
Labels: Bug

#698 Resolved Bug 678 : Counter Input issue resolved > Cannot manually enter the value & while binding the value back it is not get assigned
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Bug

#712 Task 662: Design system > Elements > Input > Tooltip > The eye icon is overlapping
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#783 Resolved Bug 722 : Design System > Input type number is not present at all in raaghu element
  raaghu-elements/src/rds-input/rds-input.stories.tsx
Labels: Bug

#799 Bug Resolved 655: Billing Address label issue resolved
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: Bug

#800 Completed Task 755 : Design System > Elements > Checkbox: Few enhancements
  raaghu-elements/src/rds-checkbox/rds-checkbox.css
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-react-themes/src/styles/checkbox.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Enhancement

#779 Enhancement 754 : Design System > Elements > Carousel : Few Enhancements
  raaghu-elements/src/rds-carousel/rds-carousel.stories.tsx
  raaghu-elements/src/rds-carousel/rds-carousel.tsx
  raaghu-react-themes/src/styles/carousel.scss
Labels: Enhancement

#797 Completed Task 785 : Design System > Elements > Enhancements in Video Player
  raaghu-elements/src/rds-video-player/rds-video-player.stories.tsx
  raaghu-elements/src/rds-video-player/rds-video-player.tsx
Labels: Enhancement

#791 Enhancement for 782: Design System > Elements > Card Enhancements
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Enhancement

#697 Resolved Bug 676 : Pagination Issues Resolved
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
Labels: Bug

#748 Resolved Bug 458 : Storybook > Alert Popup / Docs : Unable to see the fields properly
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
Labels: Bug

#738 Resolved Bug 716 : Design System > Elements Popover Docs Vertical Scrollbar Is Missing so Unable To See Popover Clearly
  raaghu-elements/src/rds-popover/rds-popover.tsx
Labels: Bug

#705 Resolved Bug 699 : Design System > Elements > Select List > Multiple > Multiple Selects are not working
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#745 Resolved Bug 695 : Storybook > Application Shells > Header > Add Layout Here is Not Display Full Screen
  raaghu-elements/src/rds-stat/rds-stat.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Bug

#702 Completed Task 519 : Storybook > Elements > Side Navigation > Side Navigation Is not as per the application
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Task

#710 Task 590 : Design System > Implement Different Types Of Alerts
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-button/rds-button.css
Labels: Task

#714 Completed Task 605 : Design System > Implement different Badge
  raaghu-elements/src/rds-badge/rds-badge.css
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Task

#817 Users/rahul/react/708/compare all storybooks elements components charts app shell layout
  raaghu-elements/libs/types/colorvariant.ts
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.css
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.css.map
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/default.scss
Labels: Enhancement

#818 Resolved Bug 812 : Storybook > Charts > Area Chart > Show error message
  raaghu-elements/src/rds-chart-area/rds-chart-area.tsx
Labels: Bug

#824 Completed Task 897 : Create common variables for bootstrap utilities.
  raaghu-react-themes/src/styles/custom.scss
Labels: Enhancement

#718 Completed Task 700 : Updated LICENSE to MIT for Design System Open Source Repo
  LICENSE
Labels: Enhancement

#829 Build Issues : Resolved Errors on Development Branch
  package.json
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.test.tsx
  raaghu-components/src/rds-comp-testimonials/rds-comp-testimonials.tsx
  raaghu-elements/__tests__/rds-carousel.test.tsx
  raaghu-elements/package.json
  raaghu-pages/src/App.tsx
  raaghu-pages/src/main.tsx
Labels: Deployment

#830 Production : Updated LICENSE to MIT from Apache 2.0
  LICENSE
Labels: Bug, Latest Version

#831 Deployment Issue : Remove Unused Import to Resolved Deployment Issue on 8.2
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Deployment

#834 Resolved Bug 833 : Design System > CSS Issue for Font Size
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#836 Merge Development : Changes from Development to Staging Branch
  raaghu-react-themes/src/styles/custom.scss
Labels: Deployment

#837 Merging Development : Moving Changes from Development 7.67 to Development 8.3 Environment
  raaghu-pages/src/main.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Deployment

#853 Completed Task 704 : Design System > Updated Readme File
  README.md
  stories/Introduction.stories.mdx
Labels: Task

#854 Completed Task 704 : Design System > Staging > Updated README.md File
  README.md
  stories/Introduction.stories.mdx
Labels: Enhancement

#855 Completed Task 704 : Design System > Production > Updated README.md File
  README.md
  stories/Introduction.stories.mdx
Labels: Enhancement

#843 Resolved Bug 667: Storybook > Component > Small and Large Mabile view save and cancel button is alignment issue all component.
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#813 Completed Task 788 : Design System > Elements > Enhancements in Text Editor
  raaghu-elements/src/rds-text-editor/rds-text-editor.stories.tsx
  raaghu-elements/src/rds-text-editor/rds-text-editor.tsx
  raaghu-react-themes/src/styles/quillEditor.scss
Labels: Enhancement

#842 Resolved Bug 753: Design System > Elements > Card : Minor Issues
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Bug

#835 Completed Task 790 : Design System > Elements > Enhancements in Tabs
  raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-react-themes/src/styles/nav-tab.scss
Labels: Enhancement

#856 Resolved Bug 844 : Design System > Components > Register Member > Default > Display twice error message.
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
Labels: Bug

#518 Completed Task 483 : Created New Grid Component for Raaghu Design System in Storybook
  .storybook/custom-theme.css
  package.json
  raaghu-components/package.json
  raaghu-components/src/rds-comp-grid/index.ts
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-elements/src/index.ts
Labels: Enhancement

#864 Completed Task 759 : Design System > Created New Chat Component
  package.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-chat/index.ts
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.stories.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Task

#872 Completed Task 794 : Design System > Elements > Enhancements in breadcrumb
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
Labels: Enhancement

#873 Completed Task 795 : Design System > Elements > Enhancements in Input
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Enhancement

#839 Resolved Bug 660 : Storybook > Components > Change Password > Default > Error Message Alignment Issue
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-react-themes/src/styles/input.scss
Labels: Bug

#887 Resolved Bug 676 : Pagination Dropdown alignment issue fixed
  raaghu-elements/src/rds-pagination/rds-pagination.stories.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-react-themes/src/styles/pagination.scss
Labels: Bug

#888 Resolved Bug 766: Elements > Button > Size not working proper selecting large size change
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-react-themes/src/styles/button.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#865 Resolved Bug 522 : Storybook >Charts>Scatter Chart>Docs> Scatter Chart icon does not display proper
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
Labels: Bug

#840 Completed Task 771 : Design System > Datepicker disbled property added
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Enhancement

#890 Resolved Bug 884 : Design System > Components > Premium Support> Default > Large mobile view card alignment is not display proper
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
Labels: Bug

#851 Completed Task 849 : Design System > Element > Progress Bar > Default : Enhancements in style
  raaghu-elements/libs/types/colorvariant.ts
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Enhancement

#891 Completed Task 781 : Design System > Version 8.3.3 > side nav bar > excess space is showing between two components
  .storybook/manager-head.html
Labels: Bug

#897 Resolved Bug 871 : Design System > Components > Required message is not displaying, & validation message alignment issue
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
Labels: Bug

#895 Resolved Bug 889 : Design System > Components > Secrets > Default > Save cancel button alignment issue
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
Labels: Bug

#896 Resolved Bug 875 : Design System > Charts > Pie chart > Unable to change the size of the pie chart, and for a circle, height and width are not required; only the radius is needed
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.stories.tsx
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.tsx
Labels: Bug

#874 Resolved Bug 861: Design System > Components > Account> Default > Captcha > Required message is not display & Alignment issue validation message Enter valid url.
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
Labels: Bug

#906 Build Issues : Resolved Errors on Development Branch
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/__tests__/rds-alert.test.tsx
Labels: Deployment

#910 Resolved Bug 870 : Design System > Components > Dynamic Entity Properties> Default> Small, Large mobile overlap Parameter.
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#904 Resolved Bug 898 : Design System > Components > Claim Type & Language > Default > After submission dropdown field does not clear
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.stories.tsx
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-language/rds-comp-language.stories.tsx
  raaghu-components/src/rds-comp-language/rds-comp-language.tsx
Labels: Bug

#912 Completed Task 592 : Design System > Implement different types of Avtars
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Enhancement

#924 Build Issues : Resolved Errors on Development Branch
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Bug

#915 Completed Task 905 : Design System > Ratings > Enhancements in Ratings
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-rating/rds-rating.css
  raaghu-elements/src/rds-rating/rds-rating.stories.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
Labels: Enhancement

#923 Resolved Bug 889 : Design System > Components > Secrets > Default > Save cancel button alignment issue.
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
Labels: Bug

#930 Completed Task 590 : Design System > Enhancement > Implement different types of Alerts (For small & large mobile views)
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-react-themes/src/styles/alert.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Enhancement

#928 Resolved Bug 884 : Design System > Components > Premium Support> Default > Large mobile view card alignment is not display proper
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
Labels: Bug

#927 Resolved Bug 926 : Storybook > Components > Summary Details > Default > Incorrect Text.
  raaghu-components/src/rds-comp-summary-details/rds-comp-summary-details.stories.tsx
Labels: Bug

#922 Resolved Bug 660 & 844 : Storybook > Components > Change Password > Default > Error message alignment issue & Design System > Components > Register Member > Default > Display twice error message
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Bug

#946 Resolved Bug 807: Design System > Charts > Polar Area Chart > Change theme and size display error massage.
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.tsx
Labels: Bug

#932 Resolved Bug 172 : Storybook > Component > Account > Default > Captcha > Issues on Account component Small, Large mobile view captcha not visible.
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
Labels: Bug

#918 Resolved Bug 746 : Design System > Version 8.3 > Scroll bar alignment issue.
  .storybook/custom-theme.css
  README.md
  stories/Introduction.mdx
Labels: Bug

#951 Resolved Bug 746 : Design System > Version 8.3 > Scroll bar alignment issue.
  README.md
  stories/Introduction.stories.mdx
Labels: Bug

#943 Resolved Bug 789 : Design System > Elements > Scrollspy > Dark theme Go Top button is not visible
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.tsx
Labels: Bug

#940 Completed Task 690: Design System > Components > Data Table > Add new component for Action
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
Labels: Enhancement

#950 Resolved Bug 792 : Design System > Elements > Stat > Advanced > Small mobile light & dark theme is not display proper
  raaghu-elements/src/rds-stat/rds-stat.css
  raaghu-elements/src/rds-stat/rds-stat.tsx
  raaghu-elements/src/rds-testimonial/rds-testimonial.stories.tsx
Labels: Bug

#948 Resolved Bug 811 : Design System > Components > Menus Directories > Default > Small Mobile view > Not able to see action menus
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#941 Resolved Bug 935 : Design System > Components > Add Member > Button alignment issue
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.tsx
  raaghu-react-themes/src/styles/offcanvas.scss
Labels: Bug

#913 Completed Bug 867 : Design System > Components > Collapsible Container > Default> UI issue and subscribe to icon color is light.
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.scss
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.style.css
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.tsx
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#917 Resolved Bug 94 : Element > Accordion > Default > Dropdown is expected to close after clicking on it
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-react-themes/src/styles/accordion.scss
Labels: Bug

#838 Completed Task 778 : Design System > Elements > Enhancements in Spinner
  raaghu-elements/src/rds-spinner/rds-spinner.stories.tsx
  raaghu-elements/src/rds-spinner/rds-spinner.tsx
Labels: Enhancement

#916 Resolved Bug 893 : Design System > Components > Tenant Dashboard > Default > Small mobile view Todo list issue
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
Labels: Bug

#961 Resolved Bug 820 : Design System > Elements > Side navigation enhancements
  raaghu-elements/src/rds-side-nav/rds-side-nav.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Bug

#970 Resolved Bug 936 : Design System > Introduction > Incorrect text
  stories/Introduction.stories.mdx
Labels: Bug

#966 Resolved Bug 963 : Design System >Elements > Alert > Default > Incorrect text
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
Labels: Bug

#953 Resolved Bug 804 : Design System > Version 8.3 > Charts > Boolean Chart > CenterIcon Icon is not change. #804
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.tsx
Labels: Bug

#964 Resolved Bug 814 : Design System > Version 8.3 > Component > Product list > Product list with Inline price > small mobile > Not able to see full image.
  raaghu-components/src/rds-comp-product-list/rds-comp-product-list.css
Labels: Bug

#974 Resolved Bug 747 : Design System > Elements > Accordion > Border is not visible proper.
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-react-themes/src/styles/accordion.scss
Labels: Bug

#947 Resolved Bug 787: Design System > Version 8.3 > Elements > Feed > For Small & large mobile view text alignment is not proper and duplicate text is displayed
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.tsx
Labels: Bug

#944 Resolved Bug 732 : Storybook > Component > Register Member >Label alignment issue.
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
Labels: Bug

#934 Completed Task 900 : Design System > Element > Create new element Time Picker
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/time-picker/index.ts
  raaghu-elements/src/time-picker/time-picker.css
  raaghu-elements/src/time-picker/time-picker.stories.tsx
  raaghu-elements/src/time-picker/time-picker.tsx
Labels: Enhancement

#933 Completed Task 788 : Design System > Elements > Enhancements in Text Editor
  raaghu-elements/src/rds-text-editor/rds-text-editor.stories.tsx
Labels: Bug

#929 Resolved Bug 871 : Design System > Components > Required message is not displaying, & validation message alignment issue,
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#952 Resolved Bug 806 : Design System > Version 8.3 >Charts > Stacked Chart > Small and large mobile view chart is not display proper.
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
Labels: Bug

#909 Resolved Bug 883: Design System > Components > Invoice Detail Receipt> Default >Dark theme text is not display proper
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#965 Resolved Bug 810 : Component > Datatable > Action button on Left side > Not able to see the 'Edit' option after hovering over the row below in the table
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.css
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
Labels: Bug

#914 Resolved Bug 866 : Design System > Components > Background Image > Default >Light theme selected text is not display Proper
  raaghu-components/src/rds-comp-background-image/rds-comp-background-image.tsx
  raaghu-components/src/rds-comp-billing/rds-comp-billing.css
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.css
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.tsx
  raaghu-components/src/rds-comp-subscription/rds-comp-subscription.css
  raaghu-components/src/rds-comp-subscription/rds-comp-subscription.tsx
Labels: Bug

#957 Completed Task 777 : Design System > Elements > Enhancements in file uploader
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-elements/__tests__/rds-fileuploader.test.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/file-uploader.scss
Labels: Enhancement

#983 Resolved Bug 862 : Design System > Components > Alert Popup > Default > Popup cancel delete button is not working
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
Labels: Bug

#986 Resolved Bug 749 : Design System > Element > Alert : Alert issues
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Enhancement

#980 Resolved Bug 969 : Design System >Elements > Payment Card > Default > Label and button alignment issue
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.tsx
  raaghu-react-themes/src/styles/card.scss
Labels: Bug

#985 Resolved Bug 810 : Component > Datatable > Action button on Left side > Not able to see the 'Edit' option after hovering over the row below in the table
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.css
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
Labels: Bug

#993 Resolved Bug 671 : Storybook > Component > Forms basic > Required message is not display
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
Labels: Bug

#998 Completed Task 742: Badge minor issue & enhancement is completed
  raaghu-elements/libs/types/colorvariant.ts
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
Labels: Enhancement

#1010 Completed Task 1001 : Elements > Enhancement > Nav Tab : Enhancements in nav tab > File Mover : Dynamic Icons > New Element > Button Grid
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.stories.tsx
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.tsx
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-button-grid/index.ts
  raaghu-elements/src/rds-button-grid/rds-button-grid.css
  raaghu-elements/src/rds-button-grid/rds-button-grid.stories.tsx
  raaghu-elements/src/rds-button-grid/rds-button-grid.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/nav-tab.scss
Labels: Enhancement

#1004 Resolved Bug 659 : Storybook > Components > Contact Us > Default > Displaying multiple error messages at the one time
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
Labels: Bug

#1012 Completed Task 981 : Design-system > Create icon for custom images for RDS icon
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
Labels: Enhancement

#939 Completed Task 938-Design system enhancement in checkbox as per new project flow
  raaghu-components/src/rds-comp-testimonials/rds-comp-testimonials.tsx
  raaghu-elements/src/rds-button-grid/rds-button-grid.stories.tsx
  raaghu-elements/src/rds-carousel/rds-carousel.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
Labels: Enhancement
