Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-09, with the labels that each got.

#626 Resolved Bug 624 : Issues of Components on Design System
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.style.css
  raaghu-components/src/rds-comp-cookies-section/rds-comp-cookies-section.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.css
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.css
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#639 Resolved Bug 591 : Design System > Implement Different Types Rounded Button True Loading Spinner is not show
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: Task

#640 Resolved Bug 275 : Component > Hide Unused components
  .storybook/manager-head.html
Labels: Bug

#642 Bug 557 : Resolved Issue Selected Dropdown Value Not Clear After Submitting.
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
Labels: Bug

#644 Resolved Bug 537 & 570 : Hand Cursor is Expected on Mouse Hover & Required Changes to Rename Permission Tree New Component
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-permission-tree-new/pemission.model.ts
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.css
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/Checkbox.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/CheckboxList.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/checkbox.module.css
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/checkboxlist.module.css
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/updateItemStates.ts
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.stories.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
Labels: Bug

#649 Bug 567 : Storybook Components Product List Images Alignment Is Not Proper
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.tsx
Labels: Bug

#646 Bug 508 & 539 : Resolved Error Message is Showing Twice in My Settings Component & Chevron is Not Visible in Select List Element
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#669 Completed Task : Resolved Compile Error
  raaghu-elements/src/index.ts
Labels: Bug

#641 Completed Task 610 : Application Shell > Implement Application Shell For Portal To Storybook In App Shell Section
  raaghu-elements/src/rds-stat/rds-stat.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Task

#657 Bug 590 : Implement Different Types of Alerts in Storybook Alert Elements
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-react-themes/src/styles/alert.scss
Labels: Bug

#680 Staging : Merge Changes from Development to Staging Branch
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.style.css
  raaghu-components/src/rds-comp-cookies-section/rds-comp-cookies-section.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-permission-tree-new/pemission.model.ts
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.css
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/Checkbox.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/CheckboxList.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/checkbox.module.css
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/checkboxlist.module.css
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree-child/updateItemStates.ts
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.stories.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.css
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.css
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-accordion/index.ts
  raaghu-elements/src/rds-accordion/rds-accordion-item.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-stat/rds-stat.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-react-themes/src/styles/alert.scss
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/responsive.scss
Labels: Enhancement, Deployment

#681 Resolved Bug : Run Time Errors
  .github/workflows/storybookreact.yml
  raaghu-elements/__tests__/rds-accordion.test.tsx
  raaghu-elements/__tests__/rds-alert.test.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Deployment

#682 Staging : Merge Changes from Development to Staging Branch
  .github/workflows/storybookreact.yml
  raaghu-elements/__tests__/rds-accordion.test.tsx
  raaghu-elements/__tests__/rds-alert.test.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Deployment

#684 Completed Task : Keeping Typescript Version Stable
  package.json
  raaghu-components/package.json
  raaghu-elements/package.json
  raaghu-layouts/package.json
Labels: Deployment

#685 Staging : Merge Changes from Development to Staging Branch
  package.json
  raaghu-components/package.json
  raaghu-elements/package.json
  raaghu-layouts/package.json
Labels: Deployment

#674 Bug 671: Storybook > Component > Forms basic > Required message is not display.
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
Labels: Bug

#664 Bug 659 : Storybook > Components > Contact Us > Default > Displaying Multiple Error Messages At the One Time
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#530 Enhancement 529 : Design System > Implement Contributor Component in Storybook
  .storybook/main.ts
  package.json
  raaghu-components/package.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-contribution/index.ts
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.css
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.stories.tsx
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx
  vite.config.ts
Labels: Enhancement

#627 Resolved Bug 625 : Design System Issues Of Elements and Charts
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-collapse/rds-collapse.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.css
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/colorvariables-semidark.scss
Labels: Bug

#672 Resolved Bug 655 : Billing Address After save clear
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
Labels: Bug

#683 Added a Contributors File on Root Directory
  Contributors.txt
Labels: Enhancement

#666 Resolved Bug : Storybook >Components >Claims > Default > Dropdown values are hidden not display proper.
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#709 Staging : Merge Changes from Development to Staging Branch
  .storybook/main.ts
  Contributors.txt
  package.json
  raaghu-components/package.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-contribution/index.ts
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.css
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.stories.tsx
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.tsx
  raaghu-elements/src/rds-collapse/rds-collapse.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-product-image/rds-product-image.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.css
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/colorvariables-semidark.scss
  raaghu-react-themes/src/styles/responsive.scss
  vite.config.ts
Labels: Deployment, Dependencies

#668 Resolved Bug : Storybook > Components > Change Password > Default > Error message alignment issue
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#673 Resolved Bug 670 : Storybook > Component > Blog Post > Small, Large Mobile view Cover Image alignment issue.
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Enhancement

#675 Resolved Bug 653 : Design system > Element > alert > With icon/ With close button/With delay Alert > Icon stroke field > Icon stroke button is not working
  raaghu-elements/src/rds-icon/rds-icon.tsx
Labels: Bug

#692 Resolved Bug 94 : Element > Accordion > Default > Dropdown is Expected to Close After Clicking on it
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
Labels: Bug

#693 Resolved Bug 679 : Design System > Scrolling Issues
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.tsx
  raaghu-react-themes/src/styles/responsive.scss
  raaghu-react-themes/src/styles/shellLayout.scss
Labels: Bug, Storybook

#723 Added Development Deployment into 'Raaghu React Storybook Deployment' Action
  .github/workflows/storybookreact.yml
Labels: Deployment

#724 Added Development Deployment into 'Raaghu React Storybook Deployment' Action
  .github/workflows/storybookreact.yml
Labels: Deployment

#725 Added Development Deployment into 'Raaghu React Storybook Deployment' Action
  .github/workflows/storybookreact.yml
Labels: Deployment
