Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-11, with the labels that each got.

#1023 Resolved Bug 789 : Design System > Elements > Scrollspy > Dark theme Go Top button is not visible.
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.css
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.tsx
Labels: Bug

#1025 Resolved Bug 807 : Design System > Charts > Polar Area Chart > Change theme and size display error massage
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.tsx
Labels: Bug

#1028 Completed Task 900 : Design System > Element > Create new element Time Picker
  raaghu-elements/src/time-picker/time-picker.stories.tsx
  raaghu-elements/src/time-picker/time-picker.tsx
Labels: Enhancement

#1034 Resolved Bug 1027 : Design System > Charts >Bubble Charts >Click on Outline to the preview & enable measures show error
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
Labels: Bug

#1030 Completed Task 592 : Design System > Implement different types of Avtaars
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Enhancement

#1015 Resolved Bug 690 : Design System > Components > Data Table > Add new component for Action
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.css
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
Labels: Bug

#1020 Resolved Bug 898 : Design System > Components > Claim Type & Language > Default > After submission dropdown field does not clear & some label changes
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-language/rds-comp-language.tsx
Labels: Bug

#1026 Resolved Bug 814 : Component > Product list > Product list with Inline price > small mobile > Not able to see full image
  raaghu-components/src/rds-comp-product-list/rds-comp-product-list.css
Labels: Bug

#1022 Resolved Bug 1005 : Design System > Components> Claims > Default > Plus button alignment issue
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
Labels: Bug

#1031 Resolved Bug 1029 : Components >Admin Dashboard > UI does not display proper.
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.css
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#1007 Completed Task 995 : Design System > Element > Add new element for header
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-header/index.ts
  raaghu-elements/src/rds-header/rds-header.css
  raaghu-elements/src/rds-header/rds-header.stories.tsx
  raaghu-elements/src/rds-header/rds-header.tsx
Labels: Bug

#1006 Completed Task 996 : Design System > Element > Enhancement in Divider
  raaghu-elements/src/rds-divider/rds-divider.stories.tsx
  raaghu-elements/src/rds-divider/rds-divider.tsx
Labels: Bug

#979 Resolved Bug 885 : Design System > Components > Payment Tenure > Default > After submitting field not clear and data is not display in action
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
Labels: Bug

#1016 Resolved Bug 991 : Design System > Components > Calendar > Small mobile view text and alignment issue
  raaghu-components/src/rds-comp-calendar/rds-comp-calendar.css
Labels: Bug

#1021 Completed Task 1014 : Design System > Elements > Text changes in element name
  raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.stories.tsx
Labels: Enhancement

#942 Completed Task 902 : Design System > Element > Create new element Truncated Text
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-truncate-text/index.ts
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.css
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.stories.tsx
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.tsx
Labels: Enhancement

#1036 Completed Task 1013 : Design System > Element > Add New Story for Stepper with checkbox
  raaghu-elements/src/rds-stepper/rds-stepper.css
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
Labels: Enhancement

#1043 Completed Task 786 : Design System > Elements > Enhancements in pagination
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-pagination/rds-pagination.stories.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-react-themes/src/styles/pagination.scss
Labels: Enhancement

#1037 Completed task 999: Design System > Component > Card : Enhancement in card view
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Enhancement

#937 Completed Task 796 : Design System > Elements > Enhancements in Review
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
Labels: Enhancement

#968 Completed Task 794 : Design System > Elements > Enhancements in breadcrumb
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.css
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Enhancement

#1045 Completed Task 796 : Design System > Elements > Enhancements in Review
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
Labels: Enhancement

#1048 Completed Task 962- Design System > Element > Create new element file uploader with avatar
  raaghu-elements/__tests__/rds-stepper.test.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Enhancement

#1062 Merging Development : Moving Changes from Development 7.6.20 to Development 8.3.5 Environment and Resolved Deployment Issue
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Deployment

#1058 Resolved bug 533 : Storybook> Click on change the theme of the preview open list select light or dark then list not close.
  .storybook/preview.ts
  .storybook/preview.tsx
Labels: Bug

#1017 Resolved Bug 972 : Components > Small, Large, Tablet view Save Cancel button alignment issue
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-client-resources/rds-comp-client-resources.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-language/rds-comp-language.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
  raaghu-components/src/rds-comp-page/rds-comp-page.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-theme/rds-comp-theme.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1056 Resolved Bug 1052 : Design System > Elements > Avatar > Default > Dark theme background does not display proper
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Bug

#1066 Merging Development : Moving Changes from Development to 8.2
  .storybook/preview.tsx
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-client-resources/rds-comp-client-resources.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-language/rds-comp-language.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-notification-settings/rds-comp-notification-settings.tsx
  raaghu-components/src/rds-comp-page/rds-comp-page.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-theme/rds-comp-theme.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Deployment

#1069 Resolved Bug 1047 : Design System > Components > Billing > Default > Controls > Add billingData display error message
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-subscription/rds-comp-subscription.tsx
Labels: Bug

#1071 Resolved Bug 1005 : Design System > Components> Claims > Default > Plus button alignment issue
  raaghu-components/src/rds-comp-claims/rds-comp-claims.css
Labels: Bug

#1072 Resolved Bug time picker element name change as per the other element format
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-time-picker/index.ts
  raaghu-elements/src/rds-time-picker/rds-time-picker.css
  raaghu-elements/src/rds-time-picker/rds-time-picker.stories.tsx
  raaghu-elements/src/rds-time-picker/rds-time-picker.tsx
  raaghu-elements/src/time-picker/index.ts
Labels: Bug

#1064 Completed Task 1046 : Design System > Element > Create new element for Skeleton.
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-skeleton/index.ts
  raaghu-elements/src/rds-skeleton/rds-skeleton.css
  raaghu-elements/src/rds-skeleton/rds-skeleton.stories.tsx
  raaghu-elements/src/rds-skeleton/rds-skeleton.tsx
Labels: Task

#1063 Resolved Bug 1051 : Design System >Accordion >Default > Dark theme chevron & border is not display proper
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1080 Completed Task 592 : Design System > Implement different types of Avatars
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Enhancement

#1073 Completed Task 740 : Design System > Component > Create new component Dialog.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-dialog/index.ts
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.css
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.stories.tsx
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.tsx
Labels: Task

#1075 Resolved Bug 845 : Design System > Components > My Settings > Default > Error message alignment issue.
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Bug

#949 Resolved Bug 695 : Storybook > Application Shells > Header > Add Layout Here is Not Display Full Screen
  raaghu-elements/src/rds-stat/rds-stat.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
Labels: Bug

#1091 Resolved task 749 : Design System > Element > Alert : Alert issues
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-react-themes/src/styles/alert.scss
Labels: Bug

#1094 Resolved bug 885 : Design System > Components > Payment Tenure > Default > After submitting field not clear and data is not display in action.
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
Labels: Bug

#1076 Resolved bug 969 : Design System >Elements > Payment Card > Default > Label and button alignment issue
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.tsx
  raaghu-react-themes/src/styles/card.scss
Labels: Bug

#1098 Resolved bug 1074 : Design System > Components > Testimonials > Default > UI issues
  raaghu-components/src/rds-comp-testimonials/rds-comp-testimonials.tsx
  raaghu-elements/src/rds-carousel/rds-carousel.tsx
Labels: Bug

#1096 Resolved bug 1090 : Design System >Elements > File Uploader > All stories multiple -true upload file display twice file
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#1095 Resolved bug 991 : Design System > Components > Calendar > Small mobile view text and alignment issue.
  raaghu-components/src/rds-comp-calendar/rds-comp-calendar.css
Labels: Bug

#1053 Resolved bug 1050 : Design System > Elements > Button > Default > All story's Height & Width issue.
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#1054 Completed Task 795 : Design System > Elements > Enhancements in Input
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Enhancement

#1100 Resolved bug 1092 : Design System > Components > Add Member > Off canvas close icon is not working.
  raaghu-elements/src/rds-icon/rds-icon.tsx
Labels: Bug

#1085 Resolved Bug 796 : Design System > Elements > Enhancements in Review
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
Labels: Enhancement

#1103 Resolved bug 1093 : Design System > Components > Features > Alignment issue.
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.css
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
Labels: Bug

#1104 Resolved bug 1101 : Design System > Components> Grid > All stories sort icon alignment issue.
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
Labels: Bug

#1108 Resolved bug 1102 : Design System > Elements > Input Group> Size control is not working proper.
  raaghu-elements/src/rds-input-group/rds-input-group.css
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
Labels: Bug

#1118 Resolved bug 1110 : Design System > Components > Feeds > Long Feed > Small mobile date & review is not display proper.
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.css
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Bug

#1033 Completed Task 590 : Design System > Enhancement > Implement different types of Alerts (For property name changes & alignment changes)
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/__tests__/rds-alert.test.tsx
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-react-themes/src/styles/alert.scss
Labels: Bug

#1125 Resolved Bug 766 : Design System > Version 8.3.3 >Elements > Button > Size not working proper selecting large size change the background icon.
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#1087 Resolved Bug 752 : Design System > Elements > Badge : Minor issues in Badge
  raaghu-elements/__tests__/rds-badge.test.tsx
  raaghu-elements/src/rds-badge/rds-badge.css
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
Labels: Bug

#1119 Resolved Bug 771 : Design System > There is no option in raaghu to disable datepicker & we are getting todays date as default value (we want as blank initially). While clearing the selected dates I am getting issue. (Image is from client site)
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-react-themes/src/styles/datePicker.scss
Labels: Bug

#1116 Completed Task 778 : Design System > Elements > Enhancements in Spinner
  raaghu-elements/src/rds-spinner/rds-spinner.tsx
Labels: Enhancement

#1000 Resolved Bug 973 : All charts height width not working
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
  raaghu-elements/src/rds-chart-area/rds-chart-area.stories.tsx
  raaghu-elements/src/rds-chart-area/rds-chart-area.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.css
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.stories.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.css
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.stories.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
  raaghu-elements/src/rds-widget/rds-widget.stories.tsx
Labels: Bug

#1060 Resolved Bug 1049 : Design System > Components > Side Navigation > Default > Image & text is not display correct
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: Bug

#1088 Resolved Bug 1014 : Design-System-Elements-Text-changes-element-name
  raaghu-elements/src/rds-illustration/rds-illustration.stories.tsx
Labels: Bug

#903 Resolved Bug 866: Design System > Components > Background Image > Default >Light theme selected text is not display Proper.
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.stories.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
Labels: Bug

#1130 Resolved Bug 852 : Design-System-Version-8-3-Side-navigation-bar-font-size-font-style-not-consistent
  .storybook/custom-theme.css
Labels: Bug

#1079 Completed Task 902 : Design System > Element > Create new element Truncated Text.
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.stories.tsx
Labels: Bug

#1082 Completed Task 786 : Design System > Elements > Enhancements in pagination
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
Labels: Enhancement

#1141 Resolved Bug : Cancel button height changed
  raaghu-elements/src/rds-input-group/rds-input-group.css
Labels: Bug

#1009 Completed Task - 775- Design System > Elements > Enhancements in Toggle
  raaghu-elements/__tests__/rds-toggle.test.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.css
  raaghu-elements/src/rds-toggle/rds-toggle.stories.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/toggle.scss
Labels: Enhancement

#1039 Completed Task 925 : Design System > Elements > Enhancements in Top Nav
  .storybook/assets/Vimeo.svg
  .storybook/assets/avatar-svg-blank.svg
  .storybook/assets/github.svg
  .storybook/assets/google.svg
  .storybook/assets/whatsapp.svg
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.css
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Enhancement

#1089 Completed Task 962 : Create new element file uploader with avatar
  raaghu-elements/__tests__/rds-chart-area.test.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Enhancement

#1135 Resolved Bug 1021 : Design System > Elements > Grid > minor issues
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
Labels: Bug

#1115 Completed Task 1114 : Design System > Components > Enhancements in Datatables > add radio button for single selection
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
Labels: Enhancement

#1070 Completed Task 1044 : Design System > Element > Create new element for Tree Structure.
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-tree-structure/index.ts
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.css
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.stories.tsx
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.tsx
Labels: Task

#1133 Resolved Bug 1120 : Design System > Alert > Multiline Alert > Link is not display properly
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Bug

#1121 Resolved Bug 1051: Design System >Accordion >Default > Dark theme chevron & border is not display proper.
  raaghu-react-themes/src/styles/accordion.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1122 Completed Task 1001: Design System > Elements > Enhancement >Nav Tab : Enhancements in nav tab > File Mover : Dynamic Icons > New Element > Button Grid
  raaghu-elements/src/rds-navtabs/rds-navtabs.stories.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/nav-tab.scss
  raaghu-react-themes/src/styles/toggle.scss
Labels: Enhancement

#1097 Completed Task 994 : Design System > Element > Banner : Add new story for header banner [New Project Flow]
  raaghu-elements/src/rds-banner/rds-banner.css
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
  raaghu-elements/src/rds-banner/rds-banner.tsx
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
  raaghu-elements/src/rds-icon/Icons.tsx
  stories/assets/raaghubannerimage.png
Labels: Enhancement

#1142 Completed Task 971 : Design System > Element > Date Picker changes
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Enhancement

#1109 Resolved bug 1106 : Design System > Components > Address Input > Default > Input box alignment issue.
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1112 Resolved bug 1107 : Design System > Components > Chat > Default > Placeholder text & icon is not centralized.
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
Labels: Bug

#1127 Resolved bug 1111 : Design System > Components > File Management Tree> Default > Vertical node does not display proper.
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1086 Completed Task 1081: Design System > Component > Skeleton : Create new component for Skeleton [New Project Flow]
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-skeleton/index.ts
  raaghu-components/src/rds-comp-skeleton/rds-comp-skeleton.css
  raaghu-components/src/rds-comp-skeleton/rds-comp-skeleton.stories.tsx
  raaghu-components/src/rds-comp-skeleton/rds-comp-skeleton.tsx
Labels: Enhancement

#1151 Resolved bug 1150 : Design System > Across application drop down issue, as data not visible in drop down
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#1139 Resolved bug 1128 : Design System > Components > Forms Email> Default > After submitting editor field are not clear.
  raaghu-components/src/rds-comp-page/rds-comp-page.tsx
  raaghu-elements/src/rds-text-editor/rds-text-editor.tsx
Labels: Bug

#1099 Resolved Bug 894 : Design System > Components > Visual Setting> Default > Small large mobile Subheader Footer overlap.
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-components/src/rds-comp-typeahead/rds-comp-typeahead.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-banner/rds-banner.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#1152 Resolved Bug : Tab component style broken
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Enhancement

#1164 Resolved Bug 1163 : Design System > Components > Edition > Button alignment issue all button
  raaghu-elements/src/rds-badge/rds-badge.css
  raaghu-elements/src/rds-badge/rds-badge.tsx
  raaghu-elements/src/rds-banner/rds-banner.css
  raaghu-elements/src/rds-banner/rds-banner.tsx
  raaghu-elements/src/rds-button/rds-button.css
Labels: Bug

#1176 Resolved Bug 795 : Design System > Elements > Enhancements in Input
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#1175 Resolved Bug 845 : Design System > Components > My Settings > Default > Error message alignment issue.
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
Labels: Bug

#1179 Resolved Bug 1167 : Design System > Elements >Dialog > Default > Size control is not working proper.
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.css
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.tsx
Labels: Bug

#1178 Completed Task 592 : Design System > Implement different types of Avtaars
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Enhancement

#1160 Resolved Bug 866 : Design System > Components > Background Image > Default >Light theme selected text is not display Proper
  raaghu-components/src/rds-comp-background-image/rds-comp-background-image.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#1162 Completed Task 989 : Design System > Element > AI Prompt for new project flow
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
Labels: Bug

#1165 Resolved Bug 1021 : Design System > Elements > Grid > minor issues
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
Labels: Bug

#1181 Resolved Bug 1180 : Design System > Truncated Text & Time Picker > Default > Code structure changes as per other existing stories
  raaghu-elements/src/rds-time-picker/rds-time-picker.stories.tsx
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.stories.tsx
Labels: Bug

#1157 Resolved Task 997 : Design System > Element > Button : Enhancement in button [New Project]
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Enhancement

#911 Completed Task 784 : Design System > Elements > Enhancements in Action Button/Dropdown
  raaghu-elements/src/rds-dropdown/rds-dropdown.css
  raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Enhancement

#1177 Resolved Task 1055 : Design System > Component > Create New Component For Transfer List And Aspect Ratio
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-transfer-list/index.ts
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.css
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.stories.tsx
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.tsx
Labels: Task

#1173 Resolved Bug 752 : Design System > Elements > Badge : Minor issues in Badge
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
Labels: Bug

#1172 Completed Task 1146 : Design System > Component >enhancement of the alert popup and in otp input
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.stories.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-components/src/rds-comp-otpinput/styles.css
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Enhancement

#1161 Resolved bug 969 : Design System >Elements > Payment Card > Default > Label and button alignment issue.
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#1068 Resolved bug 1065 : Components > Contact Us > Default > Send message button alignment issue
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-react-themes/src/styles/card.scss
Labels: Bug

#1170 Resolved bug 1128 : Design System > Components > Forms Email> Default > After submitting editor field are not clear.
  raaghu-components/src/rds-comp-page/rds-comp-page.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
Labels: Bug

#1186 Completed Task 1185 : Design System > Remove Scripts and Files
  package.json
  utils/create.js
Labels: Enhancement

#1183 Resolved Bug 894 : Design System > Components > Visual Setting> Default > Small large mobile Sub header Footer overlap
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
Labels: Bug

#1184 Resolved Bug 973 : All charts height width not working
  raaghu-elements/src/rds-chart-area/rds-chart-area.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.stories.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
Labels: Bug

#1188 Resolved bug 1187 : Design System > Resolved build issue.
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.css
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.stories.tsx
Labels: Bug
