Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-05, with the labels that each got.

#298 Bug 305 : Introduction > Responsiveness Issue for Features and Learn More Section
  package.json
  stories/Introduction.stories.mdx
Labels: Bug

#301 Bug 297 : Resolved Issues on Badge Element
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
Labels: Bug

#303 Bug 299 : Resolved Issues on Dropdown List Element
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#309 Bug 300: Resolved Issue on Component File Uploader Reduce Placeholder Size.
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#314 Merged Development : Changes Merged from Development to Production for Latest Version from 1.0.9 to 1.0.10
  package.json
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.stories.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-list-group/rds-list-group.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  stories/Introduction.stories.mdx
Labels: Latest Version, Storybook, NPM Package

#322 Enhancement : Integrate Raaghu Pages Getting Started Section Single Page
  package.json
  raaghu-elements/src/rds-card-detail/rds-card-detail.styled.ts
  raaghu-elements/src/rds-map/rds-map.styled.ts
  raaghu-elements/src/rds-map/rds-map.tsx
  raaghu-pages/.eslintrc.cjs
  raaghu-pages/.gitignore
  raaghu-pages/index.html
  raaghu-pages/package.json
  raaghu-pages/public/vite.svg
  raaghu-pages/src/App.css
  raaghu-pages/src/App.tsx
  raaghu-pages/src/assets/react.svg
  raaghu-pages/src/index.css
  raaghu-pages/src/main.tsx
  raaghu-pages/src/vite-env.d.ts
  raaghu-pages/tsconfig.json
  raaghu-pages/tsconfig.node.json
  raaghu-pages/vite.config.ts
  utils/install-all.js
Labels: Enhancement

#324 Merged Development : Changes Merged from Development to Production for Latest Version from 1.0.9 to 1.0.10
  package.json
  raaghu-elements/src/rds-card-detail/rds-card-detail.styled.ts
  raaghu-elements/src/rds-map/rds-map.styled.ts
  raaghu-elements/src/rds-map/rds-map.tsx
  raaghu-pages/.eslintrc.cjs
  raaghu-pages/.gitignore
  raaghu-pages/index.html
  raaghu-pages/package.json
  raaghu-pages/public/vite.svg
  raaghu-pages/src/App.css
  raaghu-pages/src/App.tsx
  raaghu-pages/src/assets/react.svg
  raaghu-pages/src/index.css
  raaghu-pages/src/main.tsx
  raaghu-pages/src/vite-env.d.ts
  raaghu-pages/tsconfig.json
  raaghu-pages/tsconfig.node.json
  raaghu-pages/vite.config.ts
  utils/install-all.js
Labels: Latest Version, Storybook, NPM Package

#331 Merged Production : Changes Merged from Production to Creator for Latest Version
  package.json
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.stories.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.stories.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.tsx
  raaghu-elements/src/rds-card-detail/rds-card-detail.styled.ts
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-list-group/rds-list-group.tsx
  raaghu-elements/src/rds-map/rds-map.styled.ts
  raaghu-elements/src/rds-map/rds-map.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-pages/.eslintrc.cjs
  raaghu-pages/.gitignore
  raaghu-pages/index.html
  raaghu-pages/package.json
  raaghu-pages/public/vite.svg
  raaghu-pages/src/App.css
  raaghu-pages/src/App.tsx
  raaghu-pages/src/assets/react.svg
  raaghu-pages/src/index.css
  raaghu-pages/src/main.tsx
  raaghu-pages/src/vite-env.d.ts
  raaghu-pages/tsconfig.json
  raaghu-pages/tsconfig.node.json
  raaghu-pages/vite.config.ts
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  stories/Introduction.stories.mdx
  utils/install-all.js
Labels: Latest Version

#311 Bug 287 : Resolved Issues on Offcanvas Element
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: Bug

#318 Bug 263 : Resolved Issues on Dynamic Entity Properties Component
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#319 Bug 308 : Resolved Issue on Component Properties Increasing Spacing and Reduce Buttons Size
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
Labels: Bug

#320 Bug 306 : Resolved Issue on Component New Claim Types Chevron is Missing and field is Fluctuating
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#321 Bug 317 : Resolved Issue on Component Login Attempts Pagination is Missing
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Bug

#326 Bug 310 : Resolved Issue on Organization Tree Component
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.css
Labels: Bug

#328 Bug 315 : Resolved Issue on Information Component
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
Labels: Bug

#330 Bug 325 : Resolved Issue on Components Sorting Option is not Working for Status Column
  raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.stories.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.stories.tsx
  raaghu-components/src/rds-comp-user-table/rds-comp-user-table.stories.tsx
Labels: Bug

#329 Bug 313 : Resolved Issue on Pages Component
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
Labels: Bug

#332 Bug 245 : Resolved Issue on Remove Scrollbar from all Components
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.stories.tsx
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.stories.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-elements/src/rds-tag/rds-tag.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#335 Complete Task : Update version 1.0.10 to 1.1.0
  LICENSE
  package.json
  raaghu-react-themes/src/styles/custom.scss
Labels: Task, Enhancement, NPM Package

#336 Merged Development : Changes Merged from Development to Production for Latest Version from 1.0.10 to 1.1.0
  LICENSE
  package.json
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.stories.tsx
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.stories.tsx
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.css
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.stories.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.stories.tsx
  raaghu-components/src/rds-comp-user-table/rds-comp-user-table.stories.tsx
  raaghu-elements/src/rds-checkbox-parent-child/rds-checkbox-parent-child.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-tag/rds-tag.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Latest Version, Storybook, NPM Package

#333 Bug 316 : Resolved Issues on Integration Component
  raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
Labels: Bug

#334 Bug 327 : Resolved Issue on Component Benefit Card Alignment Issue
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.stories.tsx
Labels: Bug

#337 Bug 164 : Resolved Issues on User Basics Component
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
Labels: Bug

#338 Bug 257 : Resolved Issue on Save and Cancel Button
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Bug

#339 Bug 246 : Resolved Chevron Issue on Application Work Flows Component
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
Labels: Bug

#340 Bug 230 : Resolved Issue on Component Validation Issues
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#341 Bug 263 : Resolved Issues on Dynamic Entity Property Component
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#342 Bug 278 : Resolved Issue on Permission Tree New Component
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
Labels: Bug

#351 Bug 344 : Resolved Chevron Issue on Tenant Register Component
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
Labels: Bug

#353 Bug 352: Resolved Issue on Component Tenant Information Database URL not Getting Cleared.
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
Labels: Bug

#354 Complete Bug : Update storybook version 1.1.0 to 1.1.1
  package.json
Labels: Bug, Latest Version

#357 Merged Development : Changes Merged from Development to Production for Latest Version from 1.1.0 to 1.1.1
  package.json
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.stories.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-integration/rds-comp-integration.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-components/src/rds-comp-theme-new/rds-comp-theme-new.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Enhancement

#358 Bug 346 : Resolved Issue on Payment Tenure Component
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
Labels: Bug

#360 Bug 345 : Resolved Issue on Shopping Cart Component
  raaghu-components/src/rds-comp-shopping-cart/rds-comp-shopping-cart.tsx
Labels: Bug

#361 Bug 348 : Resolved Issue on Reduce Buttons Sizes of All the Components
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.stories.tsx
  raaghu-components/src/rds-comp-typeahead/rds-comp-typeahead.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
Labels: Bug

#363 Bug 362 : Resolved Issue on Components Billing Download Icon Alignment Issue
  raaghu-components/src/rds-comp-billing/rds-comp-billing.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-react-themes/src/styles/accordion.scss
Labels: Bug

#372 Task 371 : Added New Component in Storybook
  .storybook/assets/offcanvas-invite.svg
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-add-member/index.ts
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.stories.tsx
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.styled.ts
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.test.tsx
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.tsx
Labels: Task

#366 Task 364 : OTP Input Field with Dynamic Inputs and 2 Shapes (Square and Circle)
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-otpinput/index.ts
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.stories.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.styled.ts
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.test.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-components/src/rds-comp-otpinput/styles.css
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Task

#367 Bug 365 : Resolve Issue on Components Login After Submitting Field is Not Clear
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.stories.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
Labels: Bug

#370 Bug 368 : Resolved Issue on Components Api Scope Resource After Submitting, Data is not Display in Action
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.stories.tsx
  raaghu-components/src/rds-comp-api-scope-resource/rds-comp-api-scope-resource.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#373 Bug 307: Resolve issue on Component Profile edit Image is missing
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#374 Bug 349: Resolved Issue on Component Page not found.
  raaghu-components/src/rds-comp-page-not-found/rds-comp-page-not-found.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-list-group/rds-list-group.tsx
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
Labels: Bug

#376 Complete Task : Update version of raaghu react 1.1.1 to 1.1.2
  package.json
Labels: Enhancement, NPM Package

#375 Merged Development : Changes Merged from Development to Production for Latest Version from 1.1.1 to 1.1.2
  .storybook/assets/offcanvas-invite.svg
  package.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.stories.tsx
  raaghu-components/src/rds-comp-add-member/index.ts
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.stories.tsx
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.styled.ts
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.test.tsx
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.tsx
  raaghu-components/src/rds-comp-api-scope-resource/rds-comp-api-scope-resource.tsx
  raaghu-components/src/rds-comp-billing/rds-comp-billing.stories.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-new-features/rds-comp-new-features.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-components/src/rds-comp-otpinput/index.ts
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.stories.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.styled.ts
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.test.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-components/src/rds-comp-otpinput/styles.css
  raaghu-components/src/rds-comp-page-not-found/rds-comp-page-not-found.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.stories.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-profile-edit/rds-comp-profile-edit.tsx
  raaghu-components/src/rds-comp-properties-new/rds-comp-properties-new.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-components/src/rds-comp-shopping-cart/rds-comp-shopping-cart.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.stories.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-components/src/rds-comp-typeahead/rds-comp-typeahead.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-list-group/rds-list-group.tsx
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-popular-page/rds-popular-page.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/accordion.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/selectlist.scss
Labels: Deployment, Latest Version

#378 Task 377 : Move Assistance component from Portal to Storybook
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-assistance/index.ts
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.stories.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.test.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
Labels: Task

#380 Task 377 : Add New Register Member Component on Storybook
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-register-member/index.ts
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.stories.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.test.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
Labels: Task

#381 Bug 379 : Resolved Issue on Components Polls Question Ones Click Check Box not Selected
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.stories.tsx
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.stories.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Bug

#383 Task 377 : Add Copy Text Component on Storybook
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-copy-text/index.ts
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.stories.tsx
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.styled.ts
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.test.tsx
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.tsx
Labels: Task

#384 Task 377 : Added New Component Get Assistance on Storybook
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-get-assistance/index.ts
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.stories.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.styled.ts
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.test.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
Labels: Task

#385 Task 377 : Added Invoice Detail Receipt Component on Storybook
  package.json
  raaghu-components/public/WAi-logo.png
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-invoice-detail-receipt/index.ts
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.stories.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.test.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.tsx
Labels: Task

#386 Task 377 : Added new component Order Confirmation on Storybook
  raaghu-components/public/payment-inprogress.mp4
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-order-confirmation/index.ts
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.stories.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.test.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.tsx
Labels: Task

#389 Resolved Bug 390 : Build Issue for Version 1.1.3
  package.json
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.styled.ts
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.styled.ts
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-elements/__tests__/rds-radio-button.test.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Latest Version, NPM Package

#391 Merged Development : Changes Merged from Development to Production for Latest Version from 1.1.2 to 1.1.3
  package.json
  raaghu-components/public/WAi-logo.png
  raaghu-components/public/payment-inprogress.mp4
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.stories.tsx
  raaghu-components/src/rds-comp-assistance/index.ts
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.stories.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.test.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-copy-text/index.ts
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.stories.tsx
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.styled.ts
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.test.tsx
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-directory-list/rds-comp-directory-list.stories.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.tsx
  raaghu-components/src/rds-comp-get-assistance/index.ts
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.stories.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.test.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/index.ts
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.stories.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.test.tsx
  raaghu-components/src/rds-comp-invoice-detail-receipt/rds-comp-invoice-detail-receipt.tsx
  raaghu-components/src/rds-comp-order-confirmation/index.ts
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.stories.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.test.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.tsx
  raaghu-components/src/rds-comp-payment-card/index.ts
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.stories.tsx
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.test.tsx
  raaghu-components/src/rds-comp-payment-card/rds-comp-payment-card.tsx
  raaghu-components/src/rds-comp-payment-detail/rds-comp-payment-detail.tsx
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-register-member/index.ts
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.stories.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.test.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-elements/__tests__/rds-radio-button.test.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Storybook, NPM Package
