Repository Wai-Technologies/raaghu-react, pull requests merged in 2024-03, with the labels that each got.

#45 Bug 36 : Resolved Issue on Side Nav Element, Component and Application Shell
  .storybook/main.ts
  .storybook/manager-head.html
  package.json
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.stories.tsx
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Bug

#47 Bug 46 : Enhancement in Banner, Card Detail, Benefit and Checkbox Group Elements
  .storybook/manager-head.html
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.css
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.stories.tsx
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.tsx
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.stories.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
  raaghu-react-themes/src/styles/button.scss
Labels: Bug

#48 Enhancement 49 : Changes to Names for Application Shell and Layouts
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
Labels: Enhancement

#54 Enhancement 53 : Code Refactoring and Code Indentation For Application Shells, Layout, Charts and Maps
  .github/workflows/development_storybookreact.yml
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.stories.tsx
  raaghu-elements/src/rds-chart-area/rds-chart-area.stories.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.tsx
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.stories.tsx
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.stories.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.stories.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.css
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.tsx
Labels: Enhancement

#55 Enhancement : Added Release Related Code to Elements, Components and Layouts package.json Files
  .github/workflows/npm_publish.yml
  package.json
  raaghu-components/package.json
  raaghu-elements/package.json
  raaghu-layouts/package.json
Labels: Enhancement

#56 Enhancement 52 : Code Refactoring and Code Indentation For Components
  .storybook/manager-head.html
Labels: Enhancement

#57 Enhancement : Changes on NPM Actions for Deployment
  .github/workflows/npm_publish.yml
Labels: Enhancement

#58 Enhancement : Added Main to package.json for Reference of Modules for Release, Version Upgrade from 1.0.1 to 1.0.2, and Other Changes
  package.json
  static/Mask Group 3.png
  static/abpio.png
  static/aspnetzero.png
  static/product_list_with_title.png
Labels: Enhancement

#59 Merged Development : Changes Merged from Development to Production for Latest Version from 1.0.0 to 1.0.2
  package.json
  static/Mask Group 3.png
  static/abpio.png
  static/aspnetzero.png
  static/product_list_with_title.png
Labels: Enhancement

#69 Bug 68 : Resolved Button Rendering Issue on Storybook
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-modal/rds-modal.stories.tsx
  raaghu-elements/src/rds-rating/rds-rating.css
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-size/rds-size.stories.tsx
  raaghu-elements/src/rds-spinner/rds-spinner.stories.tsx
  raaghu-elements/src/rds-stat/rds-stat.stories.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-table/rds-table.stories.tsx
  raaghu-elements/src/rds-table/rds-table.tsx
  raaghu-elements/src/rds-tag/rds-tag.stories.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.stories.tsx
  raaghu-elements/src/rds-testimonial/rds-testimonial.stories.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.stories.tsx
  raaghu-elements/src/rds-text-editor/rds-text-editor.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-tooltip/rds-tooltip.stories.tsx
  raaghu-elements/src/rds-video-player/rds-video-player.stories.tsx
  raaghu-elements/src/rds-website-matrix/rds-website-matrix.stories.tsx
  raaghu-elements/src/rds-widget/rds-widget.stories.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: Bug

#64 Bug 63 : Enhancement on Popover, Popular Page, Price, Progress Bar and Radio Button Elements
  .storybook/manager-head.html
  raaghu-elements/src/rds-popover/rds-popover.stories.tsx
  raaghu-elements/src/rds-popover/rds-popover.tsx
  raaghu-elements/src/rds-popular-page/rds-popular-page.stories.tsx
  raaghu-elements/src/rds-popular-page/rds-popular-page.tsx
  raaghu-elements/src/rds-price/rds-price.stories.tsx
  raaghu-elements/src/rds-price/rds-price.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.stories.tsx
Labels: Bug

#66 Bug 65 : Enhancement on Range, Offcanvas, Navbar, Like Dislike, Double Range, Collapse and Color Picker Elements
  .storybook/manager-head.html
  raaghu-elements/src/rds-benefit/rds-benefit.stories.tsx
  raaghu-elements/src/rds-benefit/rds-benefit.tsx
  raaghu-elements/src/rds-collapse/rds-collapse.stories.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.stories.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.stories.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.stories.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
  raaghu-elements/src/rds-navbar/rds-navbar.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-elements/src/rds-range/rds-range.stories.tsx
  raaghu-elements/src/rds-range/rds-range.tsx
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.stories.tsx
  raaghu-elements/src/rds-search/rds-search.stories.tsx
Labels: Bug

#70 Bug 67 : Enhancement in Feature List, Feed and List Group Elements
  raaghu-elements/src/rds-feature-list/rds-feature-list.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.styled.css
  raaghu-elements/src/rds-feed/rds-feed.styled.ts
  raaghu-elements/src/rds-feed/rds-feed.tsx
  raaghu-elements/src/rds-list-group/rds-list-group.stories.tsx
Labels: Bug

#72 Bug 71 : Enhancement in Notification, Pagination, Product Image and Review Category Elements
  .storybook/manager-head.html
  README.md
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.stories.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-elements/src/rds-product-image/rds-product-image.stories.tsx
  raaghu-elements/src/rds-product-image/rds-product-image.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
Labels: Bug

#76 Bug 75 : Enhancement in Card, Rating and Review Category Elements
  .storybook/manager-head.html
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-rating/rds-rating.stories.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.css
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
Labels: Bug

#82 Resolved Bug : Remove the Footer Text from Notification Element
  raaghu-elements/__tests__/rds-notification.test.tsx
Labels: Bug, Storybook

#83 Merged Development : Changes Merged from Development to Production for Latest Version from 1.0.2 to 1.0.3 (Resolved Issues)
  raaghu-elements/__tests__/rds-notification.test.tsx
Labels: Bug

#84 Resolved Bug : Npm Package Build Issue
  package.json
Labels: Bug

#86 Enhancement : Banner Issue for Height for Light and Dark Mode
  README.md
Labels: Enhancement

#90 Enhancement : Enhancement in Storybook Component
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.stories.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-elements/src/rds-tooltip/rds-tooltip.tsx
Labels: Enhancement

#91 Task 89 : Adding Payment Summary, Payment Summary, Widget and Tab Group Elements into Storybook
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-payment-summary/index.ts
  raaghu-elements/src/rds-payment-summary/rds-payment-summary.scss
  raaghu-elements/src/rds-payment-summary/rds-payment-summary.stories.tsx
  raaghu-elements/src/rds-payment-summary/rds-payment-summary.tsx
  raaghu-elements/src/rds-plan-discount/index.ts
  raaghu-elements/src/rds-plan-discount/rds-plan-discount.scss
  raaghu-elements/src/rds-plan-discount/rds-plan-discount.stories.tsx
  raaghu-elements/src/rds-plan-discount/rds-plan-discount.tsx
  raaghu-elements/src/rds-tab-group/index.ts
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
  raaghu-elements/src/rds-widget-portal/index.ts
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.scss
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.stories.tsx
  raaghu-elements/src/rds-widget-portal/rds-widget-portal.tsx
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/default.scss
  raaghu-react-themes/src/styles/tabGroup.scss
Labels: Task, Portal

#92 Enhancement 92 : Enhancement in Benefit, Blog Post New , Blog Post and Cache Component
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-background-image/rds-comp-background-image.tsx
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.stories.tsx
  raaghu-components/src/rds-comp-billing/rds-comp-billing.stories.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.stories.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.stories.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.tsx
  raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-cookies-section/rds-comp-cookies-section.tsx
  raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.css
  raaghu-components/src/rds-comp-delivery-method/rds-comp-delivery-method.tsx
  raaghu-elements/src/rds-benefit/rds-benefit.stories.tsx
  raaghu-elements/src/rds-benefit/rds-benefit.tsx
  raaghu-elements/src/rds-size/rds-size.css
Labels: Enhancement

#103 Bug 88 : Resolved Issue on Dropdown List and File Uploader Elements
  .storybook/assets/raaghu-logo.svg
  .storybook/customTheme.js
  .storybook/manager-head.html
  README.md
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#105 Bug 95 : Resolved Position Control Issue on Banner Element
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
Labels: Bug

#104 Bug 96 : Resolved SSO icon rendering Issue on Login Component
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#110 Bug 97, 98 and 99 : Resolved Button Rendering Issue on New Role, My Settings and Identity Ldap Management components
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#111 Bug 109 : Resolved Bug on Components Download Collection, Dynamic Properties, Edit Language Text, Edition Information, Edition List, Edition New Basic, and more
  package.json
  raaghu-components/src/rds-comp-account/rds-comp-account.stories.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.stories.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.stories.tsx
  raaghu-components/src/rds-comp-client-resources/rds-comp-client-resources.stories.tsx
  raaghu-components/src/rds-comp-client-resources/rds-comp-client-resources.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-edit-language-text/rds-comp-edit-language-text.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-edition-list/rds-comp-edition-list.stories.tsx
  raaghu-components/src/rds-comp-edition-new-basic/rds-comp-edition-new-basic.stories.tsx
  raaghu-components/src/rds-comp-edition-new-basic/rds-comp-edition-new-basic.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.stories.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-react-themes/src/styles/card.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#112 Bug 107 : Resolved Custom Arrow Alignment Issue on Date Picker
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Bug

#113 Bug 106 : Resolved Issue on Element Radio Button Unable to Select.
  README.md
  raaghu-elements/src/rds-radio-button/rds-radio-button.stories.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Bug

#118 Bug 101 : Resolved Issue of Remove ABP Keys from Profile Picture Component.
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
Labels: Bug

#120 Bug 119 : Resolved Enhancement Issues on Components
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.stories.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-components/src/rds-comp-website-log/rds-comp-website-log.stories.tsx
  raaghu-components/src/rds-comp-website-log/rds-comp-website-log.tsx
Labels: Bug

#121 Enhancement : Enhancement In Component
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-faq/rds-comp-faq.stories.tsx
  raaghu-components/src/rds-comp-faq/rds-comp-faq.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
Labels: Enhancement

#124 Enhancement 127 : Enhancement In Component Linked-account ,Login, My-settings, New-claims, New-language, New-menu
  .storybook/custom-theme.css
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.stories.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.css
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.stories.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-components/src/rds-comp-my-settings/rds-comp-my-settings.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-page-not-found/rds-comp-page-not-found.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
Labels: Enhancement

#125 Bug 122 : Resolved Issue on Components
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-api-scope-basic-resource/rds-comp-api-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-billing-address/rds-comp-billing-address.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-change-password/rds-comp-change-password.tsx
  raaghu-components/src/rds-comp-change-user-password/rds-comp-change-user-password.tsx
  raaghu-components/src/rds-comp-claim/rds-comp-claim.tsx
  raaghu-components/src/rds-comp-subscription/rds-comp-subscription.stories.tsx
  raaghu-components/src/rds-comp-teams/rds-comp-teams.stories.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.stories.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.stories.ts
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
  raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.stories.tsx
  raaghu-components/src/rds-comp-user-permission-new/rds-comp-user-permission-new.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.stories.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.tsx
  raaghu-components/src/rds-comp-user-table/rds-comp-user-table.css
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#129 Bug #123 : Restructuring for Button Components rendering issues resolved.
  raaghu-components/src/rds-comp-new-menu/rds-comp-new-menu.tsx
  raaghu-components/src/rds-comp-new-role/rds-comp-new-role.tsx
  raaghu-components/src/rds-comp-newPage/rds-comp-newPage.tsx
  raaghu-components/src/rds-comp-order-summary/rds-comp-order-summary.tsx
Labels: Bug

#130 Bug 123: Resolved Issue on Components Restructuring for Button Rendering Issue.
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-linked-account/rds-comp-linked-account.tsx
Labels: Bug

#131 Bug 126 : Resolved Issue on Components
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.stories.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.stories.tsx
  raaghu-components/src/rds-comp-secrets/rds-comp-secrets.tsx
  raaghu-components/src/rds-comp-security-logs/rds-comp-security-logs.stories.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.stories.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.stories.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.stories.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
Labels: Bug

#133 Bug 123 : Restructuring for Button Component rendering issue.
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-set-password/rds-comp-set-password.tsx
Labels: Bug

#134 Bug 123 : Resolved Issue on Restructuring Component for Button Rendering Issue.
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-components/src/rds-comp-new-claim-type/rds-comp-new-claim-type.tsx
  raaghu-components/src/rds-comp-new-language/rds-comp-new-language.tsx
  raaghu-components/src/rds-comp-user-claims/rds-comp-user-claims.tsx
  raaghu-components/src/rds-comp-user-delegations/rds-comp-user-delegations.tsx
Labels: Bug

#137 Bug 123: Resolved Issue on Restructuring Button Component Rendering Issue
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
Labels: Bug

#138 Bug 123 : Enhancement of Button Rendering Issue
  raaghu-components/src/rds-comp-client-resources/rds-comp-client-resources.tsx
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-shipping-address/rds-comp-shipping-address.tsx
Labels: Bug

#139 Bug 135 : Resolved Rendering and UI Issue on Components
  .storybook/assets/Theme_Dark.png
  .storybook/assets/Theme_Light.png
  .storybook/assets/Theme_SemiDark.png
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.stories.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.stories.tsx
  raaghu-components/src/rds-comp-cookies-section/rds-comp-cookies-section.stories.tsx
  raaghu-components/src/rds-comp-cookies-section/rds-comp-cookies-section.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.stories.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.stories.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.css
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.stories.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.styled.ts
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.module.css
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.stories.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.stories.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
Labels: Bug
