Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-09, with the labels that each got.

#2539 Resolved issue 2413: Design System > MUI > Creating Components from Design Kit
  raaghu-components/rds-comp-details-pane/details-pane-components.tsx
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.scss
  raaghu-components/rds-comp-map/rds-comp-map.stories.tsx
Labels: Bug

#2541 Resolved Bugs : Fixed UI, Styling and Control issue on element.
  raaghu-elements/rds-box/rds-box.stories.tsx
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.stories.tsx
  raaghu-elements/rds-button/rds-button.stories.tsx
Labels: Bug

#2546 Resolved Bug : Fixed control issue on element.
  raaghu-elements/rds-icon-button/rds-icon-button.scss
  raaghu-elements/rds-icon-button/rds-icon-button.tsx
Labels: Bug

#2564 Resolved Bug 2550 : Design System > Skeleton > Control not working as per figma if not required remove it or add that control for respective story
  raaghu-elements/rds-skeleton/rds-skeleton.stories.tsx
  raaghu-elements/rds-skeleton/rds-skeleton.tsx
Labels: Bug

#2566 Resolved Bug 2548: Design System > Kanban Board > Not as per wireframe many issues on this.
  raaghu-components/rds-comp-kanban-board/kanban-board-helpers.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.scss
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.stories.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.tsx
  raaghu-elements/rds-avatar/rds-avatar.tsx
Labels: Bug

#2558 Resolved Bug 2554 : Design System > Progress > Small and large mobile screen not working properly
  raaghu-elements/rds-progress/rds-progress.scss
  raaghu-elements/rds-progress/rds-progress.stories.tsx
Labels: Bug

#2565 Resolved Bug 2556 : Design System > Range > Small screen mobile size is not working and it's not clickable
  raaghu-elements/rds-range/rds-range.scss
  raaghu-elements/rds-range/rds-range.tsx
Labels: Bug

#2590 Resolved Bug 2559 : Design System > Typography > There is unwanted controls are there if not required remove it.
  raaghu-elements/rds-typography/rds-typography.stories.tsx
Labels: Bug

#2589 Resolved Bug 2552 : Design System > Tabs > Control is not working as per figma.
  raaghu-elements/rds-tabs/rds-tabs.scss
  raaghu-elements/rds-tabs/rds-tabs.stories.tsx
Labels: Bug

#2600 Resolve Bug 2596 and 2597 : Design System > Reviews > Avatar is not looking circular and Design System > Spinner > width and height control is not working
  raaghu-components/rds-comp-reviews/rds-comp-review-styles.tsx
  raaghu-components/rds-comp-reviews/rds-comp-reviews.scss
  raaghu-components/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/rds-comp-spinner/rds-comp-spinner.stories.tsx
  raaghu-elements/rds-avatar/rds-avatar.scss
Labels: Bug

#2598 Reoslved Bug 2557 : Counter Not Show In Proper In Small And Large Screen
  raaghu-elements/rds-counter/rds-counter.scss
  raaghu-elements/rds-counter/rds-counter.stories.tsx
Labels: Bug

#2613 Resolved Bug 2611: Design System > Badge > small size inside badge number is not looking center of the badge
  raaghu-elements/rds-badge/rds-badge.scss
  raaghu-elements/rds-badge/rds-badge.stories.tsx
Labels: Bug

#2615 Resolved Bug 2599 : Design System > Time picker > Clock icon is not there
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.scss
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.tsx
Labels: Bug

#2619 Resolved Bug 2614 : Contribution Not Show Proper In Small And Large Screen
  raaghu-components/rds-comp-contribution/rds-comp-contribution.scss
  raaghu-components/rds-comp-contribution/rds-comp-contribution.tsx
Labels: Bug

#2649 Resolved Bugs 2587 : Design System > Removed unused control across the application.
  raaghu-components/rds-comp-chart-gauge/rds-comp-chart-gauge.stories.tsx
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.stories.tsx
  raaghu-components/rds-comp-emoji-generator/rds-comp-emoji-generator.stories.tsx
  raaghu-components/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.stories.tsx
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.stories.tsx
  raaghu-components/rds-comp-toast/rds-comp-toast.stories.tsx
  raaghu-elements/rds-alert/rds-alert.stories.tsx
  raaghu-elements/rds-app-bar/rds-app-bar.stories.tsx
  raaghu-elements/rds-autocomplete/rds-autocomplete.stories.tsx
  raaghu-elements/rds-badge/rds-badge.stories.tsx
  raaghu-elements/rds-card/rds-card.stories.tsx
  raaghu-elements/rds-counter/rds-counter.stories.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/rds-menu/rds-menu.stories.tsx
  raaghu-elements/rds-modal/rds-modal.stories.tsx
  raaghu-elements/rds-multi-level-menu/rds-multi-level-menu.stories.tsx
  raaghu-elements/rds-radio/rds-radio.stories.tsx
  raaghu-elements/rds-range/rds-range.stories.tsx
  raaghu-elements/rds-rating/rds-rating.stories.tsx
  raaghu-elements/rds-sidebar/rds-sidebar.stories.tsx
  raaghu-elements/rds-skeleton/rds-skeleton.stories.tsx
  raaghu-elements/rds-tooltip/rds-tooltip.stories.tsx
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.stories.tsx
Labels: Bug

#2666 Resolved Bug 2659 : Design System > Chat > When all screen size is l the input field is not looking as expected
  raaghu-components/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/rds-comp-chat/rds-comp-chat.tsx
Labels: Bug

#2651 Resolved Bug 2636 : Color Picker Responsiveness Issue.
  raaghu-components/rds-comp-color-picker/color-picker-components.tsx
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.scss
Labels: Bug

#2663 Resolved issue 2610: File Uploader> When mode is standard selected file there is no option for remove that file if I want to remove.
  raaghu-elements/rds-file-uploader/RdsFileUploaderComponents.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.stories.tsx
Labels: Bug

#2650 Resolved issue 2622: Design System > Alert > small and large screen size not working properly.
  raaghu-elements/rds-alert/rds-alert.scss
  raaghu-elements/rds-alert/rds-alert.stories.tsx
  raaghu-elements/rds-alert/rds-alert.tsx
Labels: Bug

#2647 Resolved Bug 2634 : In Grid Remove Unwnated Control And Filter Text Should Be Muted
  raaghu-components/rds-comp-grid/rds-comp-grid.scss
  raaghu-components/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/rds-comp-grid/rds-comp-grid.tsx
Labels: Bug

#2670 Resolved Bug 2656 : Design System > Tree Structure > In language control- Cplus, Docker, ESLint, Git, Go, Gulp, Python, React, typescript, XML and YML icon is not showing also default option is not as per figma.
  raaghu-components/rds-comp-tree-structure/fileTypeIcons.tsx
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.scss
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.stories.tsx
Labels: Bug

#2668 Completed Task-2653: Add Griffel integration and refactor App component
  package.json
  raaghu-pages/src/App.tsx
  raaghu-pages/src/main.tsx
  raaghu-pages/vite.config.ts
  utils/griffel/GriffelProvider.tsx
  utils/griffel/griffel-config.ts
  vite.config.ts
Labels: Task

#2709 Resolved Bug 2684 : Design System > Dark theme > Button > Dark mode inside button text should be white for all color controls.
  raaghu-elements/rds-button/rds-button.scss
Labels: Bug

#2712 Resolved Bug 2677 : Button Dropdown > All Stories Not Proper Show In Dark Mode
  raaghu-elements/rds-radio/rds-radio.scss
Labels: Bug

#2721 Resolved Bug 2714 : Design system > Dark theme > Text Area > Dark mode it's not display proper.
  raaghu-elements/rds-text-area/rds-text-area.scss
Labels: Bug

#2718 Resolved Bug 2688 : Drawer > Interactive Story Dark Theme Issue
  raaghu-elements/rds-drawer/rds-drawer.stories.tsx
Labels: Bug

#2729 Resolved Bug 2724: Design system > Kanban Board > Drag and drop functionality is not working
  raaghu-components/rds-comp-kanban-board/kanban-board-helpers.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.tsx
Labels: Bug

#2728 Resolved Bug 2708,2710 and 2711 : Design System > Time Picker > It's not working proper in dark mode and Design System > Dark theme > Text Editor > Dark mode it's not looking appropriate like "B" and other icons and Design System > Dark theme > Reviews > Style 1, 3, 5, 7, 9, 11 inside avatar text is not display proper in dark theme
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.scss
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.scss
Labels: Bug

#2731 Resolved Bug 2715, 2726 : Snackbar And Speed Dial dark theme issue
  raaghu-elements/rds-snackbar/rds-snackbar.stories.tsx
Labels: Bug

#2730 Resolved Bug 2696 : Progress Bar Stepper Type Proper Not Show In Dark Theme
  raaghu-elements/rds-progress/rds-progress.scss
  raaghu-elements/rds-progress/rds-progress.tsx
Labels: Bug

#2732 Resolved Bug 2713 : Design system > Dark theme > Toast > Dark mode is on, and layout is downloading the "GO TO DOWNLOADS" text should be in white color.
  raaghu-components/rds-comp-toast/rds-comp-toast.scss
Labels: Bug

#2733 Resolved issue 2658: Design System > Date picker > In layout control when we select months picker or year picker check for the small screen size.
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.scss
Labels: Bug

#2737 Resolved issue 2698: Design system > Dark theme > Date Picker > layout control all layout is not looking appropriate for dark mode.
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.scss
Labels: Bug

#2749 Resolved Bug 2689 : Design System > Dark theme > Box > When dark mode is on 'with margin ' stories can we change the color of the inside box text, so it's look good in dark mode.
  raaghu-elements/rds-box/rds-box.scss
  raaghu-elements/rds-box/rds-box.stories.tsx
  raaghu-elements/rds-box/rds-box.tsx
Labels: Bug

#2757 Resolved Bug 2681: Design System > Backdrop > loading story loading circle is not visible in dark themes
  raaghu-elements/rds-backdrop/rds-backdrop.scss
  raaghu-elements/rds-backdrop/rds-backdrop.tsx
Labels: Bug

#2758 Resolved Bug 2704 : Design System > Dark theme > Chat > Dark mode when I hover on the chat member it's not looking proper
  raaghu-components/rds-comp-chat/rds-comp-chat.scss
Labels: Bug

#2759 Resolved Bug 2744 : In A Grid Dark Theme Issue
  raaghu-components/rds-comp-grid/rds-comp-grid.scss
  raaghu-components/rds-comp-grid/rds-comp-grid.tsx
Labels: Bug

#2763 Resolved But 2748 : In The Dark Theme, List Title And Avatar Text Are Not Displayed Properly
  raaghu-elements/rds-list/rds-list.scss
Labels: Bug

#2764 Resolved Bug 2701: Design System > Dark theme > Off Canvas > Button that text also in white color when dark mode is on
  raaghu-components/rds-comp-off-canvas/rds-comp-off-canvas.scss
Labels: Bug

#2768 Resolved Bug 2756 : Design System > Toggle Button > Apart from without icons, vertical buttons and standalone toggle buttons these stories other stories are not looking good in small mobile size.
  raaghu-elements/rds-toggle-button/rds-toggle-button.scss
  raaghu-elements/rds-toggle-button/rds-toggle-button.stories.tsx
  raaghu-elements/rds-toggle-button/rds-toggle-button.tsx
Labels: Bug

#2785 Resolved Bug 2770 & 2775 : Design System > List/ Popover > Small & Large Mobile view issues
  raaghu-elements/rds-list/rds-list.scss
  raaghu-elements/rds-popover/rds-popover.scss
  raaghu-elements/rds-popover/rds-popover.tsx
Labels: Bug

#2798 Resolved Bug 2784 : Design System > Element > Rating > Selecting type slider is not working proper
  raaghu-elements/rds-rating/rds-rating.tsx
Labels: Bug

#2780 Resolved Bug 2705 : Code Snippet Dark Theme Not Show Proper
  package.json
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.scss
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.tsx
Labels: Bug

#2787 Resolved Bug 2779 : In Stepper With Optional Steps Story Not Show Proper In Small Screen
  raaghu-elements/rds-stepper/rds-stepper.scss
Labels: Bug

#2791 Resolved Bug 2772 : Carousel Default Story Not Show Proper In Small Screen
  raaghu-elements/rds-carousel/rds-carousel.scss
Labels: Bug

#2804 Resolved Bug 2795 : In Collapse Default & Long Content Story Not Show Proper In Dark Theme
  raaghu-elements/rds-collapse/rds-collapse.scss
  raaghu-elements/rds-collapse/rds-collapse.stories.tsx
  raaghu-elements/rds-collapse/rds-collapse.tsx
Labels: Bug

#2782 Resolved Bug 2685 : Design System > Dark theme > Card Detail > Default story and variant control if select elevation it's not showing anything.
  raaghu-elements/rds-card-detail/rds-card-detail.scss
  raaghu-elements/rds-card-detail/rds-card-detail.tsx
Labels: Bug

#2793 Resolved Bug 2781: Design System > Dark theme > Emoji Generator > Dark mode is not display proper.
  raaghu-components/rds-comp-emoji-generator/rds-comp-emoji-generator.scss
Labels: Bug

#2800 Resolved Bug 2777 : Design System > Box > For flex container story it's not looking good in small screen size.
  raaghu-elements/rds-box/rds-box.scss
Labels: Bug

#2803 Resolved Bug 2699 : Design system > Dark theme > Toolbar >Dark mode, inside toolbar is not looking appropriate.
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.scss
Labels: Bug

#2788 Resolved Bug 2752: Design System > Dark theme > Banner > In all types of stories the green banner in dark mode link and cancel text not looking good
  raaghu-elements/rds-banner/rds-banner.scss
  raaghu-elements/rds-banner/rds-banner.stories.tsx
  raaghu-elements/rds-banner/rds-banner.tsx
Labels: Bug

#2797 Resolved Bug 2702: Design System > Dark theme > Map > Dark mode it's not looking as expected
  raaghu-components/rds-comp-map/rds-comp-map.scss
Labels: Bug

#2790 Resolved issue 2753: Design System > Dark theme > Kanban Board> There is three dots when I click on that it's show one dropdown that does not display proper in dark mode.
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.scss
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.scss
Labels: Bug

#2789 Resolved Bugs 2741, 2742, 2743 : Design System, Ai chatbox- Dark mode attachment is not properly visible and Adaptive Cards- update activity card not looking good in dark mode and charts-for all charts can we make X-axis and Y-axis more visible if it is possible
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards-helpers.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.scss
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-components/rds-comp-ai-attachement/rds-comp-ai-attachement.scss
  raaghu-components/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.scss
  raaghu-components/rds-comp-ai-fab-menu/rds-comp-ai-fab-menu.scss
  raaghu-components/rds-comp-ai-icon/rds-comp-ai-icon.scss
  raaghu-components/rds-comp-ai-typing-section/rds-comp-ai-typing-section.scss
  raaghu-components/rds-comp-chart-area/rds-comp-chart-area.tsx
  raaghu-components/rds-comp-chart-bar/rds-comp-chart-bar.tsx
  raaghu-components/rds-comp-chart-boolean/rds-comp-chart-boolean.tsx
  raaghu-components/rds-comp-chart-bubble/rds-comp-chart-bubble.tsx
  raaghu-components/rds-comp-chart-doughnut/rds-comp-chart-doughnut.tsx
  raaghu-components/rds-comp-chart-gauge/rds-comp-chart-gauge.tsx
  raaghu-components/rds-comp-chart-line/rds-comp-chart-line.tsx
  raaghu-components/rds-comp-chart-mixed/rds-comp-chart-mixed.tsx
  raaghu-components/rds-comp-chart-pie/rds-comp-chart-pie.stories.tsx
  raaghu-components/rds-comp-chart-pie/rds-comp-chart-pie.tsx
  raaghu-components/rds-comp-chart-polar-area/rds-comp-chart-polar-area.tsx
  raaghu-components/rds-comp-chart-radar/rds-comp-chart-radar.tsx
  raaghu-components/rds-comp-chart-scatter/rds-comp-chart-scatter.tsx
  raaghu-components/rds-comp-chart-stacked/rds-comp-chart-stacked.tsx
Labels: Bug

#2814 Resolved Bug 2703: Design System > Dark theme > Notification > When style is image the background of that image is not looking good in dark mode
  raaghu-components/rds-comp-notification/rds-comp-notification.scss
Labels: Bug

#2819 Resolved Bug 2774 : In Dark Theme Grid Not Show Proper
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.scss
  raaghu-components/rds-comp-grid/rds-comp-grid.scss
Labels: Bug

#2821 Resolved Bug 2810 : Design System > Notification > Close icon not closing, only closes on away click
  raaghu-elements/rds-icon-button/rds-icon-button.tsx
Labels: Bug

#2824 Resolved Bug 2816 , 2817 : Resolve Toolbar And Button Reated Responsiveness and Color Issues
  raaghu-components/rds-comp-emoji-generator/rds-comp-emoji-generator.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar-config.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.scss
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.tsx
  raaghu-elements/rds-button/rds-button.scss
  raaghu-elements/rds-button/rds-button.tsx
Labels: Bug

#2826 Resolved Bug 2632 & 2704 : Resolve Popover & Chat Issues
  raaghu-components/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.scss
  raaghu-elements/rds-popover/rds-popover.stories.tsx
Labels: Bug

#2827 Resolved Bug 2820 : Design System > Notification > Close icon not closing, only closes on away click
  raaghu-components/rds-comp-notification/rds-comp-notification.scss
  raaghu-components/rds-comp-notification/rds-comp-notification.tsx
Labels: Bug

#2851 Bug 2742: Resolved Issue in Adaptive cards light mode not looking properly
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.scss
Labels: Bug

#2893 Resolved Bug 2879 : List Check Button Now Show Proper In Dark Theme
  raaghu-elements/rds-list/rds-list.scss
Labels: Bug

#2936 Completed Task : Row and Column Swapping Enhancement in Fluent Grid.
  raaghu-components/rds-comp-fluent-grid/rds-comp-fluent-grid.stories.tsx
  raaghu-components/rds-comp-fluent-grid/rds-comp-fluent-grid.tsx
Labels: Enhancement

#2928 Resolved Bug 2877 & 2878 : Design System > Element > Loader/ Modal > Control Parameters & Errors Issue
  raaghu-elements/rds-loader/rds-loader.stories.tsx
  raaghu-elements/rds-modal/rds-modal.stories.tsx
Labels: Bug

#2940 Resolved Bug 2933 : In Radio Selected Control Is Missing In Default Story
  raaghu-elements/rds-radio/rds-radio.stories.tsx
  raaghu-elements/rds-radio/rds-radio.tsx
Labels: Bug

#2945 Resolved Bug 2909 : Design System > Elements > Dropdown Button > After selecting all control false showing blank dropdown, show me option text here.
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.scss
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.tsx
Labels: Bug

#2950 Resolved Bug 2906 : Design System > Element > SnackerBar > Clarify and fix SnackerBar open control.
  raaghu-elements/rds-snackbar/rds-snackbar.stories.tsx
Labels: Bug

#2900 Resolved Bug 2884: Design System > Element > Divider > Fix Divider icon control and vertical story issues
  raaghu-elements/rds-divider/rds-divider.stories.tsx
  raaghu-elements/rds-divider/rds-divider.tsx
Labels: Bug

#2923 Resolved Bug 2886: Design System > Element > Checkbox > Fix Checkbox circle style appearance in dark mode
  raaghu-elements/rds-checkbox/rds-checkbox.scss
Labels: Bug

#2930 Resolved Bug 2903: Design System >Element > Popover > Fix popover arrow alignment for all positions
  raaghu-elements/rds-popover/rds-popover.scss
Labels: Bug

#2941 Resolved Bug 2907: Design System > Element > Switch > Fix or remove color control in Switch component
  raaghu-elements/rds-switch/rds-switch.scss
  raaghu-elements/rds-switch/rds-switch.stories.tsx
Labels: Bug

#2899 Resolved Bugs: 2882 : Design System > Element > File Uploader > Fix File Uploader icon and isMandatory visibility in dark mode
  raaghu-elements/rds-file-uploader/RdsFileUploaderComponents.tsx
Labels: Bug

#2917 Resolved Bug 2901 : Design System >Element > Menu > Fix menu text color inconsistency in dark mode
  raaghu-elements/rds-menu/rds-menu.scss
  raaghu-elements/rds-menu/rds-menu.tsx
Labels: Bug

#2913 Resolved Bug 2861 : Design System > Element > Card > Fix Card layout and alignment issues
  raaghu-elements/rds-card/rds-card.scss
  raaghu-elements/rds-card/rds-card.stories.tsx
  raaghu-elements/rds-card/rds-card.tsx
Labels: Bug

#2952 Resolved bug 2922: Design System > Elements > Form Control > When select variant control hint text is misaligned.
  raaghu-elements/rds-form-control/rds-form-control.scss
  raaghu-elements/rds-form-control/rds-form-control.stories.tsx
Labels: Bug

#2951 Resolved Bug 2915 : In Dialog Size Control Not As Per Figma and Show Title Control Is Missing
  raaghu-elements/rds-dialog/rds-dialog.stories.tsx
  raaghu-elements/rds-dialog/rds-dialog.tsx
Labels: Bug

#2961 Resolved Bug 2942: Design System > Elements > Tab > Layout -flap is not match as per figma.
  raaghu-elements/rds-tabs/rds-tabs.scss
Labels: Bug

#2978 Resolved Bug 2975 : Design System > Element > Accordion > Dark theme > Field color is not same as per WF in dark mode
  raaghu-elements/rds-accordion/rds-accordion.scss
Labels: Bug

#2971 Resolved Bug 2939: Design System > Elements > Slider > Range & disabled stories showing error
  raaghu-elements/rds-slider/rds-slider.tsx
Labels: Bug

#2935 Resolved Bug 2902 : Design System >Element > Multi Level Menu > Fix menu text color inconsistency in light and dark mode
  raaghu-elements/rds-multi-level-menu/rds-multi-level-menu.scss
  raaghu-elements/rds-multi-level-menu/rds-multi-level-menu.tsx
Labels: Bug

#2987 Resolved Bug 2976 : Design System > Component > Adaptive cards > Controls are not working
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards-helpers.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.scss
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
Labels: Bug

#2984 Resolved bug 2982: Design System > Component > Details pane > Buttons are not alignment in small, Large mobile view
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.scss
Labels: Bug

#2970 Resolved Bugs 2934 and 2927 : Design System > Elements > Range > color and interactive stories controls is not working and Multi level Menu > Size control is not working as per figma.
  raaghu-elements/rds-multi-level-menu/rds-multi-level-menu.scss
  raaghu-elements/rds-multi-level-menu/rds-multi-level-menu.stories.tsx
  raaghu-elements/rds-multi-level-menu/rds-multi-level-menu.tsx
  raaghu-elements/rds-range/rds-range.stories.tsx
Labels: Bug

#2963 Resolved Bug 2929: Design System > Elements > Pagination > All control is missing as per figma
  raaghu-elements/rds-pagination/rds-pagination.helpers.ts
  raaghu-elements/rds-pagination/rds-pagination.scss
  raaghu-elements/rds-pagination/rds-pagination.stories.tsx
  raaghu-elements/rds-pagination/rds-pagination.tsx
Labels: Task

#2962 Resolved Bug 2926: Design System > Elements > Modal > When I click on control Icon & show icon display error.
  raaghu-elements/rds-modal/rds-modal.stories.tsx
Labels: Bug

#2959 Resolved Bug 2914 : In Counter Layout, State, Placeholder Control Is Missing As Per Figma
  raaghu-elements/rds-counter/rds-counter.scss
  raaghu-elements/rds-counter/rds-counter.stories.tsx
  raaghu-elements/rds-counter/rds-counter.tsx
Labels: Bug

#2958 Resolved Bug 2919 : Design System > Elements > Fab > Extended stories select color variant circular is not display proper.
  raaghu-elements/rds-fab/rds-fab.scss
  raaghu-elements/rds-fab/rds-fab.stories.tsx
  raaghu-elements/rds-fab/rds-fab.tsx
Labels: Bug

#3002 Resolved Bug 2997 : In Tree Structure And Grid Make Responsiveess For Small And Large Screen
  raaghu-components/rds-comp-grid/rds-comp-grid.tsx
  raaghu-elements/rds-carousel/rds-carousel.scss
Labels: Bug

#3001 Resolved Bug 2994 : Design System > Chart > Mixed Chart > In Mixed Chart chartStyle Control Not working.
  raaghu-components/rds-comp-chart-mixed/rds-comp-chart-mixed.stories.tsx
  raaghu-components/rds-comp-chart-polar-area/rds-comp-chart-polar-area.stories.tsx
Labels: Bug

#2999 Resolved Bug 2993 : Design System > Chart > Bubble Chart > In Bubble Chart chartWidth and chartStyle control Not working
  raaghu-components/rds-comp-chart-bubble/rds-comp-chart-bubble.stories.tsx
  raaghu-components/rds-comp-chart-doughnut/rds-comp-chart-doughnut.stories.tsx
Labels: Bug

#2998 Resolved Bug 2979 : In Date Time Picker Resolved UI Issues , Chnage Variant Name And Unused Control Hide
  raaghu-components/rds-comp-date-and-time-picker/rds-comp-date-and-time-picker.scss
  raaghu-components/rds-comp-date-and-time-picker/rds-comp-date-and-time-picker.stories.tsx
  raaghu-components/rds-comp-date-and-time-picker/rds-comp-date-and-time-picker.tsx
Labels: Bug

#2996 Resolved Bug 2981 : In Date Time Picker Alignment Issue In Helper Text And Hide Datetimerange From Variant
  raaghu-components/rds-comp-date-and-time-picker/rds-comp-date-and-time-picker.scss
  raaghu-components/rds-comp-date-and-time-picker/rds-comp-date-and-time-picker.stories.tsx
  raaghu-components/rds-comp-date-and-time-picker/rds-comp-date-and-time-picker.tsx
Labels: Bug

#3007 Resolved Bug 2711 : Design System > In Reviews Avatar Title Not Show Proper In Dark Theme.
  raaghu-elements/rds-avatar/rds-avatar.scss
Labels: Bug

#3013 Resolved Bugs 3011 and 3012 : Design System > Component > Grid > Filters > Missing scroll bar and Last login > Calendar > After selecting a date, the filters are also closing
  raaghu-components/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.scss
Labels: Bug

#3015 Resolved Issue : Fix Package Build Issue
  .github/workflows/npm_publish.yml
Labels: Deployment

#3062 Merged Development to Staging : Changes are made from development branch to staging branch
  .github/workflows/storybookreact.yml
  .gitignore
  .npmignore
  bunfig.toml
  package.json
  raaghu-components/index.ts
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards-helpers.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.scss
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-components/rds-comp-audio-player/rds-comp-audio-player.scss
  raaghu-components/rds-comp-chart-bar/rds-comp-chart-bar.stories.tsx
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.stories.tsx
  raaghu-components/rds-comp-date-and-time-picker/rds-comp-date-and-time-picker.stories.tsx
  raaghu-components/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.scss
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.scss
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.stories.tsx
  raaghu-elements/rds-avatar/rds-avatar.scss
  raaghu-elements/rds-file-uploader/rds-file-uploader.scss
  raaghu-elements/rds-menu/rds-menu.scss
Labels: Deployment

#3069 Resolved Bugs 3065 and 3066: Design System > Component > Contribution > UI is not in centered align and in icon the color-Variant control is not working
  raaghu-components/rds-comp-contribution/rds-comp-contribution.scss
  raaghu-components/rds-comp-contribution/rds-comp-contribution.tsx
Labels: Bug

#2830 Resolved Bug 2822 : Design System > Code Snippet > Language Dropdown is not as per Figma Design.
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.scss
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.stories.tsx
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.tsx
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.scss
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.tsx
Labels: Bug

#3051 Resolved Bug 3030 : Design System > Component > Chat > After hovering the text color and hovering effect is different than WF
  raaghu-components/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/rds-comp-chat/rds-comp-chat.tsx
Labels: Bug

#3059 Resolved Bugs 3033 and 3034 : Design System > Component > Details pane > Toolbar > Delete icon is not display on card
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.scss
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.stories.tsx
Labels: Bug

#3073 Resolved Bug 2662: Design System > App Bar > Most of the stories show search control not working, also there is unwanted controls in every story
  raaghu-elements/rds-app-bar/rds-app-bar.stories.tsx
Labels: Bug
