Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-01, with the labels that each got.

#1376 Resolved Bug 1374: Design System > Elements > Banner > Raaghu > Missing "Colorvariant" field in controls
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
Labels: Bug

#1292 Resolved Bug 1283: Design System > Component > Properties > Default > Button alignment issue
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
Labels: Bug

#1324 Completed Task 1304 : Design System > Sidebar > Added Release Version For All Environments
  .storybook/main.ts
Labels: Task

#1333 Resolved Bug 809 : Design System > Component and layout > Assistance And All Layouts > Controls > All Errors Resolved
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.stories.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
Labels: Bug

#1296 Resolved Bug 989 : Design System > Element > AI Prompt for new project flow
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.stories.tsx
Labels: Bug

#1373 Resolved Bug 1368: Design System > Components > Password Setting > Default > The new password and confirm new password validation are not displayed properly.
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#1380 Merging Development : Moving Changes from Development to Stage
  .storybook/custom-theme.css
  .storybook/main.ts
  Contributors.txt
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.stories.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.css
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Deployment

#1307 Resolved Bug 823 : Design System > Create color variants for toast elements
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/accordion.scss
  raaghu-react-themes/src/styles/alert.scss
  raaghu-react-themes/src/styles/breadcrumb.scss
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/default.scss
Labels: Bug, Enhancement

#1280 Resolved Bug 1213 : Design System > Elements > Navtabs > Icon Only > Styled > Vertical left filled > Not able to see home icon after hovering on it
  raaghu-elements/src/rds-navtabs/rds-navtabs.css
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#1379 Resolved Bug 1375: Design System > Elements/Components >The sub-element/component name is the same as the main component/element
  raaghu-elements/src/rds-address-detail/rds-address-detail.stories.tsx
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.stories.tsx
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
  raaghu-elements/src/rds-card-detail/rds-card-detail.stories.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.stories.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/src/rds-collapse/rds-collapse.stories.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.stories.tsx
  raaghu-elements/src/rds-color-switcher/rds-color-switcher.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.stories.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.stories.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.stories.tsx
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-label/rds-label.stories.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.stories.tsx
  raaghu-elements/src/rds-map/rds-map.stories.tsx
  raaghu-elements/src/rds-navbar/rds-navbar.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-popover/rds-popover.stories.tsx
  raaghu-elements/src/rds-popular-page/rds-popular-page.stories.tsx
  raaghu-elements/src/rds-rating/rds-rating.stories.tsx
  raaghu-elements/src/rds-search/rds-search.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-tag/rds-tag.stories.tsx
  raaghu-elements/src/rds-team-member/rds-team-member.stories.tsx
  raaghu-elements/src/rds-testimonial/rds-testimonial.stories.tsx
  raaghu-elements/src/rds-tooltip/rds-tooltip.stories.tsx
Labels: Bug

#1342 Resolved Bug 1260 : Design System > Elements > Badge > In Color variant info color is not according to Figma design.
  .storybook/custom-theme.css
  raaghu-elements/src/rds-badge/rds-badge.css
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/default.scss
Labels: Bug

#1284 Resolved Bug 1281:Design System > Element > Input > Number Input > Overlapping issue
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#1262 Resolved Bug 1251 : Design System > Component > Chatbot > Overlapping issue and pop-up closing issue
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
Labels: Bug

#1381 Resolved Bug 1344 : Design System > Components > Claims And Developer Mode > Default > Input box highlighted in required color
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.css
  raaghu-components/src/rds-comp-claims/rds-comp-claims.stories.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#1078 Completed Task 776 : Design System > Elements > Enhancements in Toast
  raaghu-components/src/rds-comp-background-image/rds-comp-background-image.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#1295 Resolved Bug 1264 : Design System > Sidebar > Elements > Chart & Map Icon issue
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
Labels: Bug

#1306 Resolved Bug 1274: Components Admin Dashboard UI & alignment Issues.
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1301 Resolved Bug 1282: Elements Checkbox Check box & texts spacing issue
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1382 Resolved Bug 975 : Design System > Element > Counter > Enhanced Counter As Per Design
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Enhancement

#1317 Resolved Bug 1309: Design System > Elements > Big Number > Histogram > Canvas does not display proper
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#1365 Resolved Bug 1340: Design System > Components > Blog Post > Default > label is missing & Blog Id input box spacing issue
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1363 Resolved Bug 1346: Design System > Components > Dynamic Entity Properties > Default > Label & input box alignment issue
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-dynamic-entity-property/rds-comp-dynamic-entity-property.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Bug

#1299 Resolved Bug 1148: Components Webhook Subscription Default Text alignment issue
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Bug

#1386 Resolved Bug 1370 : Design System > Components > Login > Default > Fixed Language Dropdown
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1385 Enhanced Task 1174 : Design System > Storybook > Add enhanced functionalities to Grid Component
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Enhancement

#1366 Resolved bug 1353 : Design System > Components > Tenant Information > Default > After submitting field not clear.
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
Labels: Bug

#1329 Resolved bug 1327 : Design System > Components >Dialog > Default > Cross button alignment issue.
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
Labels: Bug

#1362 Resolved bug 1360 : Design System > Elements > Fab Menu > Small mobile view is not display proper.
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1358 Resolved bug 1348 : Design System > Components > Personal Info > Default > Verify Email button alignment issue.
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
Labels: Bug

#1279 Resolved bug 1207 : Design System > Component > Blog Post > Default > Not able to see last field of form and button size is bigger than field.
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#1355 Resolved bug 1107 : Design System > Components > Chat > Default > Placeholder text & icon is not centralized.
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1334 Resolved bug 1126 : Design System > Components > Edition > Default > Dark theme Basics & Features text color issue.
  raaghu-components/src/rds-comp-edition/rds-comp-edition.css
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1314 Resolved bug 1129 : Design System > Components > Identity Client Basic > Default > Required Consent alignment issue.
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
Labels: Bug

#1275 Resolved bug 1137 : Design System > Components > Register > Default >Toggle is display outside of modal.
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1320 Resolved bug 1149 : Design System > Application Shells > Default > UI issue.
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1326 Completed task 1232 : Design System > Application > Enhancement in Comment component, File Uploader component, Accordion position and Nav tab badges
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
Labels: Task

#1396 Resolved Bug 1384 : Design System > Logo Border Not Displayed Properly
  .storybook/custom-theme.css
Labels: Bug

#1392 Resolved Bug 1390 : Design System > Component > Data Table > Enhancement > Add property Is clickable to column [New Project Flow]
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
Labels: Enhancement

#1352 Resolved Bug 1242 : Design system > Elements > Feed > Added size parameter and Resolved other Bugs
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1397 Completed bug 1395 : Design System > Elements >Time Picker > Default > Outside icon click functionality is not working.
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.stories.tsx
  raaghu-elements/src/rds-time-picker/rds-time-picker.tsx
Labels: Bug

#1399 Resolved Bug 1389 : Design System > Elements > Review Category > Center Aligned/Left Aligned Stories Profile Icon Is Enlarged
  raaghu-elements/src/rds-review-category/rds-review-category.css
Labels: Bug

#1411 Design System Deployment development to staging
  raaghu-components/src/rds-comp-forms-email/rds-comp-forms-email.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.css
Labels: Deployment

#1419 Resolved Bug 1282: Design System > Baner > Raaghu > light theme text is not display
  raaghu-elements/src/rds-banner/rds-banner.tsx
Labels: Bug

#1420 Resolved Bug 1368 : Design System > Components > Password Setting > Default > The new password and confirm new password validation are not displayed properly.
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug
