Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-05, with the labels that each got.

#2003 commit for implement tailwindcss
  package.json
  raaghu-pages/postcss.config.js
  raaghu-pages/src/App.css
  raaghu-pages/src/main.tsx
  raaghu-pages/tailwind.config.js
  vite.config.ts
Labels: Task

#2001 "Commited Changes for MUI dependencies "
  package.json
Labels: Task

#2002 "Integrate Fluent UI components into Raaghu Design System "
  package.json
Labels: Task

#2009 Bug 1982: Resolved Issue on Design System > Element > Typing Section > Enhancement as per new design.
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
Labels: Bug

#2010 Bug 1548: Resolved Issue on Design System > Elements > Side navigation > Custom Navigation Side bar right > UI issues in side navigation.
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.css
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#2011 Bug 1982: Resolved Issue on Design System > Element > Typing Section > Enhancement as per new design.
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
Labels: Bug

#2015 Resolved Bug 2014 : Design System > Layout > Need to add property for shadow.
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.css
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.tsx
Labels: Bug

#2018 Resolved Bug 1897 : Design system (Prod) > Elements/Components > Error is displayed.
  .storybook/preview.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
Labels: Bug

#2017 Resolved Bug 1982: Design System > Element > Typing Section > Enhancement as per new design.
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
Labels: Bug

#2022 Resolved Bug 2021 : Premium Support > Save Button Is Not Enabled Even After All Mandatory Fields Has The Value
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
  raaghu-elements/src/rds-text-editor/rds-text-editor.tsx
Labels: Bug

#2025 Resolved Bug 2024 : Design System > Component > Side Navigation > Error while opening the component.
  .storybook/preview.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
Labels: Bug

#2026 Resolved Bug 2019 : Design System > Component > Select List > Search results takes more time to show list thus before showing search results it shows message "No Records".
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#2028 Resolved Bug : 2027 > Side Navigation > Expanded and Collapsed Functionality Not Working Properly
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: Bug

#2030 Resolved Bug 1539 : Application Shell > Enhancement As Per Figma Design Kit
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Bug

#2033 Resolved Bug 2032 : Design System > Element > Select List > after selecting 2nd select list loader is still displayed for the 1st select list on page.
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#2038 Completed Task : Design System > Merge Development into Staging
  .storybook/preview.tsx
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Bug, Deployment

#2043 Resolved Bug 2016 : Design System >The English name needs to be added everywhere
  raaghu-elements/src/rds-chat/rds-chat.stories.tsx
Labels: Bug

#2037 Resolved Task 2031 : Design System > Need To Change Design System Pages Solution
  raaghu-pages/src/App.css
  raaghu-pages/src/App.tsx
Labels: Task

#1830 Resolved Bug 1785 : Design System > Components > File Management Tree > Icons disappear in dark theme
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1042 Enhancement Task 1041 : Design System > Pipeline > Integrate Chromatic in GitHub Action for Dev, Stage and Production
  .github/workflows/chromatic.yml
Labels: Deployment, Github Actions

#1646 Resolved Bug 1645 : Design System > Component > Grid > Advance > Not able to see delete text
  .github/workflows/chromatic.yml
  raaghu-elements/src/rds-chat/rds-chat.stories.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-pages/src/App.css
  raaghu-pages/src/App.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1451 Resolved Bug 1450 : Design System > Elements > Avatar > Avatar Only > Avatar dots are overlapping
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Bug

#1443 Resolved Bug 1401 : Design System > Element > Counter > Element and Component changes
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
  raaghu-components/src/rds-comp-purchase-developer-seats/rds-comp-purchase-developer-seats.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Enhancement

#2044 Resolved Issue: Color variables color code issues
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#1285 Resolved Bug 1147 : Design System > Components Url Forwardings Default Required message is not display
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#1308 Resolved Bug 1293 : Design System > Edition Information Small Large Tablet button alignment issue
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
Labels: Bug

#2045 Resolve issues: Found during testing
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
  raaghu-elements/src/rds-map/rds-map.stories.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#2047 Resolved Bug: Refactor CSS styles for text-dark class and clean up dropdown list CS…
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#2046 Resolved Bug 2041: Design System > Element >Side Navigation > Tooltip missing in collapse view.
  raaghu-elements/src/rds-side-nav/rds-side-nav.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: Bug

#2048 Merge Development : Changes From Development to Staging
  package.json
  postcss.config.cjs
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
  raaghu-components/src/rds-comp-payment-tenure/rds-comp-payment-tenure.tsx
  raaghu-components/src/rds-comp-purchase-developer-seats/rds-comp-purchase-developer-seats.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-map/rds-map.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-pages/package.json
  raaghu-pages/postcss.config.js
  raaghu-pages/src/index.css
  raaghu-pages/src/lib/utils.ts
  raaghu-pages/src/main.tsx
  raaghu-pages/tailwind.config.js
  raaghu-pages/tsconfig.json
  raaghu-pages/vite.config.ts
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/colorvariables-semidark.scss
  raaghu-react-themes/src/styles/default.scss
  tailwind.config.ts
  tsconfig.json
Labels: Deployment

#2052 Resolved Task 1821 : New Enhansement Of Details Pane
  .storybook/assets/icons/edit_underline.svg
  .storybook/assets/icons/history_watch.svg
  .storybook/assets/icons/icon_block.svg
  .storybook/assets/icons/icon_color.svg
  .storybook/assets/icons/icon_font.svg
  .storybook/assets/icons/icon_frame.svg
  .storybook/assets/icons/icon_line_height.svg
  .storybook/assets/icons/star_border.svg
  .storybook/assets/icons/storybook_icon.svg
  raaghu-components/src/rds-comp-details-pane/index.ts
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.stories.tsx
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Task

#2055 Resolved Bug 1147 : Design System > Components > Url Forwardings > Default > Required Message is Not Display
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
Labels: Bug

#2078 Resolved Task 2076 : Implement New Side Navigation
  .storybook/manager-head.html
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-side-navigation1/index.ts
  raaghu-components/src/rds-comp-side-navigation1/rds-comp-side-navigation1.stories.tsx
  raaghu-components/src/rds-comp-side-navigation1/rds-comp-side-navigation1.tsx
Labels: Task

#2073 Completed Task 2066 : Design System > Elements > All links And Icons Are Same
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
Labels: Task

#2079 Resolved Bug 2071: Design System > Component > Details Pane > Hover Effect is Missing and Delete Functionality is Not Working
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
Labels: Bug

#2080 Resolved Bug 2070: Design System > Component > Details Pane > Dark Theme For Details Pane component is Different Than WF
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
Labels: Bug

#2085 Resolved Bug 2054 : Design System Component Ai Chat Bot Dropdown Icon Remains Unchanged After Selecting Values
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
Labels: Bug
