Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-02, with the labels that each got.

#1423 Resolved Bug 1311 : Design System > Elements > Pagination > Advanced > Dark theme pagination is now display proper
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
Labels: Bug

#1425 Resolved bug 1395: Elements >Notification > Default > Mark As Read button alignment issue.
  raaghu-elements/src/rds-notification/rds-notification.tsx
Labels: Bug

#1408 Resolved bug 1360 : Design System > Elements > Fab Menu > Small mobile view is not display proper.
  raaghu-react-themes/src/styles/dropdown.scss
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1406 Resolved bug 1348 : Design System > Components > Personal Info > Default > Verify Email button alignment issue.
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1400 Resolved bug 1347 : Design System > Components > Page not found > Default > Text is not displaying center.
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-page-not-found/rds-comp-page-not-found.tsx
Labels: Bug

#1325 Resolved bug 1322 : Design System > Components > Email Settings > Default > Label & Input box alignment issue.
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
Labels: Bug

#1421 Resolved Bug 1340: Design System > Components > Blog Post > Default > Cover Image & Blog Id input box spacing issue.
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-elements/src/rds-label/rds-label.tsx
Labels: Bug

#1300 Completed Task 849 : Design System > Element > Progress Bar > Default : Enhancements in style.
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
Labels: Task

#1426 Resolved Bug 1404 : Design System > Elements > Rating > The position of the rating stars is inconsistent after changing the count
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
Labels: Bug

#1418 Resolved bug 1412 : Design System > Elements > Dropdown > With Multi Select > Small & large mobile selected option is not display proper.
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1367 Resolved bug 1361 : Design System > Elements > File Uploader > Default > File Uploader is not display proper.
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#1398 Resolved bug 1354 : Design System > Components > Visual Setting > Default > After submitting select list values are not clear.
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Bug

#1428 Resolved Bug 1427: Design System > Element > App detail > Default > Missing Controls and missing formatting.
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
Labels: Bug

#1405 Resolved bug 1353 : Design System > Components > Tenant Information > Default > After submitting field not clear.
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
Labels: Bug

#1433 Resolved Bug 1346: Design System > Components >Database Connection > checkbox and text alignment issue and Database URL validation
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
Labels: Bug

#1429 Resolved Bug 1242 : Design system > Elements > Feed > Added size parameter and Resolved Reopen Bugs
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.tsx
Labels: Bug

#1436 Resolved Bug 1293: Design system > Components > Edition Information >Small large tablet button alignment
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
Labels: Bug

#1431 Resolved Bug 1344 : Design System > Components > Claims And Developer Mode > Default > Input box highlighted in required color Reopen Bug
  raaghu-elements/src/rds-select-list/rds-select-list.css
Labels: Bug

#1435 Bug 1434: Resolved Design System > Elements > Alerts > Code formatting and optimization
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Bug

#1414 Completed Task 784 : Design System > Elements > Enhancements in Action Button/Dropdown.
  raaghu-react-themes/src/styles/dropdown.scss
  raaghu-react-themes/src/styles/responsive.scss
Labels: Task

#1437 Fixed deployment issue
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
Labels: Bug

#1438 Resolved Bug 1393: Design System > Elements > Rating > The position of the rating stars is inconsistent after changing the count
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
Labels: Bug

#1439 Design System Deployment development to staging
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-page-not-found/rds-comp-page-not-found.tsx
  raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx
  raaghu-components/src/rds-comp-personal-info/rds-comp-personal-info.tsx
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
  raaghu-elements/src/rds-banner/rds-banner.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-label/rds-label.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/dropdown.scss
  raaghu-react-themes/src/styles/responsive.scss
Labels: Deployment

#1441 Bug 1440: Design System > Element > AI prompt Box > Default > Enhancement & remove unnecessary console.log.
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.stories.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
Labels: Bug

#1442 Resolved Bug 1370 : Design System > Components > Login > Default > Fixed Language Dropdown
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1445 Resolved bug 1261 : Design System > Elements > Breadcrumb: - State is missing as per wireframe & compare Breadcrumb controls & UI as per Figma.
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.css
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
Labels: Bug

#1446 Users/dipak/bug 1147 design system urlforwardings required required message is not display
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.tsx
Labels: Bug

#1407 Resolved bug 1327 : Design System > Components >Dialog > Default > Cross button alignment issue.
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1444 Resolved Bug 1389 : Design System > Elements > Review Category > Center Aligned/Left Aligned Stories Profile Icon Is Enlarged Reopen issue solved
  raaghu-elements/src/rds-rating/rds-rating.tsx
Labels: Bug

#1453 Resolved Bug 823: Design System > Create color variants for toast elements.
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#1454 Resolved Bug 1341: Design System > Component > Forgot Password / Copy Text > Default > Text alignment issue
  raaghu-components/src/rds-comp-copy-text/rds-comp-copy-text.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
Labels: Bug

#1550 Completed Task 1487: Design System Element Card Enhancement as per Figma Design Kit
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Task, Enhancement

#1534 Completed task 1402 : Design System > Component > Enhancement in Tree structure.
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.stories.tsx
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.tsx
Labels: Enhancement

#1528 Completed Task 1472 Design System > Elements > Progress Bar > Enhancement as per Figma Design
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.stories.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
Labels: Task, Enhancement

#1506 Completed task 1463: Elements > Button > Enhancement as per Figma Design
  raaghu-elements/src/rds-badge/rds-badge.stories.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
Labels: Task, Enhancement

#1469 Completed task-1461: Design System > Elements > Alert > Enhancement as per Figma Design
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Task, Enhancement

#1516 Completed task 1460 : Design System > Element > Checkbox > Enhancement as per design Kit.
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
Labels: Enhancement

#1526 Resolved Task 1491 : Dropdown Enhancement as Per Figma Design Kit
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Task

#1464 Completed task 1456 : Design System > Element >Breadcrumb > Enhancement as per design Kit.
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
Labels: Task

#1510 Bug 1508: Resolved Issue Design System > Component > Contribution > Enhancement as per Figma Design
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.stories.tsx
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx
Labels: Enhancement

#1562 Completed task 1290 : Top navigation Enhancement as per figma
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: Enhancement

#1498 Resolved Bug 823: Design System > Create color variants for toast elements.
  raaghu-elements/src/rds-toast/rds-toast.css
Labels: Bug

#1570 Resolved Bug 1542: Design System Component Alert Popup
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
Labels: Bug

#1574 Resolved Bug 1543: Design System Component Api resource basic Spacing between two fields is inconsistent
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
Labels: Bug

#1578 Resolved Bug 1532: Design System Component Top Navigation Overlapping issue
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: Bug

#1465 Completed task 1458 : Design System > Element > Text Editor > Enhancement as per design Kit.
  raaghu-elements/src/rds-text-editor/rds-text-editor.stories.tsx
  raaghu-elements/src/rds-text-editor/rds-text-editor.tsx
  raaghu-react-themes/src/styles/quillEditor.scss
Labels: Task

#1466 Completed task 1459 : Design System > Element > Video Player > Enhancement as per design Kit
  raaghu-elements/src/rds-video-player/rds-video-player.stories.tsx
  raaghu-elements/src/rds-video-player/rds-video-player.tsx
Labels: Task

#1592 Completed Task 1588 : Enhanced Version In Sidebar
  .storybook/main.ts
Labels: Enhancement

#1591 Resolved Bug 1440: Resolved Issue on Element > AI prompt Box > Broken image is displayed.
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
Labels: Bug

#1502 Resolved bug 1261 : Design System > Elements > Breadcrumb: - State is missing as per wireframe & compare Breadcrumb controls & UI as per Figma
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1589 Completed Task 1452 : Design System > Component > Top Navigation >Enhancement as per design kit.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: Enhancement

#1584 Completed task 1460 : Design System > Element > Checkbox > Enhancement as per design Kit.
  raaghu-elements/src/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-react-themes/src/styles/checkbox.scss
Labels: Enhancement

#1577 Completed Task 1402 : Design System > Component > Enhancement in Tree structure.
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.stories.tsx
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.tsx
Labels: Enhancement

#1566 Completed task 1475 : Design System > Element > Scroll Bar > Enhancement as per design Kit.
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-scroll-bar/index.ts
  raaghu-elements/src/rds-scroll-bar/rds-scroll-bar.scss
  raaghu-elements/src/rds-scroll-bar/rds-scroll-bar.stories.tsx
  raaghu-elements/src/rds-scroll-bar/rds-scroll-bar.tsx
Labels: Enhancement

#1524 Completed task 1474 : Design System > Element > Rating > Enhancement as per design Kit.
  raaghu-elements/src/rds-rating/rds-rating.css
  raaghu-elements/src/rds-rating/rds-rating.stories.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
Labels: Enhancement

#1567 Resolved Task 1514 : Grid Enhansement As Per Figma Kit
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
Labels: Enhancement

#1503 Completed task 1473 : Design System > Component > Review > Enhancement as per design Kit.
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
Labels: Enhancement

#1500 Completed task 708 : Design System > Element > Counter > Enhancement as per the Figma Design.
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Enhancement

#1564 Completed Task 790 : Design System > Elements > Enhancements in Tabs
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
Labels: Task, Enhancement

#1533 Completed Task 1482: Design System Element Text area Enhancement as per design Kit
  raaghu-elements/src/rds-text-area/rds-text-area.css
  raaghu-elements/src/rds-text-area/rds-text-area.stories.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Task, Enhancement

#1509 Completed Task 1480, 1488 and 1489: Design System > Element > Spinner > Enhancement as per Figma Design Kit and Design System > Element > Dialog > Enhancement as per Figma Design Kit and Design System > Element > Date Picker > Enhancement as per Figma Design Kit
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.stories.tsx
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-spinner/rds-spinner.stories.tsx
  raaghu-elements/src/rds-spinner/rds-spinner.tsx
Labels: Task, Enhancement

#1579 Completed Task 1476 and 1557: Design System Element Slider Enhancement as per design Kit and Elements Video Player Not able to see full video in large and small view
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-slider/index.ts
  raaghu-elements/src/rds-slider/rds-slider.scss
  raaghu-elements/src/rds-slider/rds-slider.stories.tsx
  raaghu-elements/src/rds-slider/rds-slider.tsx
  raaghu-elements/src/rds-video-player/rds-video-player.css
  raaghu-elements/src/rds-video-player/rds-video-player.tsx
Labels: Task, Enhancement

#1586 Completed Task 1290 : Design System > Components > Top Navigation > Solved UI Alignment Issues.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
Labels: Enhancement

#1572 Resolved Bug 1554 : Design System > Elements > Toast > Not able to see text in dark theme and UI issue
  raaghu-react-themes/src/styles/toast.scss
Labels: Bug

#1559 Completed task 1536 > Element > Avatar > Enhancement as per Figma Design Kit
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.tsx
Labels: Enhancement, Figma

#1571 Resolved Bug 1555 : Design System > Elements > Toggle > "O" Is Hidden In Toggle
  raaghu-elements/src/rds-toggle/rds-toggle.css
Labels: Bug

#1587 Completed task 1535 > Element > Accordion > Enhancement as per Figma Design Kit
  raaghu-elements/src/rds-accordion/rds-accordion.css
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
Labels: Enhancement, Figma

#1580 Resolved Bug 1549: Design System > Elements > Stepper > Not able to see dash in dark theme and missing check boxes
  raaghu-elements/src/rds-stepper/rds-stepper.css
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
Labels: Bug

#1594 Resolved Task 1590 : Alert and Progress Bar Testing in App.tsx
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
Labels: Task

#1517 Resolved Bug 1507: Resolved Issue on Design System > Elements > input > Enhancement as per Figma Design.
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Enhancement

#1523 Resolved Bug 1522: Resolved Issue on Elements > Empty State > Enhancement as per Figma Design
  raaghu-elements/src/rds-illustration/rds-illustration.stories.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.tsx
Labels: Enhancement

#1501 Resolved Task 1481 : Design System > Element > Switch or Toggle > Enhancement as per Figma Design Kit
  raaghu-elements/src/rds-toggle/rds-toggle.css
  raaghu-elements/src/rds-toggle/rds-toggle.stories.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/toggle.scss
Labels: Task

#1568 Resolved bug 1511: Components > Data Table > Enhancement as per Figma Design
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-elements/src/rds-badge/rds-badge.tsx
Labels: Documentation, Enhancement

#1585 Completed Task 1456 : BreadCrumb Element Enhansement As Per Figma Design.
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
Labels: Enhancement

#1529 Resolved Task 1486 : Truncated Text Enhancement as Per Figma Design Kit
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.css
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.stories.tsx
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.tsx
Labels: Task

#1531 Resolved Task 1483 : Design System > Element > Toast > Enhancement as per Design Kit
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/toast.scss
Labels: Task

#1538 Bug 1513: Resolved Issue on Element > Enhancement in file uploader.
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-react-themes/src/styles/file-uploader.scss
Labels: Enhancement

#1563 Resolved Task 1492 : Design System > Element > Multilevel Menu > Enhancement as per Figma Design Kit
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-multilevel-menu/index.ts
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.stories.tsx
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.tsx
  raaghu-react-themes/src/styles/accessible.scss
  raaghu-react-themes/src/styles/blue.scss
  raaghu-react-themes/src/styles/default.scss
  raaghu-react-themes/src/styles/green.scss
  raaghu-react-themes/src/styles/multilevel-menu.scss
  raaghu-react-themes/src/styles/orange.scss
Labels: Task

#1575 Resolved Task 1490 : Design System > Element > Chat > Enhancement as per Figma Design Kit
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-chat/index.ts
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-chat/rds-chat.stories.tsx
  raaghu-elements/src/rds-chat/rds-chat.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Task
