Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-03, with the labels that each got.

#1599 Resolved Bug 1327 : Resolved Polls-Option Error Issue While Click on Control
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
Labels: Bug

#1601 Completed Task: Check dependencies of elements and check props according to that
  raaghu-components/src/rds-comp-account-external-provider/rds-comp-account-external-provider.tsx
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-add-member/rds-comp-add-member.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
  raaghu-components/src/rds-comp-assistance/rds-comp-assistance.tsx
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-contact-information/rds-comp-contact-information.tsx
  raaghu-components/src/rds-comp-contact-us/rds-comp-contact-us.tsx
  raaghu-components/src/rds-comp-database-connection/rds-comp-database-connection.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-email/rds-comp-email.tsx
  raaghu-components/src/rds-comp-feature-management/rds-comp-feature-management.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-components/src/rds-comp-feeds/rds-comp-feeds.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-forms-response/rds-comp-forms-response.tsx
  raaghu-components/src/rds-comp-forms-setting/rds-comp-forms-setting.tsx
  raaghu-components/src/rds-comp-get-assistance/rds-comp-get-assistance.tsx
  raaghu-components/src/rds-comp-identity-client-basic/rds-comp-identity-client-basic.tsx
  raaghu-components/src/rds-comp-identity-ldap-management/rds-comp-identity-ldap-management.tsx
  raaghu-components/src/rds-comp-identity-management-new/rds-comp-identity-management-new.tsx
  raaghu-components/src/rds-comp-identity-oauth-management/rds-comp-identity-oauth-management.tsx
  raaghu-components/src/rds-comp-identiy-resource-basic/rds-comp-identiy-resource-basic.tsx
  raaghu-components/src/rds-comp-language/rds-comp-language.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-menu/rds-comp-menu.tsx
  raaghu-components/src/rds-comp-other-settings/rds-comp-other-settings.tsx
  raaghu-components/src/rds-comp-permission-tree/rds-comp-permission-tree.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-premium-support/rds-comp-premium-support.tsx
  raaghu-components/src/rds-comp-product-image/rds-comp-product-image.tsx
  raaghu-components/src/rds-comp-profile/rds-comp-profile.tsx
  raaghu-components/src/rds-comp-purchase-developer-seats/rds-comp-purchase-developer-seats.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-components/src/rds-comp-role/rds-comp-role.tsx
  raaghu-components/src/rds-comp-scope-basic-resource/rds-comp-scope-basic-resource.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-components/src/rds-comp-tenant-information/rds-comp-tenant-information.tsx
  raaghu-components/src/rds-comp-tenant-management/rds-comp-tenant-management.tsx
  raaghu-components/src/rds-comp-tenant-settings/rds-comp-tenant-settings.tsx
  raaghu-components/src/rds-comp-testimonials/rds-comp-testimonials.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.tsx
  raaghu-components/src/rds-comp-user-basics/rds-comp-user-basics.tsx
  raaghu-components/src/rds-comp-user-management/rds-comp-user-management.tsx
  raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/__tests__/rds-carousel.test.tsx
  raaghu-elements/__tests__/rds-checkbox.test.tsx
  raaghu-elements/__tests__/rds-notification.test.tsx
  raaghu-elements/__tests__/rds-offcanvas.test.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
  raaghu-elements/src/rds-select-list/components/option.tsx
Labels: Enhancement

#1602 Resolved Bug : Change Props Name As Per Relevant Props
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-forms-question/rds-comp-forms-questions.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-top-navigation/multi-level-dropdown.tsx
  raaghu-elements/__tests__/rds-chart-area.test.tsx
  raaghu-elements/__tests__/rds-toast.test.tsx
  raaghu-elements/__tests__/rds-toggle.test.tsx
  raaghu-elements/__tests__/rds-tooltip.test.tsx
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-slider/rds-slider.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.tsx
Labels: Bug

#1603 Completed Task : changed props name as per relevant props
  raaghu-components/src/rds-comp-permission-tree-new/rds-comp-permission-tree-new.tsx
  raaghu-components/src/rds-comp-register-member/rds-comp-register-member.tsx
  raaghu-components/src/rds-comp-tenant-register/rds-comp-tenant-register.tsx
  raaghu-elements/__tests__/rds-checkbox.test.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
Labels: Bug

#1604 Completed Task : dropdown button changed props as per relevant props.
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Bug

#1606 Resolved bug 1477 : Design System > Elements > Side navigation > enum changes
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
Labels: Bug

#1608 Completed Task : breadcrumb props and top navigation offcanvas issue.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: Bug

#1609 Issues Found while running dependencies locally
  raaghu-elements/__tests__/rds-input.test.tsx
  raaghu-elements/__tests__/rds-progress-bar.test.tsx
  raaghu-elements/__tests__/rds-radio-button.test.tsx
Labels: Bug

#1610 Resolved Bug : Datatable & File Uploader Change Props Name As Per Relevant Props
  raaghu-components/src/rds-comp-apply-for-position/rds-comp-apply-for-position.tsx
  raaghu-components/src/rds-comp-billing/rds-comp-billing.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.tsx
  raaghu-components/src/rds-comp-claims/rds-comp-claims.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.stories.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-dynamic-properties/rds-comp-dynamic-properties.tsx
  raaghu-components/src/rds-comp-edition-list/rds-comp-edition-list.tsx
  raaghu-components/src/rds-comp-fileUploader/rds-comp-fileUploader.tsx
  raaghu-components/src/rds-comp-login-attempts/rds-comp-login-attempts.tsx
  raaghu-components/src/rds-comp-pages/rds-comp-pages.tsx
  raaghu-components/src/rds-comp-polls-option/rds-comp-polls-option.tsx
  raaghu-components/src/rds-comp-profile-picture/rds-comp-profile-picture.tsx
  raaghu-components/src/rds-comp-properties/rds-comp-properties.tsx
  raaghu-components/src/rds-comp-security-logs/rds-comp-security-logs.tsx
  raaghu-components/src/rds-comp-tenant-list/rds-comp-tenant-list.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.tsx
  raaghu-components/src/rds-comp-user-table/rds-comp-user-table.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
Labels: Bug

#1607 Resolved Task 1539 : Application Shell Enhancement As Per Figma Design Kit
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
Labels: Task

#1611 Completed Task : Skeleton added enum and changed props as per relevant props.
  raaghu-components/src/rds-comp-skeleton/rds-comp-skeleton.tsx
  raaghu-elements/src/rds-skeleton/rds-skeleton.stories.tsx
  raaghu-elements/src/rds-skeleton/rds-skeleton.tsx
Labels: Task

#1612 Resolved Bug : Resolve Props Related Changes
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/src/rds-comp-pages/rds-comp-pages.stories.tsx
  raaghu-elements/__tests__/rds-button.test.tsx
  raaghu-elements/__tests__/rds-color-picker.test.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-layouts/src/rds-comp-app-shell/shell-layout.ts
Labels: Bug

#1616 Resolved Bug : Testing Card Element On Application
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: Bug

#1617 Completed Task : Component Organization Tree app.tsx file testing.
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.css
  raaghu-pages/src/App.tsx
Labels: Task

#1621 Completed Unit Testing Changes: Design System Time Picker Elements as per Figma Design Kit.
  raaghu-elements/src/rds-time-picker/rds-time-picker.css
Labels: Bug

#1623 Completed Unit Testing Changes: Design System Toast Elements as per Figma Design Kit.
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#1626 Resolved bug 1620 : Design System > Components > Issues identified during Unit Testing of Slider, Text Editor, Tabs, Text Area, Video Player.
  raaghu-elements/src/rds-slider/rds-slider.scss
  raaghu-elements/src/rds-slider/rds-slider.stories.tsx
  raaghu-elements/src/rds-slider/rds-slider.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
  raaghu-react-themes/src/styles/quillEditor.scss
Labels: Bug

#1624 Resolved Bug 1618 : Fix Issues Identified During Unit Testing
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/toggle.scss
Labels: Bug

#1627 Bug 1495: Resolved Issue on Design System > Element > Radio > Enhancement as per Figma Design Kit
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-radio-button/rds-radio-button.stories.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Enhancement

#1613 Completed Unit Testing Changes: Design System Carousel Elements as per Figma Design Kit
  raaghu-elements/src/rds-carousel/rds-carousel.css
  raaghu-elements/src/rds-carousel/rds-carousel.stories.tsx
  raaghu-elements/src/rds-carousel/rds-carousel.tsx
Labels: Bug

#1625 Completed Unit Testing Table Responsiveness Changes: Design System Card Elements as per Figma Design Kit
  raaghu-elements/src/rds-card/rds-card.stories.tsx
Labels: Bug

#1629 Resolved Bug 1471 : Off Canvas Enhancement As Per Figma Design Kit.
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-react-themes/src/styles/offcanvas.scss
Labels: Bug

#1628 Resolved unit testing bug: Updated design system side navigation elements as per Figma Design Kit
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: Bug

#1630 Resolved Notification Issue and Unit Testing
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
Labels: Enhancement

#1634 Completed Task : Build issue error resolved.
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-elements/src/rds-divider/rds-divider.figma.tsx
  raaghu-elements/src/rds-slider/rds-slider.figma.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Task

#1632 Resolved Bug 1494 : Popover Enhancement As Per Figma Design & Add Enum
  raaghu-elements/src/rds-popover/rds-popover.css
  raaghu-elements/src/rds-popover/rds-popover.stories.tsx
  raaghu-elements/src/rds-popover/rds-popover.tsx
Labels: Bug

#1636 Completed Task : Resolved build issue.
  raaghu-elements/__tests__/rds-popover.test.tsx
  raaghu-elements/src/rds-popover/rds-popover.figma.tsx
Labels: Task

#1635 Completed Unit Testing Changes: Design System Top Nav Elements as per Figma Design Kit.
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1640 Completed Task 1620 : Design System > Components > Issues identified during Unit Testing of Slider, Text Editor, Tabs, Text Area, Video Player.
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.figma.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
Labels: Task

#1661 Completed bug 1649 & 1653 : Design System > Component > Shopping cart > Missing text and dropdown icon & Design System > Component > Theme > Dark theme > Selected values are not displayed.
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1664 Resolved Bug 1639, 1650 & 1655 : Resolved UI Issues & Add Missing Buttons
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
  raaghu-components/src/rds-comp-edition/rds-comp-edition.tsx
  raaghu-components/src/rds-comp-email-settings/rds-comp-email-settings.tsx
  raaghu-components/src/rds-comp-forms-basic/rds-comp-forms-basic.tsx
  raaghu-components/src/rds-comp-information/rds-comp-information.tsx
  raaghu-components/src/rds-comp-invoice/rds-comp-invoice.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-teams/rds-comp-teams.stories.tsx
  raaghu-components/src/rds-comp-user-permission/rds-comp-user-permission.tsx
Labels: Bug

#1666 Resolved Bug Ui Issues
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-claim-type/rds-comp-claim-type.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1671 Completed bug 1649 & 1653 : Design System > Component > Shopping cart > Missing text and dropdown icon & Design System > Component > Theme > Dark theme > Selected values are not displayed.
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1676 Completed bug 1675 : Design System > Elements > Big Number > Big Number color is duplicate white & light.
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
Labels: Bug

#1679 Resolved Bug 1641 : The button position is not fixed before and after deleting the record for cache component.
  raaghu-components/src/rds-comp-cache/rds-comp-cache.css
  raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
Labels: Bug

#1678 Completed bug 1672 : Design System > Elements > Fab Menu > After click on fab menu button is not display.
  raaghu-elements/src/rds-input-group/rds-input-group.stories.tsx
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-react-themes/src/styles/dropdown.scss
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1680 Completed bug 1670 : Design System > Elements > Charts > Stacked Chart > Change size of preview showing error message.
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.tsx
Labels: Bug

#1686 Completed Bug 1651 : Design System > Component > Tenant dashboard > Card height is inconsistent.
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
Labels: Bug

#1687 Resolved Bug 1667 : Design System > Elements > Stepper > Block > The UI changes in the dark theme
  raaghu-elements/src/rds-stepper/rds-stepper.css
Labels: Bug

#1684 Bug 1683: Resolved Issue on Design System > Benefit > In interface define proper structure for item.
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.stories.tsx
  raaghu-components/src/rds-comp-benefit/rds-comp-benefit.tsx
  raaghu-elements/src/rds-bank-card-detail/rds-bank-card-detail.tsx
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
  raaghu-elements/src/rds-banner/rds-banner.tsx
Labels: Bug

#1690 Resolved Code Connect Changes Of Contribution , Datatable , Carousel , Chat , ColorPciker and Counter.
  raaghu-components/.env
  raaghu-components/package.json
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.css
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.figma.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.figma.tsx
  raaghu-elements/src/rds-card/rds-card.figma.tsx
  raaghu-elements/src/rds-carousel/rds-carousel.css
  raaghu-elements/src/rds-carousel/rds-carousel.figma.tsx
  raaghu-elements/src/rds-chat/rds-chat.figma.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.css
  raaghu-elements/src/rds-color-picker/rds-color.figma.tsx
  raaghu-elements/src/rds-counter/rds-counter.figma.tsx
Labels: Task

#1717 Resloved Task For Code Connect Of Alert-Popup, Divider, Input, Multilevel-Menu, Off-Canvas, Popover and Progress-bar Elements.
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.figma.tsx
  raaghu-elements/src/rds-divider/rds-divider.figma.tsx
  raaghu-elements/src/rds-input/rds-input.figma.tsx
  raaghu-elements/src/rds-modal/rds-modal.figma.tsx
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.figma.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.figma.tsx
  raaghu-elements/src/rds-popover/rds-popover.tsx
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.figma.tsx
Labels: Task

#1719 Completed Task 1696: Design System > Component > Create new component Message Box as per design
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-message-box/index.ts
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.css
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.stories.tsx
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.tsx
Labels: Task, Enhancement

#1723 Completed Task 1692: Design System > Component > Create new component Typing Section as per design [Chat]
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-typing-section/index.ts
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.stories.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Task

#1728 Completed Task 1693 : Design System > Component > Create new component Attachment as per design [Chat].
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-attachement/index.ts
  raaghu-elements/src/rds-attachement/rds-attachement.css
  raaghu-elements/src/rds-attachement/rds-attachement.stories.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Enhancement

#1733 Completed Task 1704: Design System > Component > Create new component Tabs- Free & Premium as per design [Chat]
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-plan-switcher/index.ts
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.css
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.stories.tsx
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.tsx
Labels: Task

#1732 Resolved Task 1698 : Design System > Component > Create new component Profile Dropdown as per design [Chat]
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-profile-dropdown/index.ts
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.css
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.stories.tsx
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.tsx
Labels: Task

#1735 Completed Task 1703 : Design System > Component > Create new component Subscription Plan as per design [Chat]
  .storybook/assets/AIPunditColored.png
  .storybook/assets/Panel-0421.png
  .storybook/assets/backGif.gif
  .storybook/assets/check.png
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-subscription-plan/index.ts
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.css
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.tsx
Labels: Task

#1737 Completed Task 1695 : Design System > Component > Create new component Header as per design [Chat].
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-chat-header/index.ts
  raaghu-elements/src/rds-chat-header/rds-chat-header.css
  raaghu-elements/src/rds-chat-header/rds-chat-header.stories.tsx
  raaghu-elements/src/rds-chat-header/rds-chat-header.tsx
Labels: Task

#1736 Resolved Task - Create Toggle Theme
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-theme-toggle/index.ts
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.css
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.stories.tsx
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.tsx
Labels: Task

#1742 Completed bug : Header Component dark theme not showing properly.
  raaghu-elements/src/rds-chat-header/rds-chat-header.css
Labels: Bug

#1745 Completed Responsiveness for message box
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.css
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.tsx
Labels: Bug

#1747 Resolved bug : Added Attachement element props.
  raaghu-elements/src/rds-attachement/rds-attachement.css
  raaghu-elements/src/rds-attachement/rds-attachement.stories.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.tsx
Labels: Bug

#1749 Completed Task 1691 : Design System > Component > Create new component AI Chat Bot as per design [Chat]
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-ai-chat-bot/index.ts
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.css
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.tsx
Labels: Task

#1750 Resolved Task 1699 : Design System > Component > Create new component Sorting Dropdown as per design [Chat]
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-sorting-dropdown/index.ts
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.css
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.stories.tsx
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.tsx
Labels: Task

#1752 Completed UI Issues
  raaghu-components/src/rds-comp-side-navigation/rds-comp-side-navigation.tsx
  raaghu-elements/src/rds-carousel/rds-carousel.css
  raaghu-elements/src/rds-carousel/rds-carousel.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.tsx
Labels: Bug

#1753 Resolved Bug : Element Attachment Image and Url issue.
  raaghu-elements/src/rds-attachement/rds-attachement.stories.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.tsx
  raaghu-elements/src/rds-fab-menu/rds-fab-menu.tsx
Labels: Bug

#1746 Issue 1701: Resolved Issue on Design System > Component > Create new component Side Bar as per design [Chat].
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-bar/index.ts
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
Labels: Task, Enhancement

#1761 Resolved Task 1702 - Create New Component Output
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.css
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-output/index.ts
  raaghu-elements/src/rds-output/rds-output.css
  raaghu-elements/src/rds-output/rds-output.stories.tsx
  raaghu-elements/src/rds-output/rds-output.tsx
Labels: Task

#1765 Resolved Bug : Enhancement unit testing find issue.
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.css
Labels: Bug

#1766 Resolved Bug - Enhansement Unit Testing Find Issue In Profile Dropdown
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.css
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.tsx
Labels: Bug

#1768 Completed Unit testing Issues
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.css
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.tsx
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.css
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.tsx
Labels: Bug

#1767 Resolved Task 1479 : Design System > Element > Confirmation Popup > Enhancement as per Figma Design Kit
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-button-grid/rds-button-grid.css
  raaghu-elements/src/rds-button-group/rds-button-group.css
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
  raaghu-elements/src/rds-confirmation-popup/index.ts
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.css
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.stories.tsx
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.tsx
Labels: Bug

#1769 Resolved Bug Change CSS Name in Output Element
  raaghu-elements/src/rds-output/rds-output.css
  raaghu-elements/src/rds-output/rds-output.tsx
Labels: Bug

#1772 Resolved Bug 1744: Design System > Elements > Notification > Space is missing in between Notification Title and time
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.tsx
Labels: Bug

#1775 Resolved Bug - Css Related Issue in Typing Section And AI Chat Bot
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
Labels: Bug

#1777 Resolved Bug : Enhancement unit testing issue.
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.css
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
Labels: Bug

#1781 Resolved bug 1672 : Design System > Elements > Fab Menu > After click on fab menu button is not display.
  raaghu-elements/src/rds-attachement/rds-attachement.css
  raaghu-elements/src/rds-attachement/rds-attachement.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1783 Resolved Bug 1618 : CSS Override Issue on Toggle
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.css
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.tsx
Labels: Bug

#1786 Resolved Bug :1721 Design System Component Feature list Text alignment issue in small mobile
  raaghu-elements/src/rds-feature-list/rds-feature-list.tsx
Labels: Bug

#1787 Bug 1701: Resolved Issue on Component > Create new component Side Bar as per design
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
Labels: Bug

#1792 Resolved Unit testing issues on off canvas and chatbot elements
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: Bug

#1794 Resolved Bug - Change in Css Typing Section
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
Labels: Bug

#1795 Resolved Bug 1667 : Stepper UI Issues on Dark Theme
  raaghu-elements/src/rds-stepper/rds-stepper.css
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
Labels: Bug

#1796 Bug 1494: Resolved Issue on Element > Popover > Enhancement as per Figma Design Kit
  raaghu-elements/src/rds-popover/rds-popover.css
  raaghu-elements/src/rds-popover/rds-popover.tsx
Labels: Bug

#1797 Resolved UI Issues
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
  raaghu-elements/src/rds-toast/rds-toast.css
Labels: Bug

#1799 Commit changes for Folder creation
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.stories.tsx
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.stories.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.stories.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.stories.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.stories.tsx
  raaghu-elements/src/rds-gradient-text-with-icon/rds-gradient-text-with-icon.stories.tsx
  raaghu-elements/src/rds-output/rds-output.stories.tsx
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.stories.tsx
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.stories.tsx
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.stories.tsx
Labels: Enhancement

#1802 Resolved Bug : Attachement Dropdown ui issue & AI Pundit Chat added one element.
  raaghu-components/src/rds-comp-chat/rds-comp-chat.stories.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.css
  raaghu-elements/src/rds-chat-header/rds-chat-header.stories.tsx
  raaghu-react-themes/src/styles/dropdown.scss
Labels: Bug

#1806 Resolved Bug 1720 - Grid Line Not Visible In Dark Theme.
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.css
  raaghu-elements/src/rds-chart-line/rds-chart-line.css
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.css
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.stories.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.css
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.css
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.css
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.stories.tsx
Labels: Bug

#1804 Resolved Bug 1718 - Ai Prompt Box Textarea and Card Issue
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
Labels: Bug

#1803 Resolved Bug 1711 : Design System > Elements > Offcanvas > Size on button is consistent.
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.stories.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.stories.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.stories.tsx
  raaghu-elements/src/rds-chat-header/rds-chat-header.stories.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.stories.tsx
  raaghu-elements/src/rds-gradient-text-with-icon/rds-gradient-text-with-icon.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-elements/src/rds-output/rds-output.stories.tsx
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.stories.tsx
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.stories.tsx
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.stories.tsx
Labels: Bug

#1810 Bug 1701: Resolved Issue on Design System > Component > Top margin issue
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
Labels: Bug

#1798 Resolved Bug :1760 Design System Component Application Workflows UI issue in small mobile view
  raaghu-components/src/rds-comp-application-workflows/rds-comp-application-workflows.tsx
Labels: Bug

#1808 Resolved bug 1729 : Design System > Elements > Radio Button > Radio Button is different than WF and More space is there in between Radio Button and Label.
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Bug

#1811 Resolved Bug -1705 Community File Widget Alignment Issue
  .storybook/assets/community_file_widget.png
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.css
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.stories.tsx
Labels: Bug

#1793 Resolved Bug :1763 Design System Component Cache Long Cache text are hidden behind delete button in mobile views
  raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx
Labels: Bug

#1809 Resolved Bug 1479, 1481 & 1486 : Alignment And Dark Theme Issues
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.css
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.css
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-elements/src/rds-truncate-text/rds-truncate-text.tsx
Labels: Bug

#1816 Resolved bug 1814 : Design System > Elements > Chat Header > Add size control.
  raaghu-elements/src/rds-chat-header/rds-chat-header.css
  raaghu-elements/src/rds-chat-header/rds-chat-header.stories.tsx
  raaghu-elements/src/rds-chat-header/rds-chat-header.tsx
Labels: Bug

#1819 Resolved Bug - Togge Theme Color And Moon Alignment
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.css
Labels: Bug

#1818 Completed Task 1692: Design System > Component > Create new component Typing Section as per design [Chat]
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
Labels: Task

#1805 Resolved bug 1294: Elements> Grid > Enhancement as per Figma Design
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Enhancement

#1817 Resolved Bug :1721 Components Faq Two scrollbar are present in small mobile view
  raaghu-components/src/rds-comp-faq/rds-comp-faq.tsx
Labels: Bug

#1820 Resolved bug 1473 : Design System > Component > Review > Enhancement as per design Kit.
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1771 Completed Task 1691 : Design System > Component > Create new component AI Chat Bot as per design [Chat]
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.css
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.stories.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.css
  raaghu-elements/src/rds-attachement/rds-attachement.tsx
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-react-themes/src/styles/responsive.scss
Labels: Task

#1825 Resolved Bug 1672 : Design System > Elements > Fab Menu > After click on fab menu button is not display.
  raaghu-elements/src/rds-input-group/rds-input-group.css
  raaghu-elements/src/rds-input-group/rds-input-group.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
Labels: Bug

#1827 Resolved Bug 1698 : Profile Position Change as per Figma Design Kit
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.css
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.tsx
Labels: Bug

#1826 Resolved Bug - 1725 Popover Text Alignment Issue
  raaghu-elements/src/rds-popover/rds-popover.css
  raaghu-elements/src/rds-popover/rds-popover.tsx
Labels: Bug

#1828 Resolved Multiple Ui Issues
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-elements/src/rds-scroll-bar/rds-scroll-bar.scss
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#1834 Resolved Bug : Element Checkbox is not clickable for application.
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
Labels: Bug

#1833 Resolved bug 1731 : Design System > Elements > Ratings > Colors of Unrated items is different than WF on Slider.
  raaghu-elements/src/rds-rating/rds-rating.tsx
Labels: Bug

#1837 Resolved Bug 1483 : Elements > Toast > Circle Icon & Dark Theme Should As Per The Figma Design
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#1838 Resolved Bug - 1740 Accoridon Hover Effect And Button Grid CSS Issue
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-button-grid/rds-button-grid.tsx
Labels: Bug

#1840 Resolved Bug 1492 : Multilevel Menu Dark Theme Issue
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-react-themes/src/styles/multilevel-menu.scss
Labels: Bug

#1835 Resolved Bug :1778 Design System Component Edition List is displayed in small mobile view
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
Labels: Bug

#1842 Resolved bug 1473: Design System Component Review Enhancement as per design Kit
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
Labels: Bug

#1844 Resolved bug 1784: Design System Components Address Input Alignment issue in small and large mobile views
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
Labels: Bug

#1850 Resolved Bug 1642: Design System Component Admin Dashboard Responsiveness Issue Resolved issues for Responsiveness
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1839 Resolved Bug 1549: Design System > Elements > Stepper > Not able to see dash in dark theme and missing check boxes
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
Labels: Bug

#1855 Resolved Bug 1720 - Grid Line Not Visible In Dark Theme
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.css
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.css
Labels: Bug

#1823 Resolved Bug :1790 Design System Component Features > Alignment and mobile view issues
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1854 Bug 1513: Resolved Issue on Element > File uploader >Export icon arrow should display proper and close icon should align properly.
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#1843 Resolved Bug 1780 & 1722 : Design System > Components > Feeds/File Mover > Thumb alignment issue and folder icon is missing & Design System > Components > Like and dislike > Alignment issue of like and dislike button
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.stories.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.css
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
Labels: Bug

#1859 Resolved Bug 1807 : Resolve Chat Issues
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.css
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-chat/rds-chat.stories.tsx
  raaghu-elements/src/rds-chat/rds-chat.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
Labels: Bug

#1858 Bug 1511: Resolved Issue on Design System > Components > Data Table > Enhancement as per Figma Design.
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1856 Resolved Bug 1491 : Dropdown Should Open Proper Click on Second Time
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.css
Labels: Bug

#1860 Resolved Bug 1707 : Design System > Elements >Divider >i letter in divider is not according to Figma
  raaghu-elements/src/rds-divider/rds-divider.stories.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1851 Resolved Bug 1741: Design System Elements Card Text Not Displayed in Mobile Views
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: Bug

#1861 Resolved Bug 1471 : Off Canvas > Not fixed on Prod > Cross button color issue and text is different from figma
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: Bug

#1863 Reverted Pull Request 1741: Design System Elements Card Text Not Displayed in Mobile Views
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: Invalid

#1865 Resolved bug 708 : Design System > Element > Counter > Enhancement as per the Figma Design.
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1862 Resolved Bug - AI Prompt Box Responsive issue
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
Labels: Bug

#1841 Resolved Bug 1727 - Progress Bar Percentage and Visibilty Issue
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
Labels: Bug

#1864 Resolved Bug 1741: Design System Elements Card Text Not Displayed in Mobile Views
  raaghu-elements/src/rds-big-number/rds-big-number.tsx
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: Bug
