Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-08, with the labels that each got.

#2403 Completed Task 2392 : Design System > MUI > Change theme and styling.
  raaghu-elements/rds-tabs/rds-tabs.scss
  raaghu-elements/rds-tabs/rds-tabs.stories.tsx
  raaghu-elements/rds-tabs/rds-tabs.tsx
Labels: Enhancement

#2401 Completed Task 2391: Design System > MUI > Change theme and styling
  raaghu-elements/rds-accordion/rds-accordion.scss
  raaghu-elements/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/rds-accordion/rds-accordion.tsx
  raaghu-elements/rds-alert/rds-alert.scss
  raaghu-elements/rds-alert/rds-alert.stories.tsx
  raaghu-elements/rds-alert/rds-alert.tsx
  raaghu-elements/rds-avatar/rds-avatar.scss
  raaghu-elements/rds-avatar/rds-avatar.stories.tsx
  raaghu-elements/rds-avatar/rds-avatar.tsx
  raaghu-elements/rds-badge/rds-badge.scss
  raaghu-elements/rds-badge/rds-badge.stories.tsx
  raaghu-elements/rds-badge/rds-badge.tsx
  raaghu-elements/rds-banner/rds-banner.scss
  raaghu-elements/rds-banner/rds-banner.stories.tsx
  raaghu-elements/rds-banner/rds-banner.tsx
  raaghu-elements/rds-bottom-navigation/rds-bottom-navigation.stories.tsx
  raaghu-elements/rds-bottom-navigation/rds-bottom-navigation.tsx
  raaghu-elements/rds-skeleton/rds-skeleton.scss
  raaghu-elements/rds-skeleton/rds-skeleton.stories.tsx
  raaghu-elements/rds-skeleton/rds-skeleton.tsx
  raaghu-elements/rds-slider/rds-slider.scss
  raaghu-elements/rds-slider/rds-slider.stories.tsx
  raaghu-elements/rds-slider/rds-slider.tsx
Labels: Enhancement

#2399 Resolved Task 2395 : MUI Theme & Styling Changes
  raaghu-elements/rds-popover/rds-popover.scss
  raaghu-elements/rds-popover/rds-popover.stories.tsx
  raaghu-elements/rds-popover/rds-popover.tsx
  raaghu-elements/rds-progress/rds-progress.scss
  raaghu-elements/rds-progress/rds-progress.stories.tsx
  raaghu-elements/rds-progress/rds-progress.tsx
  raaghu-elements/rds-radio/rds-radio.scss
  raaghu-elements/rds-radio/rds-radio.stories.tsx
  raaghu-elements/rds-radio/rds-radio.tsx
  raaghu-elements/rds-range/rds-range.scss
  raaghu-elements/rds-range/rds-range.stories.tsx
  raaghu-elements/rds-range/rds-range.tsx
  raaghu-elements/rds-rating/rds-rating.scss
  raaghu-elements/rds-rating/rds-rating.stories.tsx
  raaghu-elements/rds-rating/rds-rating.tsx
  raaghu-elements/rds-search/rds-search.scss
  raaghu-elements/rds-search/rds-search.stories.tsx
  raaghu-elements/rds-search/rds-search.tsx
Labels: Enhancement

#2404 Completed Task 2394 : Design System > MUI > Change theme and styling
  raaghu-elements/rds-icon-button/rds-icon-button.scss
  raaghu-elements/rds-icon-button/rds-icon-button.stories.tsx
  raaghu-elements/rds-icon-button/rds-icon-button.tsx
  raaghu-elements/rds-input/rds-input.scss
  raaghu-elements/rds-input/rds-input.tsx
  raaghu-elements/rds-list/rds-list.scss
  raaghu-elements/rds-list/rds-list.stories.tsx
  raaghu-elements/rds-list/rds-list.tsx
Labels: Task

#2407 Completed Task 2394 : Design System > MUI > Change theme and styling
  .storybook/manager.ts
  .storybook/preview.ts
  raaghu-elements/rds-list/rds-list.scss
  raaghu-elements/rds-list/rds-list.stories.tsx
  raaghu-elements/rds-list/rds-list.tsx
  raaghu-react-themes/src/index.ts
  raaghu-react-themes/src/mui-theme-adapter.ts
  raaghu-react-themes/src/scss-to-css-vars.ts
  raaghu-react-themes/src/styles/css-vars/dark-vars.scss
  raaghu-react-themes/src/styles/css-vars/light-vars.scss
  raaghu-react-themes/src/styles/main-theme.scss
  raaghu-react-themes/src/styles/themes/dark.scss
  raaghu-react-themes/src/styles/themes/darkTheme.ts
  raaghu-react-themes/src/styles/themes/index.ts
  raaghu-react-themes/src/styles/themes/lightTheme.ts
  raaghu-react-themes/src/theme-loader.ts
  raaghu-react-themes/src/theme-switcher.css
Labels: Task, Enhancement

#2408 Completed Task 2394 : Design System > MUI > Change theme and styling
  raaghu-elements/index.ts
  raaghu-elements/rds-toggle-button/rds-standalone-toggle-button.tsx
  raaghu-elements/rds-toggle-button/rds-toggle-button.scss
  raaghu-elements/rds-toggle-button/rds-toggle-button.stories.tsx
  raaghu-elements/rds-toggle-button/rds-toggle-button.tsx
Labels: Task, Enhancement

#2402 Completed Task 2393: Design System > MUI > Change theme and styling
  raaghu-elements/rds-counter/rds-counter.scss
  raaghu-elements/rds-counter/rds-counter.stories.tsx
  raaghu-elements/rds-counter/rds-counter.tsx
  raaghu-elements/rds-dialog/rds-dialog.scss
  raaghu-elements/rds-dialog/rds-dialog.stories.tsx
  raaghu-elements/rds-dialog/rds-dialog.tsx
  raaghu-elements/rds-divider/rds-divider.stories.tsx
  raaghu-elements/rds-divider/rds-divider.tsx
  raaghu-elements/rds-file-uploader/RdsFileUploaderComponents.tsx
  raaghu-elements/rds-file-uploader/RdsFileUploaderStandardView.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.scss
  raaghu-elements/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.scss
  raaghu-layouts/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.tsx
  raaghu-layouts/rds-comp-layout/renderLayoutContent.tsx
Labels: Enhancement

#2418 Completed Task 2392 : Design System > MUI > Change theme and styling.
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.scss
  raaghu-elements/rds-card/rds-card.scss
  raaghu-elements/rds-checkbox/rds-checkbox.scss
  raaghu-elements/rds-switch/rds-switch.scss
  raaghu-elements/rds-tabs/rds-tabs.scss
Labels: Enhancement

#2421 Completed Task 2392 : Design System > MUI > Change theme and styling.
  raaghu-elements/rds-table/rds-table.scss
  raaghu-elements/rds-table/rds-table.stories.tsx
  raaghu-elements/rds-table/rds-table.tsx
Labels: Task, Enhancement

#2422 Completed Task : Created Spinner Component
  raaghu-components/index.ts
  raaghu-components/rds-comp-spinner/rds-comp-spinner.scss
  raaghu-components/rds-comp-spinner/rds-comp-spinner.stories.tsx
  raaghu-components/rds-comp-spinner/rds-comp-spinner.tsx
Labels: Task

#2424 Completed Task 2392 : Design System > MUI > Change theme and styling.
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.stories.tsx
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.tsx
  raaghu-elements/rds-button/rds-button.stories.tsx
  raaghu-elements/rds-card/rds-card.scss
  raaghu-elements/rds-checkbox/rds-checkbox.scss
  raaghu-elements/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/rds-tabs/rds-tabs.scss
Labels: Enhancement

#2426 Resolved Bug : Add controls as per figma
  raaghu-elements/rds-input/rds-input.scss
  raaghu-elements/rds-input/rds-input.stories.tsx
  raaghu-elements/rds-input/rds-input.tsx
Labels: Bug

#2427 Resolved Bug : Added enum and controls as per figma
  raaghu-elements/rds-input/rds-input.stories.tsx
  raaghu-elements/rds-input/rds-input.tsx
Labels: Bug

#2429 Completed Task 2416 : Design System > MUI > Creating Components from Design Kit
  raaghu-components/index.ts
  raaghu-components/rds-comp-scrollbar/rds-comp-scrollbar.scss
  raaghu-components/rds-comp-scrollbar/rds-comp-scrollbar.stories.tsx
  raaghu-components/rds-comp-scrollbar/rds-comp-scrollbar.tsx
  raaghu-elements/rds-loader/rds-loader.stories.tsx
  raaghu-elements/rds-loader/rds-loader.tsx
  raaghu-elements/rds-tooltip/rds-tooltip.stories.tsx
  raaghu-elements/rds-tooltip/rds-tooltip.tsx
Labels: Task, Enhancement

#2435 Completed Task 2395 : Change Props as per the Figma for Code Connect
  raaghu-elements/rds-radio/rds-radio.stories.tsx
  raaghu-elements/rds-radio/rds-radio.tsx
  raaghu-elements/rds-range/rds-range.stories.tsx
  raaghu-elements/rds-range/rds-range.tsx
Labels: Enhancement

#2437 Completed Task 2416 : Design System > MUI > Creating Components from Design Kit
  .storybook/bootstrap-globals.scss
  .storybook/custom-theme.css
  .storybook/manager.ts
  .storybook/preview.ts
  docs/ARCHITECTURE_OVERVIEW.md
  docs/BOOTSTRAP_IMPLEMENTATION_GUIDE.md
  docs/LOCALIZATION_GUIDE.md
  docs/README.md
  docs/THEME_INTEGRATION_GUIDE.md
  package.json
  raaghu-components/index.ts
  raaghu-components/rds-comp-reviews/rds-comp-reviews.scss
  raaghu-components/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-components/rds-comp-reviews/review-styles.tsx
  raaghu-components/rds-comp-scrollbar/rds-comp-scrollbar.stories.tsx
  raaghu-components/rds-comp-spinner/rds-comp-spinner.stories.tsx
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.scss
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.stories.tsx
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.tsx
  raaghu-elements/rds-avatar/rds-avatar.scss
  raaghu-elements/rds-badge/rds-badge.scss
  raaghu-elements/rds-checkbox/rds-checkbox.scss
  raaghu-elements/rds-menu/rds-menu.scss
  raaghu-elements/rds-pagination/rds-pagination.scss
  raaghu-elements/rds-rating/rds-rating.scss
  raaghu-elements/rds-rating/rds-rating.tsx
  raaghu-elements/rds-tabs/rds-tabs.scss
  raaghu-elements/rds-tooltip/rds-tooltip.scss
  raaghu-pages/src/index.css
  raaghu-pages/src/main.tsx
  raaghu-react-themes/src/index.ts
  raaghu-react-themes/src/styles/custom-properties.scss
  raaghu-react-themes/tokens/design-tokens.ts
Labels: Task, Enhancement

#2438 Completed Task 2416 : Design System > MUI > Creating Components from Design Kit
  .storybook/main.ts
  raaghu-components/index.ts
  raaghu-components/rds-comp-audio-player/rds-comp-audio-player.scss
  raaghu-components/rds-comp-contribution/rds-comp-contribution.scss
  raaghu-components/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/rds-comp-scrollbar/rds-comp-scrollbar.scss
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.scss
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.stories.tsx
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.scss
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.stories.tsx
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.tsx
  raaghu-components/rds-comp-time-picker/time-picker-modes.tsx
  raaghu-components/rds-comp-time-picker/time-picker-utils.ts
  raaghu-components/rds-comp-video-player/rds-comp-video-player.scss
  raaghu-elements/rds-card/rds-card.scss
  raaghu-elements/rds-header/rds-header.scss
Labels: Task, Enhancement

#2439 Completed Task 2413 : Design System > MUI > Creating Components from Design Kit
  package.json
  raaghu-components/index.ts
  raaghu-components/rds-comp-color-picker/color-picker-components.tsx
  raaghu-components/rds-comp-color-picker/color-utils.ts
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.scss
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.stories.tsx
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.tsx
  raaghu-components/rds-comp-details-pane/details-pane-components.tsx
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.scss
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.stories.tsx
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.tsx
Labels: Task

#2444 Completed Task 2417 : Design System > MUI > Creating Components from Design Kit.
  raaghu-components/index.ts
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar-config.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.scss
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.stories.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.tsx
Labels: Enhancement

#2445 Completed Task 2417 : Design System > MUI > Creating Components from Design Kit.
  raaghu-components/index.ts
  raaghu-components/rds-comp-tree-structure/fileTypeIcons.tsx
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.scss
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.stories.tsx
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.tsx
Labels: Enhancement

#2446 Completed Task 2413: Design System > MUI > Creating Components Datepicker
  package.json
  raaghu-components/index.ts
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker-utils.tsx
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.scss
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.stories.tsx
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.tsx
Labels: Task

#2447 Completed Bug : Fixed Ui issue on Element/Component.
  .storybook/preview.ts
  raaghu-components/rds-comp-toast/rds-comp-toast.scss
  raaghu-elements/rds-button/rds-button.scss
  raaghu-elements/rds-button/rds-button.stories.tsx
  raaghu-elements/rds-button/rds-button.test.tsx
  raaghu-elements/rds-button/rds-button.tsx
  raaghu-elements/rds-switch/rds-switch.scss
  raaghu-elements/rds-switch/rds-switch.tsx
Labels: Bug

#2443 Completed Task 2412 : Create Comp from Design Kit
  raaghu-components/rds-comp-audio-player/rds-comp-audio-player.stories.tsx
  raaghu-components/rds-comp-chart-area/rds-comp-chart-area.stories.tsx
  raaghu-components/rds-comp-chart-boolean/rds-comp-chart-boolean.stories.tsx
  raaghu-components/rds-comp-chart-bubble/rds-comp-chart-bubble.stories.tsx
  raaghu-components/rds-comp-chart-doughnut/rds-comp-chart-doughnut.stories.tsx
  raaghu-components/rds-comp-chart-line/rds-comp-chart-line.stories.tsx
  raaghu-components/rds-comp-chart-mixed/rds-comp-chart-mixed.stories.tsx
  raaghu-components/rds-comp-chart-pie/rds-comp-chart-pie.stories.tsx
  raaghu-components/rds-comp-chart-polar-area/rds-comp-chart-polar-area.stories.tsx
  raaghu-components/rds-comp-chart-radar/rds-comp-chart-radar.stories.tsx
  raaghu-components/rds-comp-chart-scatter/rds-comp-chart-scatter.stories.tsx
  raaghu-components/rds-comp-chart-stacked/rds-comp-chart-stacked.stories.tsx
  raaghu-components/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/rds-comp-chat/rds-comp-chat.stories.tsx
  raaghu-components/rds-comp-chat/rds-comp-chat.tsx
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.scss
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.stories.tsx
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.tsx
  raaghu-components/rds-comp-navtabs/rds-comp-navtabs.scss
  raaghu-components/rds-comp-navtabs/rds-comp-navtabs.stories.tsx
  raaghu-components/rds-comp-navtabs/rds-comp-navtabs.tsx
Labels: Enhancement

#2448 Resolve Issue : Build command not working
  .storybook/main.ts
  .storybook/preview.ts
  index.html
  index.ts
  package.json
  raaghu-components/index.ts
  utils/performance/index.ts
  utils/quality/standards.ts
  utils/test/setup.ts
  vite.config.ts
Labels: Bug

#2440 Completed Task 2415 : Design System > MUI > Creating Components from Design Kit
  package.json
  raaghu-components/index.ts
  raaghu-components/rds-comp-map/rds-comp-map.scss
  raaghu-components/rds-comp-map/rds-comp-map.stories.tsx
  raaghu-components/rds-comp-map/rds-comp-map.tsx
  raaghu-components/rds-comp-notification/rds-comp-notification.scss
  raaghu-components/rds-comp-notification/rds-comp-notification.stories.tsx
  raaghu-components/rds-comp-notification/rds-comp-notification.tsx
Labels: Enhancement

#2452 Completed Task 2415: Design System > MUI > Creating Components from Design Kit
  package.json
  raaghu-components/index.ts
  raaghu-components/rds-comp-kanban-board/index.ts
  raaghu-components/rds-comp-kanban-board/kanban-board-helpers.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.scss
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.stories.tsx
  raaghu-components/rds-comp-kanban-board/rds-comp-kanban-board.tsx
  raaghu-components/rds-comp-off-canvas/rds-comp-off-canvas.scss
  raaghu-components/rds-comp-off-canvas/rds-comp-off-canvas.stories.tsx
  raaghu-components/rds-comp-off-canvas/rds-comp-off-canvas.tsx
Labels: Enhancement

#2449 Completed Task 2415: Design System > MUI > Creating Components from Design Kit
  raaghu-components/index.ts
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.scss
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.stories.tsx
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.tsx
Labels: Enhancement

#2461 Resolved Task 2431 : Figma Code Connect
  raaghu-elements/rds-accordion/rds-accordion.figma.tsx
  raaghu-elements/rds-accordion/rds-accordion.tsx
  raaghu-elements/rds-alert/rds-alert.figma.tsx
  raaghu-elements/rds-alert/rds-alert.tsx
  raaghu-elements/rds-app-bar/rds-app-bar.tsx
  raaghu-elements/rds-autocomplete/rds-autocomplete.figma.tsx
  raaghu-elements/rds-autocomplete/rds-autocomplete.tsx
  raaghu-elements/rds-avatar/rds-avatar.figma.tsx
  raaghu-elements/rds-badge/rds-badge.figma.tsx
  raaghu-elements/rds-card/rds-card.figma.tsx
  raaghu-elements/rds-menu/rds-menu.figma.tsx
  raaghu-elements/rds-menu/rds-menu.tsx
  raaghu-elements/rds-modal/rds-modal.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.figma.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.tsx
Labels: Task

#2462 Resolved Bug : Fixed issue on RdsElement and RdsComponent name on deployed side.
  raaghu-components/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.tsx
  raaghu-components/rds-comp-e-signature/rds-comp-e-signature.tsx
  raaghu-components/rds-comp-emoji-generator/rds-comp-emoji-generator.tsx
  raaghu-components/rds-comp-empty-state/rds-comp-empty-state.tsx
  raaghu-elements/rds-typography/rds-typography.tsx
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.tsx
Labels: Bug

#2464 Resolved Task 2431 : Figma Code Connect - Piyush
  raaghu-elements/rds-avatar/rds-avatar.figma.tsx
  raaghu-elements/rds-menu/rds-menu.figma.tsx
  raaghu-elements/rds-radio/rds-radio.figma.tsx
  raaghu-elements/rds-skeleton/rds-skeleton.figma.tsx
  raaghu-elements/rds-skeleton/rds-skeleton.tsx
Labels: Task

#2469 Resolved Task 2431 : Figma Code Connect Component
  raaghu-components/rds-comp-toast/rds-comp-toast.figma.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.figma.tsx
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.figma.tsx
  raaghu-components/rds-comp-truncate-text/rds-comp-truncate-text.figma.tsx
  raaghu-components/rds-comp-truncate-text/rds-comp-truncate-text.tsx
  raaghu-components/rds-comp-video-player/rds-comp-video-player.figma.tsx
  raaghu-elements/rds-button/rds-button.stories.tsx
  raaghu-elements/rds-modal/rds-modal.scss
  raaghu-elements/rds-modal/rds-modal.stories.tsx
  raaghu-elements/rds-modal/rds-modal.tsx
  raaghu-pages/tsconfig.app.json
  raaghu-pages/tsconfig.node.json
  tsconfig.app.json
  tsconfig.node.json
Labels: Task

#2473 Resolved Task 2431 : Figma Code Connect For Elements
  raaghu-elements/rds-counter/rds-counter.figma.tsx
  raaghu-elements/rds-counter/rds-counter.tsx
  raaghu-elements/rds-dialog/rds-dialog.figma.tsx
  raaghu-elements/rds-dialog/rds-dialog.tsx
  raaghu-elements/rds-divider/rds-divider.figma.tsx
  raaghu-elements/rds-divider/rds-divider.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.figma.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/rds-modal/rds-modal.figma.tsx
Labels: Task

#2475 Completed Task 2412 : Application Shells Enhancement
  raaghu-elements/rds-app-bar/rds-app-bar.scss
  raaghu-elements/rds-sidebar/rds-sidebar.stories.tsx
  raaghu-elements/rds-sidebar/rds-sidebar.tsx
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell-item.tsx
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.scss
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.tsx
  raaghu-layouts/rds-comp-app-shell/shell-layout.ts
  raaghu-layouts/rds-comp-layout/rds-comp-layout.stories.tsx
Labels: Enhancement

#2476 Resolved Bug : fixed UI issue on element & component and also added enum value in component.
  raaghu-components/rds-comp-toast/rds-comp-toast.stories.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar-config.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.stories.tsx
  raaghu-components/rds-comp-toolbar/rds-comp-toolbar.tsx
  raaghu-components/rds-comp-tree-structure/fileTypeIcons.tsx
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.stories.tsx
  raaghu-components/rds-comp-tree-structure/rds-comp-tree-structure.tsx
  raaghu-components/rds-comp-truncate-text/rds-comp-truncate-text.stories.tsx
  raaghu-components/rds-comp-truncate-text/rds-comp-truncate-text.tsx
  raaghu-components/rds-comp-video-player/rds-comp-video-player.stories.tsx
  raaghu-components/rds-comp-video-player/rds-comp-video-player.tsx
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.scss
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.stories.tsx
Labels: Bug

#2477 Resolved Bug : Fixed UI Issues on component and element & Build Issue
  raaghu-components/index.ts
  raaghu-components/rds-comp-kanban-board/index.ts
  raaghu-components/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/rds-comp-scrollbar/rds-comp-scrollbar.stories.tsx
  raaghu-components/rds-comp-spinner/rds-comp-spinner.stories.tsx
  raaghu-elements/rds-modal/rds-modal.stories.tsx
  raaghu-elements/rds-modal/rds-modal.tsx
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Bug

#2479 Completed Task : Added web.config file.
  .github/workflows/storybookreact.yml
  web.config
Labels: Task

#2481 Resolved Bug 2412 : Resolve Issues on Component
  raaghu-components/rds-comp-audio-player/rds-comp-audio-player.scss
  raaghu-components/rds-comp-audio-player/rds-comp-audio-player.tsx
  raaghu-components/rds-comp-chat/rds-comp-chat.tsx
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.stories.tsx
  raaghu-components/rds-comp-code-snippet/rds-comp-code-snippet.tsx
  raaghu-elements/rds-slider/rds-slider.scss
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.scss
  raaghu-layouts/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Bug

#2468 Completed Task 2410: Created Comment Box and Adaptive Card.
  .storybook/public/assets/Image1.png
  .storybook/public/assets/Image10.png
  .storybook/public/assets/Image11.png
  .storybook/public/assets/Image12.png
  .storybook/public/assets/Image2.png
  .storybook/public/assets/Image3.png
  .storybook/public/assets/Image4.png
  .storybook/public/assets/Image5.png
  .storybook/public/assets/Image6.png
  .storybook/public/assets/Image7.png
  .storybook/public/assets/Image8.png
  .storybook/public/assets/Image9.png
  .storybook/public/assets/scorecard1.png
  .storybook/public/assets/scorecard2.png
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards-helpers.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.scss
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.scss
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.stories.tsx
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.tsx
Labels: Enhancement

#2485 Resolved Task 2431 : Figma Code Connect
  raaghu-components/rds-comp-e-signature/rds-comp-e-signature-modes.figma.tsx
  raaghu-components/rds-comp-emoji-generator/rds-comp-emoji-genrator.figma.tsx
  raaghu-components/rds-comp-empty-state/rds-comp-emty-state.figma.tsx
Labels: Task

#2484 Resolved Issue : Enhance Menu element
  raaghu-elements/rds-menu/rds-menu.stories.tsx
  raaghu-elements/rds-menu/rds-menu.tsx
Labels: Enhancement

#2490 Resolved Bug : Fixed Ui issue and hide some element.
  .storybook/manager-head.html
  raaghu-elements/rds-switch/rds-switch.scss
  raaghu-elements/rds-tabs/rds-tabs.scss
Labels: Bug

#2494 Resolved Bug : Enhance button icon control.
  raaghu-elements/rds-button/rds-button.stories.tsx
  raaghu-elements/rds-button/rds-button.tsx
Labels: Bug

#2496 Completed Task : Create Button Dropdown Element
  raaghu-elements/index.ts
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.scss
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.stories.tsx
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.tsx
  raaghu-elements/rds-input/rds-input.stories.tsx
  raaghu-elements/rds-input/rds-input.tsx
  raaghu-elements/rds-menu/rds-menu.tsx
  raaghu-elements/rds-pagination/rds-pagination.stories.tsx
Labels: Task, Enhancement

#2497 Resolved issue 2413: Design System > MUI > Creating Components from Design Kit
  raaghu-components/rds-comp-color-picker/color-picker-components.tsx
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.scss
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker-utils.tsx
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.scss
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.tsx
  raaghu-components/rds-comp-details-pane/details-pane-components.tsx
  raaghu-components/rds-comp-details-pane/rds-comp-details-pane.scss
Labels: Task

#2501 Completed Task 2415: Design System > MUI > Creating Components from Design Kit
  raaghu-elements/rds-alert/rds-alert.scss
  raaghu-elements/rds-alert/rds-alert.stories.tsx
  raaghu-elements/rds-badge/rds-badge.scss
  raaghu-elements/rds-badge/rds-badge.stories.tsx
Labels: Enhancement

#2492 Completed Task : Changes the element and components
  raaghu-components/rds-comp-details-pane/details-pane-components.tsx
  raaghu-elements/rds-counter/rds-counter.scss
  raaghu-elements/rds-counter/rds-counter.stories.tsx
  raaghu-elements/rds-counter/rds-counter.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.stories.tsx
Labels: Enhancement

#2507 Completed Task 2412 : Enhancement on AI Chat Bot
  .storybook/manager-head.html
  raaghu-components/index.ts
  raaghu-components/rds-comp-ai-attachement/rds-comp-ai-attachement.scss
  raaghu-components/rds-comp-ai-attachement/rds-comp-ai-attachement.stories.tsx
  raaghu-components/rds-comp-ai-attachement/rds-comp-ai-attachement.tsx
  raaghu-components/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.scss
  raaghu-components/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.tsx
  raaghu-components/rds-comp-ai-chat-header/rds-comp-ai-chat-header.scss
  raaghu-components/rds-comp-ai-chat-header/rds-comp-ai-chat-header.stories.tsx
  raaghu-components/rds-comp-ai-chat-header/rds-comp-ai-chat-header.tsx
  raaghu-components/rds-comp-ai-fab-menu/rds-comp-ai-fab-menu.scss
  raaghu-components/rds-comp-ai-fab-menu/rds-comp-ai-fab-menu.stories.tsx
  raaghu-components/rds-comp-ai-fab-menu/rds-comp-ai-fab-menu.tsx
  raaghu-components/rds-comp-ai-gradient-text-with-icon/rds-comp-ai-gradient-text-with-icon.scss
  raaghu-components/rds-comp-ai-gradient-text-with-icon/rds-comp-ai-gradient-text-with-icon.stories.tsx
  raaghu-components/rds-comp-ai-gradient-text-with-icon/rds-comp-ai-gradient-text-with-icon.tsx
  raaghu-components/rds-comp-ai-icon/rds-comp-ai-icon.scss
  raaghu-components/rds-comp-ai-icon/rds-comp-ai-icon.stories.tsx
  raaghu-components/rds-comp-ai-icon/rds-comp-ai-icon.tsx
  raaghu-components/rds-comp-ai-message-box/rds-comp-ai-message-box.scss
  raaghu-components/rds-comp-ai-message-box/rds-comp-ai-message-box.stories.tsx
  raaghu-components/rds-comp-ai-message-box/rds-comp-ai-message-box.tsx
  raaghu-components/rds-comp-ai-typing-section/rds-comp-ai-typing-section.scss
  raaghu-components/rds-comp-ai-typing-section/rds-comp-ai-typing-section.stories.tsx
  raaghu-components/rds-comp-ai-typing-section/rds-comp-ai-typing-section.tsx
Labels: Enhancement

#2508 Resolved Bug : time picker and text editor issues
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.scss
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.stories.tsx
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.tsx
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.scss
  raaghu-components/rds-comp-time-picker/rds-comp-time-picker.tsx
  raaghu-components/rds-comp-time-picker/time-picker-modes.tsx
Labels: Bug

#2512 Completed Task 2415: Design System > MUI > Creating Components from Design Kit
  .storybook/public/assets/animation.gif
  raaghu-components/rds-comp-map/rds-comp-map.scss
  raaghu-components/rds-comp-map/rds-comp-map.stories.tsx
  raaghu-components/rds-comp-map/rds-comp-map.tsx
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.scss
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.tsx
  raaghu-elements/rds-app-bar/ProfileMenu.tsx
Labels: Bug

#2511 Completed Task and Resolved Bugs-2410: completed Issues in adaptive card and comment box components also fixed bugs in Radio button.
  .storybook/public/assets/ThreadHero.png
  .storybook/public/assets/your-logo.png
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards-helpers.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.scss
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.scss
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.stories.tsx
  raaghu-components/rds-comp-comments-box/rds-comp-comments-box.tsx
  raaghu-components/rds-comp-comments-box/rds-comp-comments-logic-combined.tsx
  raaghu-elements/rds-radio/rds-radio.scss
  raaghu-elements/rds-radio/rds-radio.stories.tsx
  raaghu-elements/rds-radio/rds-radio.tsx
Labels: Task

#2513 Resolved issue 2413: Design System > MUI > Creating Components from Design Kit
  raaghu-components/rds-comp-color-picker/color-picker-components.tsx
  raaghu-components/rds-comp-color-picker/color-utils.ts
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.scss
  raaghu-components/rds-comp-color-picker/rds-comp-color-picker.tsx
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker-utils.tsx
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.scss
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.stories.tsx
Labels: Task

#2516 Resolved issue : Dialog Docs are not visible
  raaghu-elements/rds-dialog/rds-dialog.stories.tsx
Labels: Bug

#2520 Completed Task : Code enhancement of Product tour
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.stories.tsx
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.tsx
Labels: Task

#2518 Resolved Task 2431 : Figma Code Connect New Elements And Components
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.figma.tsx
  raaghu-components/rds-comp-filter-button/rds-comp-filter-button.scss
  raaghu-components/rds-comp-filter-button/rds-comp-filter-button.stories.tsx
  raaghu-components/rds-comp-filter-button/rds-comp-filter-button.tsx
  raaghu-elements/rds-box/rds-box.tsx
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.figma.tsx
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.tsx
  raaghu-elements/rds-table/rds-table.figma.tsx
  raaghu-elements/rds-text-area/rds-text-area.figma.tsx
  raaghu-elements/rds-text-area/rds-text-area.tsx
Labels: Task

#2523 Completed Task 2415: Design System > MUI > Creating Components from Design Kit
  raaghu-components/rds-comp-notification/rds-comp-notification.scss
  raaghu-components/rds-comp-notification/rds-comp-notification.tsx
  raaghu-components/rds-comp-off-canvas/rds-comp-off-canvas.tsx
  raaghu-components/rds-comp-product-tour/rds-comp-product-tour.tsx
Labels: Bug

#2522 Resolved issue 2393: Design System > MUI > Change theme and styling.
  raaghu-elements/rds-file-uploader/RdsFileUploaderComponents.tsx
  raaghu-elements/rds-file-uploader/RdsFileUploaderStandardView.tsx
  raaghu-elements/rds-file-uploader/rds-file-uploader.scss
  raaghu-elements/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#2525 Resolved Bug : Fixed Ui Issues of Component and code enhancement of alert and banner
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.scss
  raaghu-components/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-components/rds-comp-ai-gradient-text-with-icon/rds-comp-ai-gradient-text-with-icon.stories.tsx
  raaghu-components/rds-comp-ai-gradient-text-with-icon/rds-comp-ai-gradient-text-with-icon.tsx
  raaghu-elements/rds-alert/rds-alert.tsx
  raaghu-elements/rds-banner/rds-banner.tsx
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.stories.tsx
  raaghu-elements/rds-button-dropdown/rds-button-dropdown.tsx
  raaghu-elements/rds-dialog/rds-dialog.tsx
Labels: Bug

#2527 Resolved Bug : Fixed issues on components
  raaghu-components/rds-comp-ai-gradient-text-with-icon/rds-comp-ai-gradient-text-with-icon.stories.tsx
  raaghu-components/rds-comp-ai-gradient-text-with-icon/rds-comp-ai-gradient-text-with-icon.tsx
  raaghu-components/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-components/rds-comp-spinner/rds-comp-spinner.stories.tsx
Labels: Bug

#2530 Resolved issue 2413: Design System > MUI > Creating Components from Design Kit
  raaghu-components/rds-comp-ai-message-box/rds-comp-ai-message-box.stories.tsx
  raaghu-components/rds-comp-ai-message-box/rds-comp-ai-message-box.tsx
  raaghu-components/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/rds-comp-chat/rds-comp-chat.tsx
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker-utils.tsx
  raaghu-components/rds-comp-datepicker/rds-comp-datepicker.scss
Labels: Bug

#2533 Resolved Bug : Bug Fixes of Text Editor and Time Picker Component
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.scss
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.stories.tsx
  raaghu-components/rds-comp-text-editor/rds-comp-text-editor.tsx
  raaghu-components/rds-comp-time-picker/time-picker-modes.tsx
Labels: Bug
