Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-06, with the labels that each got.

#2088 Merge Development : Latest Code from Development to Staging
  package.json
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
  raaghu-components/src/rds-comp-theme/rds-comp-theme.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.css
  raaghu-elements/src/index.ts
  raaghu-elements/src/rds-carousel/rds-carousel.css
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
  raaghu-elements/src/rds-product-tour/index.ts
  raaghu-elements/src/rds-product-tour/rds-product-tour.css
  raaghu-elements/src/rds-product-tour/rds-product-tour.stories.tsx
  raaghu-elements/src/rds-product-tour/rds-product-tour.tsx
  stories/assets/animation.gif
Labels: Deployment

#2063 Resolved Bug 1815 : Design System > Review Names of Elements & Components
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-app-detail/rds-comp-app-detail.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-url-forwardings/rds-comp-url-forwardings.stories.ts
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-button/rds-button.stories.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
  raaghu-elements/src/rds-button/rds-button.types.ts
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.stories.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
  raaghu-elements/src/rds-collapse/rds-collapse.stories.tsx
  raaghu-elements/src/rds-color-switcher/rds-color-switcher.stories.tsx
  raaghu-elements/src/rds-modal/rds-modal.stories.tsx
  raaghu-elements/src/rds-navbar/rds-navbar.stories.tsx
  raaghu-layouts/src/rds-comp-layout/rds-comp-layout.stories.tsx
Labels: Bug

#2092 Resolved Bug 1815 : Review Components of Design System
  .storybook/manager-head.html
  raaghu-components/src/rds-comp-login/rds-comp-login.stories.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.stories.tsx
  raaghu-components/src/rds-comp-order-confirmation/rds-comp-order-confirmation.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.stories.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.stories.tsx
  raaghu-components/src/rds-comp-security/rds-comp-security.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
Labels: Bug

#2095 Resolved Bug : Resolved Build Issue
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.tsx
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: Bug

#2102 Resolved Issue 2103 : Design System > Hotfix > Themes > React Image render from react-theme package
  package.json
  raaghu-react-themes/src/index.tsx
Labels: Task

#2107 Resolved Issue 2108 : Design System > Prod > Hotfix > Change for Index File for mapping Elements, Components, Themes and Layouts
  index.ts
  package.json
Labels: Bug

#2111 Resolved Bug 2109: Design System > Element > Issues in product tour
  raaghu-elements/src/rds-product-tour/rds-product-tour.css
  raaghu-elements/src/rds-product-tour/rds-product-tour.stories.tsx
Labels: Bug

#2104 Resolved Bug 2072: Design System > Component > Details Pane > Unable to see text in dark theme and UI issue
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
Labels: Bug

#2099 Resolved Bug 2096 : Design System > Readme File > Link redirection should be based on branch and not everything to be linked to "main" for production
  README.md
Labels: Bug

#2097 Resolved Bug 2096 : Design System > Readme File > Link redirection should be based on branch and not everything to be linked to "main"
  README.md
Labels: Bug

#2113 Merge Development : Latest Code From Development to Staging
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-elements/src/rds-navtabs/rds-navtabs.css
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-elements/src/rds-product-tour/rds-product-tour.css
  raaghu-elements/src/rds-product-tour/rds-product-tour.stories.tsx
Labels: Deployment

#2114 Completed Task : Npm Package Upgrade
  package.json
Labels: NPM Package

#2115 Completed Task : Npm Version Upgrade to 1.1.12
  package.json
Labels: NPM Package

#2118 Completed Task 2039 : Design System > Component > Create Adaptive Cards
  .storybook/assets/Image1.png
  .storybook/assets/Image10.png
  .storybook/assets/Image11.png
  .storybook/assets/Image12.png
  .storybook/assets/Image2.png
  .storybook/assets/Image3.png
  .storybook/assets/Image4.png
  .storybook/assets/Image5.png
  .storybook/assets/Image6.png
  .storybook/assets/Image7.png
  .storybook/assets/Image8.png
  .storybook/assets/Image9.png
  .storybook/assets/icons/dot.svg
  .storybook/assets/scorecard1.png
  .storybook/assets/scorecard2.png
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-adaptive-cards/index.ts
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.css
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Task

#2089 Resolved Bug 1982: Design System > Element > Typing Section > Enhancement as per new design
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
Labels: Bug

#2117 Resolved Bug 2109: Design System > Element > Issues in product tour
  .storybook/assets/donut_chart.gif
  raaghu-elements/src/rds-product-tour/rds-product-tour.stories.tsx
  raaghu-elements/src/rds-product-tour/rds-product-tour.tsx
Labels: Bug

#2119 Resolved Bug 1815 : Review Elements & Components Names
  raaghu-components/src/rds-comp-side-navigation1/rds-comp-side-navigation1.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.stories.tsx
Labels: Bug

#2121 Merge Development : Latest Code from Development to Staging
  .storybook/assets/Image1.png
  .storybook/assets/Image10.png
  .storybook/assets/Image11.png
  .storybook/assets/Image12.png
  .storybook/assets/Image2.png
  .storybook/assets/Image3.png
  .storybook/assets/Image4.png
  .storybook/assets/Image5.png
  .storybook/assets/Image6.png
  .storybook/assets/Image7.png
  .storybook/assets/Image8.png
  .storybook/assets/Image9.png
  .storybook/assets/donut_chart.gif
  .storybook/assets/icons/dot.svg
  .storybook/assets/scorecard1.png
  .storybook/assets/scorecard2.png
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-adaptive-cards/index.ts
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.css
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-components/src/rds-comp-side-navigation1/rds-comp-side-navigation1.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-product-tour/rds-product-tour.stories.tsx
  raaghu-elements/src/rds-product-tour/rds-product-tour.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.stories.tsx
Labels: Deployment

#2127 Resolved Bug 2120 : Design System > Component > Bank Card Detail > Docs/Bank card details > The logo does not display sometimes.
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
Labels: Bug

#2126 Resolved Bug 2122 : Design System > Element > Skeleton > UI of skeleton is not display as per WF.
  raaghu-elements/src/rds-dropdown/rds-dropdown.css
Labels: Bug

#2130 Resolved Bug 2128 : Design System > Components > Polls question > Missing input field.
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
Labels: Bug

#2132 Resolved Bug 2124 : Adaptive Cards Some Controls Not Working
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
Labels: Bug

#2131 Completed Task 2040 : Create AI chat component
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.stories.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Task

#2134 Completed Task 2040 : Added spacing and button required changes
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
Labels: Task

#2136 Resolved Bug 2133 : Design System > Elements > Progress bar >Black color is display in pending progress bar.
  raaghu-react-themes/src/styles/default.scss
Labels: Bug

#2140 Resolved issue 2138: Design system > Element > Button > Button outline issue
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
Labels: Bug

#2141 Resolved Bug 2039 : Adaptive Cards Issues
  .storybook/assets/icons/circle.svg
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.css
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
Labels: Bug

#2142 Resolved Bug 2139 : Design system > Element > Dropdown list > After selecting values from the dropdown, the text is displayed in grey color.
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#2145 Merge Development : Latest Changes from Development to Staging
  .storybook/assets/icons/circle.svg
  package.json
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.css
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-generate-code-metrics/rds-comp-generate-code-metrics.tsx
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
  raaghu-components/src/rds-comp-polls-question/rds-comp-polls-question.tsx
  raaghu-components/src/rds-comp-register/rds-comp-register.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.stories.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
  raaghu-elements/src/rds-widget/rds-widget.stories.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/default.scss
Labels: Deployment

#2148 Resolved Bug 542 : Fixed Grid Component Column Resizing Issue
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
Labels: Bug

#2147 Resolved Bug 773: Design system > There is no option in raaghu to disable datepicker & we are getting todays date as default value (we want as blank initially). While clearing the selected dates getting issue.
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
Labels: Bug

#2151 Resolved Bug 2039 : Adaptive Cards Dark Theme Text Is Not Visible
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.css
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.stories.tsx
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#2152 Resolved Bug 1821: Design System > Component > Create details panel
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
Labels: Bug

#2161 Resolved Bug 2160: Design System > Elements > Chat > Pointer Issue
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-chat/rds-chat.stories.tsx
  raaghu-elements/src/rds-chat/rds-chat.tsx
Labels: Bug

#2167 Resolved Bug 2153 : Design System > Components > AI Chat Box > Typing Section > Typed texts is displayed in primary color
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
Labels: Bug

#2163 Resolved Bug 2072 : Design System > Component > Details Pane > Unable to see text in dark theme and UI issue
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
Labels: Bug

#2172 Resolved Bug 2053 : Design System > Component > Profile Dropdown > Dark theme effect is not applied on profile dropdown list
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.css
Labels: Bug

#2178 Resolved Bugs 2174 and 2175 : Resolved Issue of Radio Button List Not Displaying and Toggle Not Working in Toggle Element
  raaghu-elements/src/rds-radio-button/rds-radio-button.stories.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#2143 Resolved Bug 2091: Design System > Element > Top Navigation Not in Proper Alignment and CSS Issue
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: Bug

#2183 Resolved Bug 828: Design System > App Shell > Add new app shell as per figma design
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Bug

#2196 Resolved Bug 2182: Design System > Icon Label and Label > Stories can be clubbed instead of keeping 2 different components
  .storybook/manager-head.html
  raaghu-elements/src/rds-icon-label/rds-icon-label.css
  raaghu-elements/src/rds-icon-label/rds-icon-label.stories.tsx
  raaghu-elements/src/rds-icon-label/rds-icon-label.tsx
Labels: Bug

#2169 Resolved Bug 2166: Design System > Components > Application Shells > One Three One > Story name need correction
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
  raaghu-layouts/src/rds-comp-app-shell/shell-layout.ts
Labels: Bug

#2197 Resolved Bug 2185: Design System > Element > Chart > Bar Chart > Not sorted alphabetically naming convention not consistent for all stories
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
Labels: Bug

#2205 Resolved Bug 2193: Design System > Element > Multiple stories related to address
  .storybook/manager-head.html
  raaghu-elements/src/rds-address-detail/rds-address-detail.css
  raaghu-elements/src/rds-address-detail/rds-address-detail.stories.tsx
  raaghu-elements/src/rds-address-detail/rds-address-detail.tsx
Labels: Bug

#2219 Resolved Bug 2210: Design System > Element > Banner > Banner icon not visible properly
  raaghu-elements/src/rds-banner/rds-banner.tsx
Labels: Bug

#2203 Resolved Bug 2200: Design System > Element > Top Navigation > Logout icon not as per figma and space missing in Language abbreviation & arrow
  .storybook/assets/icons/leave_logout.svg
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
Labels: Bug

#2224 Resolved Bug 2199 : Fixed text color issue on webhook subscription for dark theme
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.css
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#2228 Resolved Bug 2221 : Fixed tooltip display issue on widget element as per the position.
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-widget/rds-widget.stories.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#2220 Resolved Bug 2212: Design System > Elements > Grid > Default > 3 dots not displayed properly
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
Labels: Bug

#2225 Resolved Bug 2209: Design System > Element > Tag > Multi Tag Input > Close icon is larger than required
  raaghu-elements/src/rds-tag/rds-tag.tsx
Labels: Bug

#2227 Resolved Bug 2190: Design System > Elements > Stories are not listed in alphabetic order
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
Labels: Bug

#2226 Resolved bug 828: Design System > App Shell > Add new app shell as per figma design
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
Labels: Enhancement

#2230 Resolved Bug 2216: Design System > Docs > For all elements and components > Extra space is displayed at the top of the page
  raaghu-react-themes/src/styles/default.scss
Labels: Bug

#2237 Resolved Bug 2232: Design System > Elements > Confirmation pop-up > Confirmation pop-up is not in centered align
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.css
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.tsx
Labels: Bug

#2246 Resolved Bug 2241, 2242 : Design System > Elements > Component > Details pane
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-elements/src/rds-icon-label/rds-icon-label.css
Labels: Bug

#2243 Resolved Bug 2235: Design System > Elements > Offcanvas > The size of hover effect of close icon is not correct and missing hover effect in light theme
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: Bug

#2249 Merge Development : Latest Code from Development to Staging
  .storybook/assets/icons/leave_logout.svg
  .storybook/assets/icons/notification_dot.svg
  .storybook/assets/icons/sun_2.svg
  .storybook/manager-head.html
  raaghu-components/__tests__/rds-comp-dialog.test.tsx
  raaghu-components/__tests__/rds-comp-typing-section.test.tsx
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.stories.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.css
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-visual-setting/rds-comp-visual-setting.css
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.css
  raaghu-elements/src/rds-accordion/rds-accordion.stories.tsx
  raaghu-elements/src/rds-address-detail/rds-address-detail.css
  raaghu-elements/src/rds-address-detail/rds-address-detail.stories.tsx
  raaghu-elements/src/rds-address-detail/rds-address-detail.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-banner/rds-banner.tsx
  raaghu-elements/src/rds-benefit/rds-benefit.css
  raaghu-elements/src/rds-benefit/rds-benefit.tsx
  raaghu-elements/src/rds-big-number/rds-big-number.stories.tsx
  raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.css
  raaghu-elements/src/rds-confirmation-popup/rds-confirmation-popup.tsx
  raaghu-elements/src/rds-icon-label/rds-icon-label.css
  raaghu-elements/src/rds-icon-label/rds-icon-label.stories.tsx
  raaghu-elements/src/rds-icon-label/rds-icon-label.tsx
  raaghu-elements/src/rds-icon/rds-icon.stories.tsx
  raaghu-elements/src/rds-icon/rds-icon.tsx
  raaghu-elements/src/rds-loader/rds-loader.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.css
  raaghu-elements/src/rds-review-category/rds-review-category.stories.tsx
  raaghu-elements/src/rds-review-category/rds-review-category.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-tag/rds-tag.tsx
  raaghu-elements/src/rds-widget/rds-widget.stories.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.stories.tsx
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.tsx
  raaghu-layouts/src/rds-comp-app-shell/shell-layout.ts
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/colorvariables-light.scss
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/default.scss
  raaghu-react-themes/src/styles/pagination.scss
Labels: Deployment
