Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-04, with the labels that each got.

#1868 Resolved Bug 1495: Design System > Element > Radio > Radio button UI Issues
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
Labels: Bug

#1872 Merge Staging: Latest code from dev into stage for deployment
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.stories.tsx
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.css
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.figma.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-elements/libs/types/index.ts
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-big-number/rds-big-number.tsx
  raaghu-elements/src/rds-button-grid/rds-button-grid.tsx
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.css
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.css
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-chat/rds-chat.stories.tsx
  raaghu-elements/src/rds-chat/rds-chat.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-divider/rds-divider.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.css
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-elements/src/rds-toast/rds-toast.figma.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-elements/src/rds-tooltip/rds-tooltip.figma.tsx
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.figma.tsx
  raaghu-elements/src/rds-video-player/rds-video.figma.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
  raaghu-pages/tsconfig.json
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/multilevel-menu.scss
  raaghu-react-themes/src/styles/responsive.scss
  tsconfig.json
Labels: Deployment

#1885 Completed -> Raaghu React -> Merge staging into production
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.tsx
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.tsx
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-components/src/rds-comp-file-mover/rds-comp-file-mover.stories.tsx
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.css
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.figma.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.stories.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-elements/libs/types/index.ts
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-ai-prompt-box/rds-ai-prompt-box.css
  raaghu-elements/src/rds-big-number/rds-big-number.tsx
  raaghu-elements/src/rds-button-grid/rds-button-grid.tsx
  raaghu-elements/src/rds-card/rds-card.css
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.css
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.css
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-chat/rds-chat.stories.tsx
  raaghu-elements/src/rds-chat/rds-chat.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-divider/rds-divider.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.css
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.css
  raaghu-elements/src/rds-like-dislike/rds-like-dislike.tsx
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.tsx
  raaghu-elements/src/rds-navtabs/rds-navtabs.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-radio-button/rds-radio-button.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.css
  raaghu-elements/src/rds-toast/rds-toast.figma.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-elements/src/rds-tooltip/rds-tooltip.figma.tsx
  raaghu-elements/src/rds-tree-structure/rds-tree-structure.figma.tsx
  raaghu-elements/src/rds-video-player/rds-video.figma.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
  raaghu-pages/tsconfig.json
  raaghu-react-themes/src/styles/custom.scss
  raaghu-react-themes/src/styles/multilevel-menu.scss
  raaghu-react-themes/src/styles/responsive.scss
  tsconfig.json
Labels: Deployment

#1882 Resolved Task 1878 : Design System > Component > Chat > Typing Section > Update as per new design
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.css
Labels: Task, Enhancement

#1874 Bug 1522: Resolved dark theme Issue on empty state.
  raaghu-elements/src/rds-illustration/rds-illustration.css
Labels: Bug

#1886 Resolved bug 1276: Design System > Component > Webhook Subscription >Required message and alignment issue
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Bug

#1893 Merge Development: Latest code from dev to stage for deployment
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.css
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-illustration/rds-illustration.css
  raaghu-elements/src/rds-input/rds-input.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.tsx
Labels: Deployment

#1881 Resolved Bug 1495: Design System > Element > Radio > Radio button design does not match the Figma design
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
Labels: Bug

#1896 Resolved Task - Create New Spinner In Loader
  raaghu-elements/src/rds-loader/rds-loader.stories.tsx
  raaghu-elements/src/rds-loader/rds-loader.tsx
  raaghu-react-themes/src/styles/loaders.scss
Labels: Enhancement

#1866 Resolved bug 1668: Design System Elements Toast Text is not visible in dark theme
  raaghu-elements/src/rds-toast/rds-toast.tsx
Labels: Bug

#1884 Resolved bug 1784: Design System Components Address Input Responsiveness issues Not able to see last field
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
Labels: Bug

#1899 Resolved Bug:1762 Design System Component Blog Post Alignment issue in small and large mobile views
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.css
  raaghu-elements/src/rds-select-list/rds-select-list.css
Labels: Bug

#1831 Bug 1508: Resolved Issue Design System > Component > Contribution > Enhancement as per Figma Design.
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.css
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx
Labels: Bug

#1876 Resolved Bug 1341: Design System Component Forgot Password Default Text alignment issue.
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#1853 Resolved Bug - Code Connect For Button Dropdown and TopNavigation Bar
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.figma.tsx
  raaghu-elements/src/rds-counter/rds-counter.figma.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.figma.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
Labels: Bug

#1883 Resolved bug No.1543: Design System Component Api resource basic Spacing between two fields is inconsistent.
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
Labels: Bug

#1887 Resolved bug No.1708: Design System Elements Date Picker The calendar is not displaying fully
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
Labels: Bug

#1904 Resolved Bug - Avatar and Pagination Issue
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
Labels: Bug

#1901 Resolved bug 1473: Design System Component Review Enhancement as per design Kit Text is not visible in dark theme
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-elements/src/rds-rating/rds-rating.tsx
Labels: Bug

#1905 Resolved Bug 1475 : Design System > Element > Scroll Bar > Enhancement as per design Kit.
  raaghu-elements/src/rds-scroll-bar/rds-scroll-bar.tsx
Labels: Bug

#1903 Resolved bug 1709: Design System > Elements > Modal >Unable to open a new modal until the previous one is closed
  raaghu-elements/src/rds-modal/rds-modal.tsx
Labels: Bug

#1908 Merge Development: Latest code from development to staging
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-address-input/rds-comp-address-input.tsx
  raaghu-components/src/rds-comp-ai-chat-bot/rds-comp-ai-chat-bot.stories.tsx
  raaghu-components/src/rds-comp-api-resource-basic/rds-comp-api-resource-basic.tsx
  raaghu-components/src/rds-comp-blog-post-new/rds-comp-blog-post-new.tsx
  raaghu-components/src/rds-comp-blog-post/rds-comp-blog-post.css
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.css
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx
  raaghu-components/src/rds-comp-forgot-password/rds-comp-forgot-password.stories.tsx
  raaghu-components/src/rds-comp-generate-code-metrics/index.ts
  raaghu-components/src/rds-comp-generate-code-metrics/rds-comp-generate-code-metrics.css
  raaghu-components/src/rds-comp-generate-code-metrics/rds-comp-generate-code-metrics.stories.tsx
  raaghu-components/src/rds-comp-generate-code-metrics/rds-comp-generate-code-metrics.tsx
  raaghu-components/src/rds-comp-message-box/rds-comp-message-box.stories.tsx
  raaghu-components/src/rds-comp-reviews/rds-comp-reviews.tsx
  raaghu-components/src/rds-comp-subscription-plan/rds-comp-subscription-plan.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.figma.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.stories.tsx
  raaghu-elements/src/rds-attachement/rds-attachement.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.css
  raaghu-elements/src/rds-carousel/rds-carousel.css
  raaghu-elements/src/rds-carousel/rds-carousel.tsx
  raaghu-elements/src/rds-chat-header/rds-chat-header.stories.tsx
  raaghu-elements/src/rds-chat/rds-chat.css
  raaghu-elements/src/rds-chat/rds-chat.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.figma.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.figma.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.tsx
  raaghu-elements/src/rds-gradient-text-with-icon/rds-gradient-text-with-icon.stories.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-loader/rds-loader.stories.tsx
  raaghu-elements/src/rds-loader/rds-loader.tsx
  raaghu-elements/src/rds-modal/rds-modal.tsx
  raaghu-elements/src/rds-output/rds-output.stories.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
  raaghu-elements/src/rds-plan-switcher/rds-plan-switcher.stories.tsx
  raaghu-elements/src/rds-profile-dropdown/rds-profile-dropdown.stories.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-rating/rds-rating.tsx
  raaghu-elements/src/rds-scroll-bar/rds-scroll-bar.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-sorting-dropdown/rds-sorting-dropdown.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-theme-toggle/rds-theme-toggle.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.tsx
  raaghu-react-themes/src/styles/loaders.scss
Labels: Deployment

#1907 Resolved Bug 708 : Design System > Element > Counter > Enhancement as per the Figma Design. & 1226 : Design System > Elements > Counter > Counter button alignment issue.
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-elements/src/rds-counter/rds-counter.tsx
Labels: Bug

#1910 Resolved Bug 1482 and 1493: Design System Element Notification Enhancement as per Figma Design Kit and Design System Element Textarea Enhancement as per design Kit
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.stories.tsx
Labels: Task, Bug

#1912 Resolved Bug 1460 : Design System > Element > Checkbox > Enhancement as per design Kit.
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
Labels: Bug

#1911 Resolved Bug - Work on Alert Now App.tsx File Show Properly
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Bug

#1917 Bug 1233: Resolved Issue on Design system > Side nav bar > Charts and maps are not display in the element section
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.stories.tsx
  raaghu-elements/src/rds-chart-area/rds-chart-area.stories.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.stories.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.stories.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.stories.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.stories.tsx
  raaghu-elements/src/rds-map/rds-map.stories.tsx
Labels: Bug

#1918 Resolved Bug 1476 and 1488: Design System > Element > Slider > Enhancement as per design Kit and Design System > Element > Dialog > Enhancement as per Figma Design Kit
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.css
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.tsx
  raaghu-elements/src/rds-slider/rds-slider.scss
  raaghu-elements/src/rds-slider/rds-slider.stories.tsx
  raaghu-elements/src/rds-slider/rds-slider.tsx
Labels: Bug

#1919 Resolved bug No.: Design System Components Features Alignment and mobile view issues
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Bug

#1924 Merge Dev: Latest Code from development to staging
  raaghu-components/src/rds-comp-data-table/rds-comp-data-table.css
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.css
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.tsx
  raaghu-components/src/rds-comp-features/rds-comp-features.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.stories.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.css
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-elements/src/rds-chart-Pie/rds-chart-pie.stories.tsx
  raaghu-elements/src/rds-chart-area/rds-chart-area.stories.tsx
  raaghu-elements/src/rds-chart-bar/rds-chart-bar.stories.tsx
  raaghu-elements/src/rds-chart-boolean/rds-chart-boolean.stories.tsx
  raaghu-elements/src/rds-chart-bubble/rds-chart-bubble.stories.tsx
  raaghu-elements/src/rds-chart-doughnut/rds-chart-doughnut.stories.tsx
  raaghu-elements/src/rds-chart-line/rds-chart-line.stories.tsx
  raaghu-elements/src/rds-chart-mixed/rds-chart-mixed.stories.tsx
  raaghu-elements/src/rds-chart-polar-area/rds-chart-polar-area.stories.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.stories.tsx
  raaghu-elements/src/rds-chart-scatter/rds-chart-scatter.stories.tsx
  raaghu-elements/src/rds-chart-stacked/rds-chart-stacked.stories.tsx
  raaghu-elements/src/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/src/rds-counter/rds-counter.css
  raaghu-elements/src/rds-counter/rds-counter.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-map/rds-map.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-slider/rds-slider.scss
  raaghu-elements/src/rds-slider/rds-slider.stories.tsx
  raaghu-elements/src/rds-slider/rds-slider.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.stories.tsx
  raaghu-elements/src/rds-time-picker/rds-time-picker.stories.tsx
  raaghu-elements/src/rds-time-picker/rds-time-picker.tsx
  raaghu-react-themes/src/styles/responsive.scss
Labels: Deployment

#1913 Bug 1701: Resolved Issue on Hover effect is not applied sidebar icons.
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.css
  raaghu-elements/src/rds-side-bar/rds-side-bar.stories.tsx
  raaghu-elements/src/rds-side-bar/rds-side-bar.tsx
Labels: Bug

#1923 Resolved bug No.1878: Design System Component Chat Typing Section Update as per new design
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1926 Resolved Bug 1776 : Design System > Components > Database Connection/Developer Mode/ Edition Information>Radio Buttons and Checkbox Buttons Not Working Properly.
  raaghu-components/src/rds-comp-edition-information/rds-comp-edition-information.tsx
Labels: Bug

#1867 Resolved Bug 1785: Design System > Components > File Management Tree > Icons disappear in dark theme
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.css
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1931 Completed Task: Kanban Board and other Ui issues
  package.json
  raaghu-components/src/index.ts
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.css
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.stories.tsx
  raaghu-components/src/rds-comp-dialog/rds-comp-dialog.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-kanban-board/index.ts
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.css
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.stories.tsx
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.tsx
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
Labels: Task, Bug

#1932 Resolved Bug 1620 : Design System > Components > Issues identified during Unit Testing of Slider, Text Editor, Tabs, Text Area, Video Player
  raaghu-elements/src/rds-color-picker/rds-color-picker.css
  raaghu-elements/src/rds-color-picker/rds-color-picker.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
Labels: Bug

#1938 Resolved Bug 1758 and 1759 : Design System > Components > Stepper > stepper multiple issue
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
Labels: Bug

#1939 Resolved Bug 1922 - Remove Border From Pagination Dropdown Button
  raaghu-elements/src/rds-pagination/rds-pagination.tsx
Labels: Bug

#1927 Bug 1472: Resolved Issue on dark theme colorVariant is not working.
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
Labels: Bug

#1937 Bug 1463: Resolved Issue on Design System > Elements > Button > Controls are not working proper.
  raaghu-elements/src/rds-button/rds-button.css
  raaghu-elements/src/rds-button/rds-button.tsx
Labels: Bug

#1941 Resolved Bug 708 : Design System > Element > Counter > Enhancement as per the Figma Design.
  raaghu-elements/src/rds-counter/rds-counter.css
Labels: Bug

#1949 Bug 1916: Resolved Issue on Design System > Elements > Contribution > Tablet view > Contribution is not aligned in center.
  raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx
Labels: Bug

#1836 Resolved bug 1548: Design System > Elements > Side navigation > Custom Navigation Side bar right > UI issues in Side Navigation.
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-react-themes/src/styles/responsive.scss
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Bug

#1951 Resolved Bug 1928 : Design System > Time Picker > Minute dropdown issue.
  raaghu-elements/src/rds-time-picker/rds-time-picker.css
  raaghu-elements/src/rds-time-picker/rds-time-picker.tsx
Labels: Bug

#1952 Resolved bug No.1942: Design System Elements Admin Dashboard Unable to see the percentage in small mobile view
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
Labels: Bug

#1958 Resolved Bug 759-1758-1759 : Functionality and ui issue for chatbot and stepper
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.stories.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
Labels: Bug

#1959 Completed Task 1948: Design System Refactor elements and component to use enum values for, enhance Storybook documentation with code transformations
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-color-picker/rds-color-picker.stories.tsx
  raaghu-elements/src/rds-counter/rds-counter.stories.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx
  raaghu-elements/src/rds-file-uploader/rds-file-uploader.stories.tsx
  raaghu-elements/src/rds-input/rds-input.stories.tsx
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.stories.tsx
  raaghu-elements/src/rds-multilevel-menu/rds-multilevel-menu.tsx
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.stories.tsx
  raaghu-elements/src/rds-popover/rds-popover.stories.tsx
  raaghu-elements/src/rds-popover/rds-popover.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.stories.tsx
  raaghu-elements/src/rds-rating/rds-rating.stories.tsx
  raaghu-elements/src/rds-scroll-bar/rds-scroll-bar.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-skeleton/rds-skeleton.stories.tsx
  raaghu-elements/src/rds-slider/rds-slider.stories.tsx
  raaghu-elements/src/rds-spinner/rds-spinner.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.stories.tsx
  raaghu-elements/src/rds-text-area/rds-text-area.stories.tsx
  raaghu-elements/src/rds-toast/rds-toast.stories.tsx
  raaghu-elements/src/rds-toggle/rds-toggle.stories.tsx
Labels: Task, Enhancement

#1957 Resolved bug No.1878: Design System Component Chat Typing Section Update as per new design
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.css
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-components/src/rds-comp-icon-list/Icons.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
Labels: Bug

#1962 Resolved: Kanban Board UI Issues
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.css
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.stories.tsx
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.tsx
Labels: Bug

#1964 Resolved Bug 759-1758-1759 : Functionality and ui issue for chatbot and stepper
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.stories.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
Labels: Bug

#1965 Resolved bug No.1946: Design System Elements Radio Button is not displayed properly in dark theme
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
Labels: Bug

#1967 Resolved bug 1620 : Design System > Components > Issues identified during Unit Testing of Slider, Text Editor, Tabs, Text Area, Video Player
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-slider/rds-slider.scss
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
Labels: Bug

#1969 Resolved Bug 1930: Notification UI Issues
  raaghu-elements/src/rds-notification/rds-notification.tsx
Labels: Bug

#1960 Resolved bug 1944: Design System(prod) > Components > Features > Unable to see the dropdown text in dark theme
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-time-picker/rds-time-picker.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#1968 Resolved bug No.1943: Design System Components Tenant Dashboard Unable to see Profit Share percentage in small mobile view
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.css
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.tsx
Labels: Bug

#1972 Resolved bug No.1942: Design System Elements Admin Dashboard
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
Labels: Bug

#1975 Resolved bug No.1945: Design System Elements Pagination Unable to see the pagination in dark theme
  raaghu-elements/src/rds-pagination/rds-pagination.css
Labels: Bug

#1980 Deployment dev to stage design system bugs
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.stories.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.css
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-slider/rds-slider.scss
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
  raaghu-elements/src/rds-time-picker/rds-time-picker.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Deployment

#1934 Resolved bug 1849: Design System > Elements > Dropdown List > Dropdown Value is Not Searchable
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#1979 Bug 1978: Resolved Issue on Select List > Add Select All option select list
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Task

#1981 Resolved Bug 1936 : Design System > Elements > Progress Bar >Testing in app.tsx Enhancement as per Figma design.
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
Labels: Bug

#1986 Bug 1472: Resolved Issue on Design System > Elements > Progress Bar > Enhancement as per Figma Design.
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
Labels: Enhancement

#1990 Resolved Bug 1984 :- Cards > Enhance for proper training and CSS change for Reconnect to Figma
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
Labels: Bug

#1976 Bug 1514: Resolved Issue on Design System > Element > Grid > Enhancement as per Figma Design Kit.
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
Labels: Enhancement

#1991 Completed Task 1983 : Design System > Element > Explore Community > Enhancement as per new design.
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.css
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.stories.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.tsx
Labels: Enhancement

#1993 Dev to stage deployment for sprint 22
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.css
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.stories.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
Labels: Deployment

#1996 Stage to prod deployment for sprint 22
  raaghu-components/src/rds-comp-admin-dashboard/rds-comp-admin-dashboard.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.scss
  raaghu-components/src/rds-comp-chat/rds-comp-chat.stories.tsx
  raaghu-components/src/rds-comp-chat/rds-comp-chat.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.css
  raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.css
  raaghu-components/src/rds-comp-tenant-dashboard/rds-comp-tenant-dashboard.tsx
  raaghu-elements/src/rds-card/rds-card.stories.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-chart-radar/rds-chart-radar.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.css
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.stories.tsx
  raaghu-elements/src/rds-community-file-widget/rds-community-file-widget.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.css
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.stories.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-pagination/rds-pagination.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.css
  raaghu-elements/src/rds-progress-bar/rds-progress-bar.tsx
  raaghu-elements/src/rds-radio-button/rds-radio-button.css
  raaghu-elements/src/rds-select-list/rds-select-list.css
  raaghu-elements/src/rds-select-list/rds-select-list.tsx
  raaghu-elements/src/rds-slider/rds-slider.scss
  raaghu-elements/src/rds-tab-group/rds-tab-group.css
  raaghu-elements/src/rds-tab-group/rds-tab-group.stories.tsx
  raaghu-elements/src/rds-tab-group/rds-tab-group.tsx
  raaghu-elements/src/rds-time-picker/rds-time-picker.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Deployment

#1995 Resolved Bug 1897 : Design system (Prod) > Elements/Components > Error is displayed.
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
Labels: Bug

#1994 Completed Task 1971 : Design System > Components > Add enum.
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.stories.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.tsx
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.stories.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.stories.tsx
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.tsx
  raaghu-elements/__tests__/rds-banner.test.tsx
  raaghu-elements/__tests__/rds-button-group.test.tsx
  raaghu-elements/__tests__/rds-color-switcher.test.tsx
  raaghu-elements/__tests__/rds-doubleRange.test.tsx
  raaghu-elements/__tests__/rds-feature-list.test.tsx
  raaghu-elements/__tests__/rds-tag.test.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
  raaghu-elements/src/rds-banner/rds-banner.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.figma.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.stories.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
  raaghu-elements/src/rds-color-switcher/rds-color-switcher.stories.tsx
  raaghu-elements/src/rds-color-switcher/rds-color-switcher.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.stories.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.tsx
  raaghu-elements/src/rds-feature-list/rds-feature-list.stories.tsx
  raaghu-elements/src/rds-feature-list/rds-feature-list.tsx
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.tsx
  raaghu-elements/src/rds-search/rds-search.stories.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/rds-tag/rds-tag.figma.tsx
  raaghu-elements/src/rds-tag/rds-tag.stories.tsx
  raaghu-elements/src/rds-tag/rds-tag.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
Labels: Task

#1966 Resolved bug 1548: Design System Elements Side navigation
  raaghu-elements/src/rds-side-nav/rds-side-nav.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-react-themes/src/styles/responsive.scss
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Bug

#1999 Completed Task 1970 : Design System > Element > Notification > Need to implement element as per updated WF.
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
Labels: Task

#1974 Resolved bug No.1548: Design System Elements Side navigation
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
Labels: Bug

#2004 Deployment for development to staging
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.stories.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.stories.tsx
  raaghu-components/src/rds-comp-collapsible-container/rds-comp-collapsible-container.tsx
  raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx
  raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx
  raaghu-components/src/rds-comp-icon-list/rds-comp-icon-list.tsx
  raaghu-components/src/rds-comp-menus-directories/rds-comp-menus-directories.tsx
  raaghu-components/src/rds-comp-organization-tree/rds-comp-organization-tree.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.stories.tsx
  raaghu-components/src/rds-comp-otpinput/rds-comp-otpinput.tsx
  raaghu-components/src/rds-comp-top-navigation-with-search/rds-comp-top-navigation-with-search.tsx
  raaghu-components/src/rds-comp-top-navigation/rds-comp-top-navigation.tsx
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.stories.tsx
  raaghu-components/src/rds-comp-transfer-list/rds-comp-transfer-list.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.stories.tsx
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
  raaghu-elements/__tests__/rds-banner.test.tsx
  raaghu-elements/__tests__/rds-button-group.test.tsx
  raaghu-elements/__tests__/rds-color-switcher.test.tsx
  raaghu-elements/__tests__/rds-doubleRange.test.tsx
  raaghu-elements/__tests__/rds-feature-list.test.tsx
  raaghu-elements/__tests__/rds-tag.test.tsx
  raaghu-elements/src/rds-accordion/rds-accordion.css
  raaghu-elements/src/rds-accordion/rds-accordion.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.stories.tsx
  raaghu-elements/src/rds-app-detail/rds-app-detail.tsx
  raaghu-elements/src/rds-banner/rds-banner.stories.tsx
  raaghu-elements/src/rds-banner/rds-banner.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.figma.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.stories.tsx
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
  raaghu-elements/src/rds-card/rds-card.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.stories.tsx
  raaghu-elements/src/rds-checkbox-group/rds-checkbox-group.tsx
  raaghu-elements/src/rds-color-switcher/rds-color-switcher.stories.tsx
  raaghu-elements/src/rds-color-switcher/rds-color-switcher.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.stories.tsx
  raaghu-elements/src/rds-double-range/rds-double-range.tsx
  raaghu-elements/src/rds-feature-list/rds-feature-list.stories.tsx
  raaghu-elements/src/rds-feature-list/rds-feature-list.tsx
  raaghu-elements/src/rds-feed/rds-feed.stories.tsx
  raaghu-elements/src/rds-feed/rds-feed.tsx
  raaghu-elements/src/rds-icon/Icons.tsx
  raaghu-elements/src/rds-notification/rds-notification.css
  raaghu-elements/src/rds-notification/rds-notification.stories.tsx
  raaghu-elements/src/rds-notification/rds-notification.tsx
  raaghu-elements/src/rds-search/rds-search.stories.tsx
  raaghu-elements/src/rds-search/rds-search.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.css
  raaghu-elements/src/rds-side-nav/rds-side-nav.stories.tsx
  raaghu-elements/src/rds-side-nav/rds-side-nav.tsx
  raaghu-elements/src/rds-stepper/rds-stepper.tsx
  raaghu-elements/src/rds-tag/rds-tag.figma.tsx
  raaghu-elements/src/rds-tag/rds-tag.stories.tsx
  raaghu-elements/src/rds-tag/rds-tag.tsx
  raaghu-elements/src/rds-widget/rds-widget.tsx
  raaghu-react-themes/src/styles/responsive.scss
  raaghu-react-themes/src/styles/side-nav.scss
Labels: Deployment
