Repository Wai-Technologies/raaghu-react, pull requests merged in 2025-07, with the labels that each got.

#2247 Resolved Bug 2239: Design System > Component > Button Group > in dark mode checkbox, icon, and radio button groups are only visible on hover
  raaghu-elements/src/rds-button-group/rds-button-group.css
  raaghu-elements/src/rds-button-group/rds-button-group.tsx
Labels: Bug

#2262 Resolved Bug 2254: Design System > Component > Scrollspy the button labelled 'Third' is overlapping with the card information below and is not properly aligned
  raaghu-elements/src/rds-scrollspy/rds-scrollspy.css
Labels: Bug

#2267 Resolved Bug 2259 : Design System > Component > Collapse > In dark mode text is not properly displayed
  raaghu-elements/src/rds-collapse/rds-collapse.css
Labels: Bug

#2263 Resolved Bug 2256 : Design System > Component > Details pane > Selection > left border is not according to figma design
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
Labels: Bug

#2265 Resolved Bug 2255 : Design System > Stat component, the Default section content is not styled for dark mode
  raaghu-elements/src/rds-stat/rds-stat.css
Labels: Bug

#2271 Resolved Bug 2193: Design System > Element > Multiple stories related to address
  raaghu-components/src/rds-comp-address-detail/rds-comp-address-detail.stories.tsx
Labels: Bug

#2287 Resolved Bug 2277: Design System > Component > Detail Pan > Real Estate > Not aligned centrally
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
Labels: Bug

#2286 Resolved Bug 2276: Design System > Element > Off Canvas > Custome Slidout Offcanvas > Button Alignment Not Proper
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.css
  raaghu-elements/src/rds-offcanvas/rds-offcanvas.tsx
Labels: Bug

#2288 Resolved Bug 2156: Design System > Elements > Top Navigation > Profile Page Functionality Incomplete
  .storybook/assets/icons/help_new.svg
  .storybook/assets/icons/profile_new.svg
  .storybook/assets/icons/setting_new.svg
  .storybook/assets/icons/theme_new.svg
  raaghu-elements/src/rds-top-navigation/rds-top-navigation.tsx
Labels: Bug

#2294 Resolved Bug 2292 : Alert Header & Button Alignment Issue on Small & Large Mobile View
  raaghu-elements/src/rds-alert/rds-alert.css
  raaghu-elements/src/rds-alert/rds-alert.tsx
Labels: Bug

#2296 Resolved Bug 2278: Design System > Element > Empty state > Missing icon and text is not same as per WF
  .storybook/assets/icons/empty_Button.svg
  .storybook/assets/icons/empty_state_dark.svg
  .storybook/assets/icons/empty_state_light.svg
  raaghu-elements/src/rds-empty-state/rds-empty-state.stories.tsx
  raaghu-elements/src/rds-empty-state/rds-empty-state.tsx
Labels: Bug

#2309 Resolved Bug #2306, #2308: Design System > component > CMS > on responsive mode, the 'Save' button is not visible on all devices
  raaghu-components/src/rds-comp-cms/rds-comp-cms.tsx
  raaghu-components/src/rds-comp-collapse/rds-comp-collapse.css
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#2313 Resolved Bug 2311 & 2312 : Issues on Popover & Toggle Element
  raaghu-elements/src/rds-popover/rds-popover.css
  raaghu-elements/src/rds-popover/rds-popover.tsx
  raaghu-react-themes/src/styles/colorvariables-dark.scss
  raaghu-react-themes/src/styles/toggle.scss
Labels: Bug

#2317 Resolved Bug 2315: Design System > component > CookiesSection and Edition > Issue in Dark Mode
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#2326 Resolved Bug 2324 : Design System > Component > Address details > Billing > The 'Save' button remains disabled even after all fields are filled in
  raaghu-components/src/rds-comp-address-detail/rds-comp-address-detail.tsx
Labels: Bug

#2325 Resolved Bug 2320 : Components > Scrollspy > Dark Thems > Black background displayed for buttons too
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#2328 Resolved Bug 2327 : Component > Application Shells > Topnav should be behind the Sidenav
  raaghu-layouts/src/rds-comp-app-shell/rds-comp-app-shell.css
Labels: Bug

#2329 Resolved Bug 2322 & 2323 : Component > Account > Standard > Input Field Issues
  raaghu-components/src/rds-comp-account/rds-comp-account.tsx
  raaghu-components/src/rds-comp-ai-prompt-box/rds-comp-ai-prompt-box.css
  raaghu-components/src/rds-comp-navtabs/rds-comp-navtabs.css
  raaghu-components/src/rds-comp-select-list/rds-comp-select-list.css
Labels: Bug

#2321 Resolved Bug 2250: Design System > Component > Bank Card Details > The 'Set as Default' and 'Edit' options are not vertically aligned with the title
  raaghu-components/src/rds-comp-bank-card-detail/rds-comp-bank-card-detail.css
  raaghu-components/src/rds-comp-bank-card-detail/rds-comp-bank-card-detail.tsx
Labels: Bug

#2330 Resolved Bug 2277: Design System > Component > Detail Pan > Real Estate > Not aligned centrally
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
Labels: Bug

#2334 Resolved Bug 2059 : Dark Theme Issue in Docs & Calendar Text Issue
  raaghu-react-themes/src/styles/colorvariables-dark.scss
Labels: Bug

#2333 Resolved Bug 2255: Design System > Component > Stat >Default > Content is not styled for dark mode
  raaghu-components/src/rds-comp-stat/rds-comp-stat.css
Labels: Bug

#2331 Resolved Bug 828, 2190 & 2260 : Desing System > Components/ Elements > Details Pane > App shell >Stories alphabetical
  raaghu-components/src/rds-comp-big-number/rds-comp-big-number.stories.tsx
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.css
  raaghu-components/src/rds-comp-stepper/rds-comp-stepper.stories.tsx
  raaghu-elements/src/rds-top-navigation/rds-top-navigation.css
Labels: Bug

#2318 Resolved Bug 2314: Design System > Components> Typing section > not responsive for mobile view
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.css
  raaghu-components/src/rds-comp-typing-section/rds-comp-typing-section.tsx
Labels: Bug

#2337 Resolve Deployment Issue
  .storybook/main.ts
  raaghu-components/src/rds-comp-kanban-board/rds-comp-kanban-board.tsx
Labels: Bug

#2341 Resolved Build Issue
  .storybook/main.ts
Labels: Bug

#2351 Merge Development : Latest Code from Development to Staging
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  raaghu-components/src/rds-comp-big-number/rds-comp-big-number.stories.tsx
  raaghu-elements/src/rds-avatar/rds-avatar.stories.tsx
Labels: Deployment

#2339 Resolved Bug 2272 : Element/Component > Datepicker/Input/Search > The Input Field & Placeholder Sizes Differ at Smaller Sizes
  raaghu-components/src/rds-comp-select-list/rds-comp-select-list.css
  raaghu-components/src/rds-comp-select-list/rds-comp-select-list.tsx
  raaghu-elements/src/rds-datepicker/rds-datepicker.tsx
  raaghu-elements/src/rds-input/rds-input.css
  raaghu-elements/src/rds-input/rds-input.tsx
Labels: Bug

#2357 Resolved Bug 2346: Design System > Header > Selected theme name is not displayed like the selected view name
  .storybook/preview.tsx
Labels: Bug

#2358 Resolved Bug 2353 & 2054 : Issues on Alerts & Banner
  raaghu-elements/src/rds-alert/rds-alert.stories.tsx
  raaghu-elements/src/rds-alert/rds-alert.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#2335 Resolved Bug 2283, 2284 & 2289 : Design System > Component > Alert Popup > Bank card Details
  raaghu-components/src/rds-comp-alert-popup/rds-comp-alert-popup.tsx
  raaghu-components/src/rds-comp-bank-card-detail-list/rds-comp-bank-card-detail-list.css
  raaghu-react-themes/src/styles/custom.scss
Labels: Bug

#2361 Resolved Bug 2355 : Component > Login > UI issues
  raaghu-components/src/rds-comp-login/rds-comp-login.css
  raaghu-components/src/rds-comp-login/rds-comp-login.tsx
Labels: Bug

#2362 Resolved Bug 2354 : Changes for Resolve Deploy Error of Alerts
  raaghu-components/src/rds-comp-details-pane/rds-comp-details-pane.tsx
  raaghu-elements/__tests__/rds-alert.test.tsx
  raaghu-elements/src/rds-alert/rds-alert.figma.tsx
Labels: Bug

#2365 Resolved Bug 2345, 2343 : Design system > components > Empty state > top navigation
  raaghu-elements/src/rds-empty-state/rds-empty-state.stories.tsx
  raaghu-elements/src/rds-top-navigation/rds-top-navigation.stories.tsx
  raaghu-elements/src/rds-top-navigation/rds-top-navigation.tsx
Labels: Bug

#2377 Resolved Bug 2374 & 2375 : Component > Banner > Actionable Banner > Few Issues
  raaghu-components/src/rds-comp-banner/rds-comp-banner.stories.tsx
  raaghu-react-themes/src/styles/colorvariables-light.scss
Labels: Bug

#2372 Resolved Bug 2366, 2305 : Design System > Component > Dialog > Save button is not clickable > Adaptive cards > Resoposive issue
  raaghu-components/src/rds-comp-adaptive-cards/rds-comp-adaptive-cards.css
  raaghu-elements/src/rds-dialog/rds-dialog.css
  raaghu-elements/src/rds-dialog/rds-dialog.tsx
Labels: Bug

#2386 Resolved Bug 2383 : Customer Review > % Icon is Bold & Not in Sync With The Number
  raaghu-components/src/rds-comp-customer-reviews/rds-comp-customer-reviews.tsx
Labels: Bug

#2388 Resolved Bug 2382 : Developer Mode > Standard > Apply Button is Not Enabled Even After Entering All Details
  raaghu-components/src/rds-comp-developer-mode/rds-comp-developer-mode.tsx
Labels: Bug

#2389 Resolved Bug 2384 & 2387 : Component > Application > Few Issues on Scopes & Workflows
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.stories.tsx
  raaghu-components/src/rds-comp-application-basic/rds-comp-application-basic.tsx
  raaghu-elements/src/rds-dropdown-list/rds-dropdown-list.tsx
Labels: Bug

#2397 Completed Task 2394 : Design System > MUI > Change theme and styling
  raaghu-elements/rds-pagination/rds-pagination.scss
  raaghu-elements/rds-pagination/rds-pagination.stories.tsx
  raaghu-elements/rds-pagination/rds-pagination.tsx
Labels: Task, Enhancement

#2396 Completed Task 2394 : Design System > MUI > Change theme and styling
  package.json
  raaghu-elements/rds-input/rds-input.scss
  raaghu-elements/rds-input/rds-input.stories.tsx
  raaghu-elements/rds-input/rds-input.tsx
  raaghu-elements/rds-loader/rds-loader.scss
  raaghu-elements/rds-loader/rds-loader.stories.tsx
  raaghu-elements/rds-loader/rds-loader.tsx
  raaghu-elements/rds-menu/rds-menu.stories.tsx
  raaghu-elements/rds-modal/rds-modal.scss
  raaghu-elements/rds-modal/rds-modal.stories.tsx
  raaghu-elements/rds-modal/rds-modal.tsx
  raaghu-elements/rds-tooltip/rds-tooltip.scss
  raaghu-elements/rds-tooltip/rds-tooltip.stories.tsx
  raaghu-elements/rds-tooltip/rds-tooltip.tsx
Labels: Enhancement

#2400 Completed Task 2394 : Design System > MUI > Change theme and styling
  .storybook/manager-head.html
  .storybook/manager.ts
  raaghu-elements/rds-header/ProfileMenu.tsx
  raaghu-elements/rds-header/rds-header.scss
  raaghu-elements/rds-header/rds-header.stories.tsx
  raaghu-elements/rds-header/rds-header.tsx
  raaghu-elements/rds-menu/rds-menu.scss
  raaghu-elements/rds-menu/rds-menu.stories.tsx
  raaghu-elements/rds-menu/rds-menu.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.css
  raaghu-layouts/rds-comp-layout/rds-comp-layout.scss
  raaghu-layouts/rds-comp-layout/rds-comp-layout.stories.tsx
  raaghu-layouts/rds-comp-layout/rds-comp-layout.tsx
Labels: Enhancement

#2398 Completed Task 2392 : Design System > MUI > Change theme and styling.
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.scss
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.stories.tsx
  raaghu-elements/rds-breadcrumbs/rds-breadcrumbs.tsx
  raaghu-elements/rds-button/rds-button.scss
  raaghu-elements/rds-button/rds-button.stories.tsx
  raaghu-elements/rds-button/rds-button.tsx
  raaghu-elements/rds-carousel/rds-carousel.scss
  raaghu-elements/rds-carousel/rds-carousel.stories.tsx
  raaghu-elements/rds-carousel/rds-carousel.tsx
  raaghu-elements/rds-checkbox/rds-checkbox.scss
  raaghu-elements/rds-checkbox/rds-checkbox.stories.tsx
  raaghu-elements/rds-checkbox/rds-checkbox.tsx
  raaghu-elements/rds-switch/rds-switch.scss
  raaghu-elements/rds-switch/rds-switch.stories.tsx
  raaghu-elements/rds-switch/rds-switch.tsx
Labels: Enhancement
